<a href="https://colab.research.google.com/github/japabon216/Trabajo_de_grado_SM_Para_Clasificacion_ADL_Algoritmos_SL/blob/main/Parte_1_Preparacion_de_datos_(1_8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import os
import csv
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
drive.mount('/content/drive')

Mounted at /content/drive

# Funciones

In [ ]:
import random
import pandas as pd

def resample_dataframe(df):
    original_frequency = df['Frequency'].iloc[0]

    if original_frequency == 50:
        return df

    elif original_frequency > 50:
        new_rows = int(len(df) * (50 / original_frequency))
        drop_indices = random.sample(range(len(df)), len(df) - new_rows)

        new_df = df.drop(drop_indices).copy()

        new_df['Frequency'] = 50

        return new_df

    else:
        new_frequency = 50

        grouped = df.groupby('User')

        resampled_data = []

        for group_name, group_data in grouped:
            desired_rows = int(len(group_data) * (new_frequency / group_data['Frequency'].iloc[0]))

            repeated_group = pd.concat([group_data] * (desired_rows // len(group_data)))

            remaining_rows = desired_rows - len(repeated_group)
            if remaining_rows > 0:
                additional_rows = group_data.sample(n=remaining_rows, replace=True)
                repeated_group = pd.concat([repeated_group, additional_rows])

            ordered_group = repeated_group.sort_index()

            resampled_data.append(ordered_group)

        resampled_data = pd.concat(resampled_data, ignore_index=True)
        resampled_data['Frequency'] = 50
        return resampled_data

In [ ]:
# Funcion para ver los valores válidos de un acelerometro
import plotly.graph_objects as go
import pandas as pd

def grafico_acelerometro_valido(df):

    valores_nulos = df[['X_Acc', 'Y_Acc', 'Z_Acc']].isnull().any(axis=1).sum()
    valores_validos = len(df) - valores_nulos


    # Calcular los porcentajes
    porcentaje_nulos = (valores_nulos / len(df)) * 100
    porcentaje_validos = (valores_validos / len(df)) * 100

    labels = ['Valores nulos', 'Valores válidos']
    values = [porcentaje_nulos, porcentaje_validos]

    fig = go.Figure(data=[go.Pie(labels=labels, values=values)])

    fig.update_layout(
        title="Porcentaje de valores nulos y valores válidos en el acelerómetro"
    )

    fig.show()

In [ ]:
# Valores máximos y mínimos en el acelerometro
import plotly.graph_objects as go
import pandas as pd

def grafico_acelerometro_max_min(df):

    columnas = ['X_Acc', 'Y_Acc', 'Z_Acc']
    df_columnas = df[columnas]

    media = df_columnas.mean()
    mediana = df_columnas.median()
    maximo = df_columnas.max()
    minimo = df_columnas.min()

    desplazamiento = (media.max() - media.min()) * 0.05

    fig = go.Figure()

    fig.add_trace(go.Bar(
        x=columnas,
        y=media,
        name='Media',
        marker_color='rgba(55, 128, 191, 0.7)'
    ))

    fig.add_trace(go.Bar(
        x=columnas,
        y=mediana,
        name='Mediana',
        marker_color='rgba(219, 64, 82, 0.7)'
    ))

    for columna, valor_max, valor_min in zip(columnas, maximo, minimo):
        fig.add_annotation(
            x=columna,
            y=media.max() + desplazamiento,
            text="Máximo: " + str(valor_max),
            showarrow=False,
            font=dict(color='green')
        )
        fig.add_annotation(
            x=columna,
            y=media.min() - desplazamiento,
            text="Mínimo: " + str(valor_min),
            showarrow=False,
            font=dict(color='purple')
        )

    fig.update_layout(
        title="Media, Mediana y Etiquetas de Máximo y Mínimo de las columnas del acelerometro",
        xaxis_title="Columnas",
        yaxis_title="Valor"
    )

    fig.show()

In [ ]:
#Valores validos giroscopio
import plotly.graph_objects as go
import pandas as pd

def grafico_giroscopio_valido(df):

    valores_nulos = df[['X_Gyro', 'Y_Gyro', 'Z_Gyro']].isnull().any(axis=1).sum()
    valores_validos = len(df) - valores_nulos

    porcentaje_nulos = (valores_nulos / len(df)) * 100
    porcentaje_validos = (valores_validos / len(df)) * 100

    labels = ['Valores nulos', 'Valores válidos']
    values = [porcentaje_nulos, porcentaje_validos]

    fig = go.Figure(data=[go.Pie(labels=labels, values=values)])

    fig.update_layout(
        title="Porcentaje de valores nulos y valores válidos en el giroscopio"
    )
    fig.show()

In [ ]:
#Valores máximos y mínimos giroscopio
import plotly.graph_objects as go
import pandas as pd

def grafico_giroscopio_max_min(df):

    columnas = ['X_Gyro', 'Y_Gyro', 'Z_Gyro']
    df_columnas = df[columnas]

    media = df_columnas.mean()
    mediana = df_columnas.median()
    maximo = df_columnas.max()
    minimo = df_columnas.min()

    desplazamiento = (media.max() - media.min()) * 0.05

    fig = go.Figure()

    fig.add_trace(go.Bar(
        x=columnas,
        y=media,
        name='Media',
        marker_color='rgba(55, 128, 191, 0.7)'
    ))

    fig.add_trace(go.Bar(
        x=columnas,
        y=mediana,
        name='Mediana',
        marker_color='rgba(219, 64, 82, 0.7)'
    ))

    for columna, valor_max, valor_min in zip(columnas, maximo, minimo):
        fig.add_annotation(
            x=columna,
            y=media.max() + desplazamiento,
            text="Máximo: " + str(valor_max),
            showarrow=False,
            font=dict(color='green')
        )
        fig.add_annotation(
            x=columna,
            y=media.min() - desplazamiento,
            text="Mínimo: " + str(valor_min),
            showarrow=False,
            font=dict(color='purple')
        )

    fig.update_layout(
        title="Media, Mediana y Etiquetas de Máximo y Mínimo de las columnas del giroscopio",
        xaxis_title="Columnas",
        yaxis_title="Valor"
    )

    fig.show()

In [ ]:
#Porcentaje de actividades validas
import plotly.graph_objects as go
import pandas as pd

def grafico_activity(df):

    columna_actividad = df['Activity']

    valores_validos = columna_actividad.notnull().sum()
    valores_nulos = columna_actividad.isnull().sum()

    # Calcular los porcentajes
    porcentaje_validos = (valores_validos / len(columna_actividad)) * 100
    porcentaje_nulos = (valores_nulos / len(columna_actividad)) * 100

    labels = ['Valores válidos', 'Valores nulos']
    values = [porcentaje_validos, porcentaje_nulos]

    fig = go.Figure(data=[go.Pie(labels=labels, values=values)])

    fig.update_layout(
        title="Porcentaje de valores nulos y valores válidos en la columna 'Activity'"
    )

    fig.show()

# Dataset número 1. UMAFALL_Dataset

## Preparación del Dataset número 1.

Debido a que este en este dataset todos sus archivos CSV tienen informoación necesaria, pero que afectan el precesamiento en sus primeras 40 filas, se borran las 40 filas de los 746 archivos de la carpeta de UMAFALL_Dataset.

In [ ]:
# Ruta de la carpeta con los archivos CSV
folder_path = "/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset"

# Ruta de la carpeta donde se guardarán los archivos corregidos
new_folder_path = "/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset_Corregido"

# Nombre del header que se buscará
header_name = "% TimeStamp"

# Porcentaje de similitud mínimo para considerar que se encontró el header
header_similarity = 0.6

# Contador de archivos exitosos
successful_files = 0

# Contador de archivos con errores
error_files = 0

# Número máximo de archivos con errores permitidos
max_error_files = 5

# Recorremos todos los archivos de la carpeta
for filename in sorted(os.listdir(folder_path)):

    if filename.endswith(".csv"):

        file_path = os.path.join(folder_path, filename)

        new_filename = "new_" + filename

        new_file_path = os.path.join(new_folder_path, new_filename)

        try:
            with open(file_path, "r") as f:
                reader = csv.reader(f, delimiter=";")
                rows = list(reader)

                header_found = False
                for i, row in enumerate(rows):
                    similarity = sum([word in row[0] for word in header_name.split()]) / len(header_name.split())
                    if similarity >= header_similarity:
                        header_found = True
                        break

                if not header_found:
                    raise ValueError("No se encontró el header adecuado")

                # Borramos las filas anteriores al header
                rows = rows[i:]

            with open(new_file_path, "w", newline="") as f:
                writer = csv.writer(f, delimiter=";")
                writer.writerows(rows)

            successful_files += 1

        except Exception as e:
            # Si ocurre un error, incrementamos el contador de archivos con errores
            error_files += 1

            # Si se alcanza el límite máximo de errores, detenemos el programa
            if error_files >= max_error_files:
                print("Se alcanzó el límite máximo de archivos con errores permitidos")
                break

            # Si no, mostramos el mensaje de error y continuamos con el siguiente archivo
            print(f"Error en el archivo {filename}: {str(e)}")
            continue

print(f"{successful_files} archivos fueron exitosamente creados del número total de archivos que es {len(os.listdir(folder_path))}")

747 archivos fueron exitosamente creados del número total de archivos que es 747

Como resultado se tiene una nueva Carpeta en Drive que se llama: UMAFall_Dataset_Corregido

En el siguiente recuadro se tiene cómo se visualizaba el archivo del dataset sin corregir:

In [ ]:
import pandas as pd

Dataset_Sin_Corregir = pd.read_csv("/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset/UMAFall_Subject_01_ADL_Aplausing_1_2017-04-14_23-38-23.csv")
Dataset_Sin_Corregir

     % Universidad de Malaga - ETSI de Telecomunicacion (Spain)
0     % Date: 2017-04-14_23:38:23                   ...
1     % ID: Subject_01_ADL_Aplausing_1              ...
2     % Name: Subject_01                            ...
3     % Age: 67                                     ...
4     % Height(cm): 156                             ...
...                                                 ...
6589  14774;295;-63.66666793823242;48.16666793823242...
6590  14832;296;-63.83333206176758;48.83333206176758...
6591  14877;297;-63.33333206176758;49.66666793823242...
6592  14927;298;-63;48.33333206176758;95.83333587646...
6593  14969;299;-62.33333206176758;49.33333206176758...

[6594 rows x 1 columns]

Como se puede observar, el dataset sin corregir tiene información previa que explica el contenido del dataset, pero que no aporta nada a la visualización del Dataframe, por eso se utiliza el código de "Eliminar_Filas" que se presento anteriormente y se tiene el siguiente dataset corregido.

In [ ]:
Dataset_Corregido = pd.read_csv("/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset_Corregido/new_UMAFall_Subject_01_ADL_Aplausing_1_2017-04-14_23-38-23.csv")
Dataset_Corregido

     % TimeStamp; Sample No; X-Axis; Y-Axis; Z-Axis; Sensor Type; Sensor ID;
0     102;1;-0.1387496441602707;0.8868721723556519;0...
1     102;2;-0.1381397247314453;0.8865065574645996;0...
2     102;3;-0.1348443180322647;0.8895576596260071;0...
3     102;4;-0.1402153074741364;0.8866279125213623;0...
4     102;5;-0.1391168385744095;0.8862622380256653;0...
...                                                 ...
6557  14774;295;-63.66666793823242;48.16666793823242...
6558  14832;296;-63.83333206176758;48.83333206176758...
6559  14877;297;-63.33333206176758;49.66666793823242...
6560  14927;298;-63;48.33333206176758;95.83333587646...
6561  14969;299;-62.33333206176758;49.33333206176758...

[6562 rows x 1 columns]

Ya se eliminaron las filas que no se necesitaban en los archivos de origen de este dataset, y se tiene en la ruta '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset_Corregido/', sin embargo, hace falta reconocer la actividad en las columnas, así mismo como el ID del sujeto, esta información se encuentra en el nombre de cada archivo, a continuación, se realiza el código para esto.

**Creación del TimeStamp REAL, así como en el mismo código agregar la prueba, user y activity **

In [ ]:
#Código para que el timestamp sea el real, es decir combinando el timestamp del nombre con el de las filas, es decir adicionando los milisegundos

x = 'new_UMAFall_Subject_01_ADL_Aplausing_2_2017-04-14_23-38-59'
ruta = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset_Corregido'
rutaout = f'/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset/{x}.csv'
ruta_completa = os.path.join(ruta, x + '.csv')

df = pd.read_csv(ruta_completa, delimiter=';')

df['% TimeStamp'] = pd.to_timedelta(df['% TimeStamp'], unit='ms')

time_start_str = '2017-04-14_23-38-59'
time_start = datetime.datetime.strptime(time_start_str, '%Y-%m-%d_%H-%M-%S')

# Añadimos el timedelta a la fecha inicial
df['Real TimeStamp'] = df['% TimeStamp'].apply(lambda x: time_start + x)

df.to_csv(rutaout)

In [ ]:
df

,% TimeStamp,Sample No,X-Axis,Y-Axis,Z-Axis,Sensor Type,Sensor ID,,Real TimeStamp
0,0 days 00:00:00.139000,1,0.409448,0.773596,-0.338626,0,0,NaN,2017-04-14 23:38:59.139
1,0 days 00:00:00.139000,2,0.406640,0.771276,-0.336062,0,0,NaN,2017-04-14 23:38:59.139
2,0 days 00:00:00.139000,3,0.407495,0.769445,-0.337405,0,0,NaN,2017-04-14 23:38:59.139
3,0 days 00:00:00.139000,4,0.403223,0.766149,-0.332522,0,0,NaN,2017-04-14 23:38:59.139
4,0 days 00:00:00.139000,5,0.402369,0.763952,-0.334598,0,0,NaN,2017-04-14 23:38:59.139
...,...,...,...,...,...,...,...,...,...
6563,0 days 00:00:14.808000,296,-22.166666,47.500000,96.000000,2,4,NaN,2017-04-14 23:39:13.808
6564,0 days 00:00:14.858000,297,-22.500000,46.666668,96.833336,2,4,NaN,2017-04-14 23:39:13.858
6565,0 days 00:00:14.903000,298,-22.333334,48.333332,95.500000,2,4,NaN,2017-04-14 23:39:13.903
6566,0 days 00:00:14.949000,299,-22.333334,46.833332,95.166664,2,4,NaN,2017-04-14 23:39:13.949
6567,0 days 00:00:15.005000,300,-22.333334,49.166668,95.166664,2,4,NaN,2017-04-14 23:39:14.005

In [ ]:
#Timestamp real para todos los archivos, el código anterior aplicado a todos los archivos

input_folder = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset_Corregido'
output_folder = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset'

files = os.listdir(input_folder)

csv_files = [f for f in files if f.endswith('.csv')]

for file_name in csv_files:
    input_path = os.path.join(input_folder, file_name)
    output_path = os.path.join(output_folder, file_name)

    df = pd.read_csv(input_path, delimiter=';')

    df['% TimeStamp'] = pd.to_timedelta(df['% TimeStamp'], unit='ms')

    time_start_str = file_name.split('_')[-2] + '_' + file_name.split('_')[-1].split('.')[0]
    time_start = datetime.datetime.strptime(time_start_str, '%Y-%m-%d_%H-%M-%S')

    df['Real TimeStamp'] = df['% TimeStamp'].apply(lambda x: time_start + x)

    df.to_csv(output_path, index=False)

A los archivos creados anteriormente con el timestamp real, procedemos a agregarles el Trial, User y Activity (información que se encuentra en el nombre de los archivos)

In [ ]:
output_folder = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset'

# Lista todos los archivos en la carpeta de salida
files = os.listdir(output_folder)

csv_files = [f for f in files if f.endswith('.csv')]

for file_name in csv_files:
    output_path = os.path.join(output_folder, file_name)

    df = pd.read_csv(output_path)

    # Agregamos las columnas 'Trial', 'User' y 'Activity'
    df['Trial'] = int(file_name.split('_')[-3])
    df['User'] = int(file_name.split('_')[3])
    df['Activity'] = "_".join(file_name.split('_')[5:-3])

    df.to_csv(output_path, index=False)

In [ ]:
prueba = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset/new_UMAFall_Subject_06_ADL_LyingDown_OnABed_1_2016-06-13_21-24-41.csv')
prueba

,% TimeStamp,Sample No,X-Axis,Y-Axis,Z-Axis,Sensor Type,Sensor ID,,Real TimeStamp,Trial,User,Activity
0,0 days 00:00:00.095000,1,0.055213,0.931183,-0.186043,0,0,NaN,2016-06-13 21:24:41.095,1,6,LyingDown_OnABed
1,0 days 00:00:00.095000,2,0.054724,0.929840,-0.185433,0,0,NaN,2016-06-13 21:24:41.095,1,6,LyingDown_OnABed
2,0 days 00:00:00.095000,3,0.053016,0.930450,-0.186897,0,0,NaN,2016-06-13 21:24:41.095,1,6,LyingDown_OnABed
3,0 days 00:00:00.095000,4,0.051185,0.930084,-0.186287,0,0,NaN,2016-06-13 21:24:41.095,1,6,LyingDown_OnABed
4,0 days 00:00:00.095000,5,0.053747,0.932770,-0.183967,0,0,NaN,2016-06-13 21:24:41.095,1,6,LyingDown_OnABed
...,...,...,...,...,...,...,...,...,...,...,...,...
6564,0 days 00:00:14.780000,295,-81.333336,-19.666666,21.833334,2,4,NaN,2016-06-13 21:24:55.780,1,6,LyingDown_OnABed
6565,0 days 00:00:14.821000,296,-83.666664,-20.333334,21.833334,2,4,NaN,2016-06-13 21:24:55.821,1,6,LyingDown_OnABed
6566,0 days 00:00:14.865000,297,-81.833336,-19.833334,22.500000,2,4,NaN,2016-06-13 21:24:55.865,1,6,LyingDown_OnABed
6567,0 days 00:00:14.910000,298,-81.666664,-21.166666,63.833332,2,4,NaN,2016-06-13 21:24:55.910,1,6,LyingDown_OnABed
6568,0 days 00:00:14.975000,299,-80.333336,-19.000000,22.166666,2,4,NaN,2016-06-13 21:24:55.975,1,6,LyingDown_OnABed

Se realiza la unión de los CSV que se tienen actualmente con el nuevo folder creado anteriormente.

In [ ]:
#Union de los csv

folder_path = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/UMAFall_Dataset'

csv_files = [file for file in sorted(os.listdir(folder_path)) if file.endswith('.csv')]

dfs = []
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    dfs.append(df)

concatenated_df = pd.concat(dfs, axis=0, ignore_index=True)

output_folder = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/Dataset1_1_SIN_CODIGO'
output_file = os.path.join(output_folder, 'dataset_1_1.csv')

concatenated_df.to_csv(output_file, index=False)

In [ ]:
concatenated_df

,% TimeStamp,Sample No,X-Axis,Y-Axis,Z-Axis,Sensor Type,Sensor ID,,Real TimeStamp,Trial,User,Activity
0,0 days 00:00:00.102000,1,-0.13875,0.886872,0.331029,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing
1,0 days 00:00:00.102000,2,-0.13814,0.886507,0.332372,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing
2,0 days 00:00:00.102000,3,-0.134844,0.889558,0.33115,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing
3,0 days 00:00:00.102000,4,-0.140215,0.886628,0.333714,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing
4,0 days 00:00:00.102000,5,-0.139117,0.886262,0.334568,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing
...,...,...,...,...,...,...,...,...,...,...,...,...
4688249,0 days 00:00:14.604000,277,-60.833332,-8.333333,114.5,2,4,NaN,2016-06-07 21:37:28.604,6,19,lateralFall
4688250,0 days 00:00:14.687000,278,-61.833332,-8.833333,115.0,2,4,NaN,2016-06-07 21:37:28.687,6,19,lateralFall
4688251,0 days 00:00:14.766000,279,-60.5,-7.5,115.166664,2,4,NaN,2016-06-07 21:37:28.766,6,19,lateralFall
4688252,0 days 00:00:14.867000,280,-59.666668,-8.333333,115.5,2,4,NaN,2016-06-07 21:37:28.867,6,19,lateralFall
4688253,0 days 00:00:14.977000,281,-60.833332,-8.666667,115.166664,2,4,NaN,2016-06-07 21:37:28.977,6,19,lateralFall

In [ ]:
Ruta = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/Dataset1_1_SIN_CODIGO/dataset_1_1.csv'
Dataset1 = pd.read_csv(Ruta)
Dataset1

Asignamos las respectivas frecuencias dependiendo del valor de Sensor ID y eliminamos los valores 2 de sensor type, que corresponden a magnetometro

In [ ]:
ruta = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/Dataset1_1_SIN_CODIGO/dataset_1_1.csv'

dtype = {'Sensor ID': int}  # Especificar el tipo de datos de la columna "Sensor ID"

df = pd.read_csv(ruta, dtype=dtype)

df = df[df[' Sensor Type'] != 2]

df['Frequency'] = ""

df.loc[df[' Sensor ID'] == 0, 'Frequency'] = 200

df.loc[df[' Sensor ID'] == 1, 'Frequency'] = 20

df.loc[df[' Sensor ID'] == 2, 'Frequency'] = 20

df.loc[df[' Sensor ID'] == 3, 'Frequency'] = 20

df.loc[df[' Sensor ID'] == 4, 'Frequency'] = 20

In [ ]:
df

,% TimeStamp,Sample No,X-Axis,Y-Axis,Z-Axis,Sensor Type,Sensor ID,,Real TimeStamp,Trial,User,Activity,Frequency
0,0 days 00:00:00.102000,1,-0.13875,0.886872,0.331029,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
1,0 days 00:00:00.102000,2,-0.13814,0.886507,0.332372,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
2,0 days 00:00:00.102000,3,-0.134844,0.889558,0.33115,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
3,0 days 00:00:00.102000,4,-0.140215,0.886628,0.333714,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
4,0 days 00:00:00.102000,5,-0.139117,0.886262,0.334568,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4687968,0 days 00:00:14.600000,277,-0.648438,0.242188,-2.53125,1,4,NaN,2016-06-07 21:37:28.600,6,19,lateralFall,20
4687969,0 days 00:00:14.683000,278,-0.414062,0.414062,-2.0625,1,4,NaN,2016-06-07 21:37:28.683,6,19,lateralFall,20
4687970,0 days 00:00:14.763000,279,0.75,0.554688,-2.539062,1,4,NaN,2016-06-07 21:37:28.763,6,19,lateralFall,20
4687971,0 days 00:00:14.854000,280,0.664062,0.515625,-2.328125,1,4,NaN,2016-06-07 21:37:28.854,6,19,lateralFall,20
4687972,0 days 00:00:14.973000,281,-0.984375,-2.039062,-2.710938,1,4,NaN,2016-06-07 21:37:28.973,6,19,lateralFall,20

In [ ]:
df.to_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/Dataset1_1_SIN_CODIGO/dataset_1_1.csv')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/Dataset1_1_SIN_CODIGO/dataset_1_1.csv')

<ipython-input-18-5e5f1b43908b>:1: DtypeWarning: Columns (4,5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/Dataset1_1_SIN_CODIGO/dataset_1_1.csv')

Ya tenemos el dataframe con las frecuencias, en base a estas vamos a dividir el dataset, primero en un dataset para las frecuencias de 200, este sensor solo incluye mediociones de acelerometro, mientras que los de frecuencia 20 incluyen tanto acelerometro como giroscopio y 4 sensores, por lo que hay que unirlos en base al timestamp, y asignar el codigo en base a los valores de las columnas de los sensores. Por las diferencias presentadas aquí se propone dividir el dataset en 2.

In [ ]:
df_200 = df[df['Frequency'] == 200]
df_200.to_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASET_SEPARADO/UMAFALL_200.csv', index=False)

df_20 = df[df['Frequency'] == 20]
df_20.to_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASET_SEPARADO/UMAFALL_20.csv', index=False)

In [ ]:
df_200 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASET_SEPARADO/UMAFALL_200.csv')

<ipython-input-22-0ecb76c50e9b>:1: DtypeWarning: Columns (2,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_200 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASET_SEPARADO/UMAFALL_200.csv')

In [ ]:
df_200

,% TimeStamp,Sample No,X-Axis,Y-Axis,Z-Axis,Sensor Type,Sensor ID,,Real TimeStamp,Trial,User,Activity,Frequency
0,0 days 00:00:00.102000,1,-0.13875,0.886872,0.331029,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
1,0 days 00:00:00.102000,2,-0.13814,0.886507,0.332372,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
2,0 days 00:00:00.102000,3,-0.134844,0.889558,0.33115,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
3,0 days 00:00:00.102000,4,-0.140215,0.886628,0.333714,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
4,0 days 00:00:00.102000,5,-0.139117,0.886262,0.334568,0,0,NaN,2017-04-14 23:38:23.102,1,1,Aplausing,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235536,0 days 00:00:14.978000,3030,-0.773532,-0.272756,-0.590128,0,0,NaN,2016-06-07 21:37:28.978,6,19,lateralFall,200
2235537,0 days 00:00:14.989000,3031,-0.775302,-0.274282,-0.591104,0,0,NaN,2016-06-07 21:37:28.989,6,19,lateralFall,200
2235538,0 days 00:00:14.992000,3032,-0.772128,-0.272634,-0.593302,0,0,NaN,2016-06-07 21:37:28.992,6,19,lateralFall,200
2235539,0 days 00:00:14.992000,3033,-0.772494,-0.270071,-0.589823,0,0,NaN,2016-06-07 21:37:28.992,6,19,lateralFall,200
2235540,0 days 00:00:15.033000,3034,-0.774142,-0.271963,-0.58848,0,0,NaN,2016-06-07 21:37:29.033,6,19,lateralFall,200

**Primero resolveremos el dataset de 200 Hz**

In [ ]:
df_200.drop(columns=[' Sensor Type'], inplace=True)
df_200.drop(columns=['% TimeStamp'], inplace=True)
df_200 = df_200.rename(columns={'Real TimeStamp': 'TimeStamp'})
df_200 = df_200.rename(columns={'Actividad': 'Activity'})
df_200 = df_200.rename(columns={' X-Axis': 'X_Acc'})
df_200 = df_200.rename(columns={' Y-Axis': 'Y_Acc'})
df_200 = df_200.rename(columns={' Z-Axis': 'Z_Acc'})

In [ ]:
#Asiganmos el código y agregamos las columnas del giroscopio
df_200.insert(10,'Dataset', 1)
df_200.insert(11,'Code', '012')

df_200.insert(12,'X_Acc_6', np.nan)
df_200.insert(13,'Y_Acc_6', np.nan)
df_200.insert(14,'Z_Acc_6', np.nan)
df_200.insert(15,'X_Gyro', np.nan)
df_200.insert(16,'Y_Gyro', np.nan)
df_200.insert(17,'Z_Gyro', np.nan)

In [ ]:
df_200 = df_200.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial', ' Sample No'])

In [ ]:
df_200

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial,Sample No
0,1,Aplausing,-0.13875,0.886872,0.331029,NaN,NaN,NaN,NaN,NaN,NaN,012,2017-04-14 23:38:23.102,200,1,1,1
1,1,Aplausing,-0.13814,0.886507,0.332372,NaN,NaN,NaN,NaN,NaN,NaN,012,2017-04-14 23:38:23.102,200,1,1,2
2,1,Aplausing,-0.134844,0.889558,0.33115,NaN,NaN,NaN,NaN,NaN,NaN,012,2017-04-14 23:38:23.102,200,1,1,3
3,1,Aplausing,-0.140215,0.886628,0.333714,NaN,NaN,NaN,NaN,NaN,NaN,012,2017-04-14 23:38:23.102,200,1,1,4
4,1,Aplausing,-0.139117,0.886262,0.334568,NaN,NaN,NaN,NaN,NaN,NaN,012,2017-04-14 23:38:23.102,200,1,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235536,1,lateralFall,-0.773532,-0.272756,-0.590128,NaN,NaN,NaN,NaN,NaN,NaN,012,2016-06-07 21:37:28.978,200,19,6,3030
2235537,1,lateralFall,-0.775302,-0.274282,-0.591104,NaN,NaN,NaN,NaN,NaN,NaN,012,2016-06-07 21:37:28.989,200,19,6,3031
2235538,1,lateralFall,-0.772128,-0.272634,-0.593302,NaN,NaN,NaN,NaN,NaN,NaN,012,2016-06-07 21:37:28.992,200,19,6,3032
2235539,1,lateralFall,-0.772494,-0.270071,-0.589823,NaN,NaN,NaN,NaN,NaN,NaN,012,2016-06-07 21:37:28.992,200,19,6,3033
2235540,1,lateralFall,-0.774142,-0.271963,-0.58848,NaN,NaN,NaN,NaN,NaN,NaN,012,2016-06-07 21:37:29.033,200,19,6,3034

In [ ]:
df_200 = df_200.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])
df_200.to_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_200.csv')

El dataset presento un problema y es que algunos valores de acelerometro y giroscopio se leian equivocadamente, tomaba una coma como signo de mil, lo cual no era correcto, se propuso el siguiente código como solución:
Adicionalmente, como un primer vistazo se cambia las unidades del acelerometro de g a ms2

In [ ]:
def convert_decimal(val):
    # Si el valor es un flotante, lo devolvemos tal cual
    if isinstance(val, float):
        return val

    # Reemplaza la coma por un punto si el valor está en notación científica
    if 'E' in val or 'e' in val:
        val = val.replace(',', '.')

    # Divide el string en dos partes usando el primer punto como separador
    parts = val.split('.', 1)

    # Si solo hay una parte, no había ningún punto, por lo que devolvemos el número tal cual
    if len(parts) == 1:
        return float(parts[0])

    # Si hay dos partes, eliminamos los puntos adicionales de la segunda parte y las unimos de nuevo
    return float(parts[0] + '.' + parts[1].replace('.', ''))

# Ahora aplicamos esta función a las columnas
df_200['X_Acc'] = df_200['X_Acc'].apply(convert_decimal)
df_200['Y_Acc'] = df_200['Y_Acc'].apply(convert_decimal)
df_200['Z_Acc'] = df_200['Z_Acc'].apply(convert_decimal)

# Ahora realiza la conversión de las unidades.
g = 9.81
df_200['X_Acc'] = df_200['X_Acc'] * g
df_200['Y_Acc'] = df_200['Y_Acc'] * g
df_200['Z_Acc'] = df_200['Z_Acc'] * g

In [ ]:
df_200

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,0,1,Aplausing,-1.361134,8.700216,3.247392,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
1,1,1,Aplausing,-1.355151,8.696629,3.260564,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
2,2,1,Aplausing,-1.322823,8.726561,3.248583,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
3,3,1,Aplausing,-1.375512,8.697820,3.273737,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
4,4,1,Aplausing,-1.364736,8.694233,3.282116,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235536,2235536,1,lateralFall,-7.588349,-2.675740,-5.789155,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:28.978,200,19,6
2235537,2235537,1,lateralFall,-7.605712,-2.690709,-5.798734,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:28.989,200,19,6
2235538,2235538,1,lateralFall,-7.574578,-2.674542,-5.820289,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:28.992,200,19,6
2235539,2235539,1,lateralFall,-7.578170,-2.649396,-5.786161,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:28.992,200,19,6
2235540,2235540,1,lateralFall,-7.594336,-2.667956,-5.772988,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:29.033,200,19,6

In [ ]:
df_200 = df_200.drop(['Unnamed: 0'], axis=1)
df_200

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,1,Aplausing,-1.361134,8.700216,3.247392,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
1,1,Aplausing,-1.355151,8.696629,3.260564,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
2,1,Aplausing,-1.322823,8.726561,3.248583,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
3,1,Aplausing,-1.375512,8.697820,3.273737,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
4,1,Aplausing,-1.364736,8.694233,3.282116,NaN,NaN,NaN,NaN,NaN,NaN,12,2017-04-14 23:38:23.102,200,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235536,1,lateralFall,-7.588349,-2.675740,-5.789155,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:28.978,200,19,6
2235537,1,lateralFall,-7.605712,-2.690709,-5.798734,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:28.989,200,19,6
2235538,1,lateralFall,-7.574578,-2.674542,-5.820289,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:28.992,200,19,6
2235539,1,lateralFall,-7.578170,-2.649396,-5.786161,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:28.992,200,19,6
2235540,1,lateralFall,-7.594336,-2.667956,-5.772988,NaN,NaN,NaN,NaN,NaN,NaN,12,2016-06-07 21:37:29.033,200,19,6

In [ ]:
df_200.to_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_1.csv', index=False)

##**Dataset de 20 Hz**

In [ ]:
df_20 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASET_SEPARADO/UMAFALL_20.csv')

<ipython-input-2-a7bb90827c94>:1: DtypeWarning: Columns (2,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_20 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASET_SEPARADO/UMAFALL_20.csv')

In [ ]:
df_20

,% TimeStamp,Sample No,X-Axis,Y-Axis,Z-Axis,Sensor Type,Sensor ID,,Real TimeStamp,Trial,User,Activity,Frequency
0,0 days 00:00:00.123000,0,0.72168,0.122559,0.754883,0,1,NaN,2017-04-14 23:38:23.123,1,1,Aplausing,20
1,0 days 00:00:00.130000,1,0.72168,0.122559,0.754883,0,1,NaN,2017-04-14 23:38:23.130,1,1,Aplausing,20
2,0 days 00:00:00.156000,2,0.696045,0.117432,0.754883,0,1,NaN,2017-04-14 23:38:23.156,1,1,Aplausing,20
3,0 days 00:00:00.189000,3,0.72168,0.125977,0.77002,0,1,NaN,2017-04-14 23:38:23.189,1,1,Aplausing,20
4,0 days 00:00:00.238000,4,0.710449,0.118652,0.742676,0,1,NaN,2017-04-14 23:38:23.238,1,1,Aplausing,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1635137,0 days 00:00:14.600000,277,-0.648438,0.242188,-2.53125,1,4,NaN,2016-06-07 21:37:28.600,6,19,lateralFall,20
1635138,0 days 00:00:14.683000,278,-0.414062,0.414062,-2.0625,1,4,NaN,2016-06-07 21:37:28.683,6,19,lateralFall,20
1635139,0 days 00:00:14.763000,279,0.75,0.554688,-2.539062,1,4,NaN,2016-06-07 21:37:28.763,6,19,lateralFall,20
1635140,0 days 00:00:14.854000,280,0.664062,0.515625,-2.328125,1,4,NaN,2016-06-07 21:37:28.854,6,19,lateralFall,20
1635141,0 days 00:00:14.973000,281,-0.984375,-2.039062,-2.710938,1,4,NaN,2016-06-07 21:37:28.973,6,19,lateralFall,20

En este momento el dataset incluye datos de acelerometro y giroscopio en las mismas filas y las distingen mediante Sensor Type, esto para nosotros no nos funciona pues debemos tener las medidas paralelamente, por lo que en base al sensor vamos a dividir el dataset. Luego los unimos pero horizontalmente, verificando que estemos uniendo las mediciones tomadas en el mismo tiempo.

In [ ]:
df_accelerometer = df_20[df_20[' Sensor Type'] == 0]
df_gyroscope = df_20[df_20[' Sensor Type'] == 1]

# Eliminar columnas innecesarias para el giroscopio
df_gyroscope = df_gyroscope.drop(['% TimeStamp', ' Sensor Type', 'Real TimeStamp'], axis=1)

# Ordenar los dataset de la misma manera
df_accelerometer.sort_values(by=['User', 'Activity', 'Trial', ' Sensor ID'], inplace=True)
df_gyroscope.sort_values(by=['User', 'Activity', 'Trial', ' Sensor ID'], inplace=True)

df_accelerometer.reset_index(drop=True, inplace=True)
df_gyroscope.reset_index(drop=True, inplace=True)

merged_df = pd.concat([df_accelerometer, df_gyroscope], axis=1)

<ipython-input-12-b4c44b8a982f>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_accelerometer.sort_values(by=['User', 'Activity', 'Trial', ' Sensor ID'], inplace=True)

In [ ]:
merged_df.drop(columns=[' Sensor Type'], inplace=True)
merged_df.drop(columns=['% TimeStamp'], inplace=True)
merged_df.drop(columns=[' Sample No'], inplace=True)
merged_df.drop(columns=['            '], inplace=True)

merged_df = merged_df.rename(columns={'Real TimeStamp': 'TimeStamp'})

Por el contexto de la unión tenemos columnas duplicada lo cual es un problema para eliminar las que no necesitamos, para esto vamos a distingir las columnas y eliminarlas

In [ ]:
# Obtiene los nombres de las columnas
cols = pd.Series(merged_df.columns)

# Encuentra las columnas duplicadas y selecciona la primera aparición de ellas
for dup in cols[cols.duplicated()].unique():
    cols[cols[cols == dup].index.values.tolist()] = [dup + '_' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]

merged_df.columns = cols

cols_to_drop = [' Sensor ID_1', 'Trial_1', 'User_1', 'Activity_1', 'Frequency_1']
merged_df = merged_df.drop(columns=cols_to_drop)

In [ ]:
merged_df.columns

Index([' X-Axis', ' Y-Axis', ' Z-Axis', ' Sensor ID', 'TimeStamp', 'Trial',
       'User', 'Activity', 'Frequency', ' X-Axis_1', ' Y-Axis_1', ' Z-Axis_1'],
      dtype='object')

In [ ]:
merged_df = merged_df.rename(columns={' X-Axis': 'X_Acc'})
merged_df = merged_df.rename(columns={' Y-Axis': 'Y_Acc'})
merged_df = merged_df.rename(columns={' Z-Axis': 'Z_Acc'})
merged_df = merged_df.rename(columns={' X-Axis_1': 'X_Gyro'})
merged_df = merged_df.rename(columns={' Y-Axis_1': 'Y_Gyro'})
merged_df = merged_df.rename(columns={' Z-Axis_1': 'Z_Gyro'})

In [ ]:
merged_df.to_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv')

In [ ]:
merged_df.columns

Index(['Unnamed: 0', 'X_Acc', 'Y_Acc', 'Z_Acc', ' Sensor ID', 'TimeStamp',
       'Trial', 'User', 'Activity', 'Frequency', 'X_Gyro', 'Y_Gyro', 'Z_Gyro'],
      dtype='object')

Agregamos el código mediante un mapeo

In [ ]:
# Primero, definimos un diccionario que mapea los valores actuales a los nuevos valores.
id_to_code = {1: 204, 2: 208, 3: 221, 4: 213}

merged_df['Code'] = merged_df[' Sensor ID'].map(id_to_code)

In [ ]:
merged_df

,Unnamed: 0,X_Acc,Y_Acc,Z_Acc,Sensor ID,TimeStamp,Trial,User,Activity,Frequency,X_Gyro,Y_Gyro,Z_Gyro,Code
0,0,0.72168,0.122559,0.754883,1,2017-04-14 23:38:23.123,1,1,Aplausing,20,-0.765625,-0.617188,-2.453125,204
1,1,0.72168,0.122559,0.754883,1,2017-04-14 23:38:23.130,1,1,Aplausing,20,-0.765625,-0.617188,-2.453125,204
2,2,0.696045,0.117432,0.754883,1,2017-04-14 23:38:23.156,1,1,Aplausing,20,-3.125,0.054688,-2.234375,204
3,3,0.72168,0.125977,0.77002,1,2017-04-14 23:38:23.189,1,1,Aplausing,20,-2.414062,0.1875,-2.867188,204
4,4,0.710449,0.118652,0.742676,1,2017-04-14 23:38:23.238,1,1,Aplausing,20,-2.648438,-2.023438,-2.929688,204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817566,817566,0.221436,-0.075928,-0.934082,4,2016-06-07 21:37:28.596,6,19,lateralFall,20,-0.648438,0.242188,-2.53125,213
817567,817567,0.222412,-0.081299,-0.958496,4,2016-06-07 21:37:28.679,6,19,lateralFall,20,-0.414062,0.414062,-2.0625,213
817568,817568,0.218994,-0.083008,-0.935791,4,2016-06-07 21:37:28.759,6,19,lateralFall,20,0.75,0.554688,-2.539062,213
817569,817569,0.202881,-0.085938,-0.953125,4,2016-06-07 21:37:28.835,6,19,lateralFall,20,0.664062,0.515625,-2.328125,213
817570,817570,0.219238,-0.081543,-0.954834,4,2016-06-07 21:37:28.969,6,19,lateralFall,20,-0.984375,-2.039062,-2.710938,213

In [ ]:
merged_df.insert(14,'Dataset', 1)
merged_df.insert(15,'X_Acc_6', np.nan)
merged_df.insert(16,'Y_Acc_6', np.nan)
merged_df.insert(17,'Z_Acc_6', np.nan)

merged_df = merged_df.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])

In [ ]:
merged_df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,1,Aplausing,0.72168,0.122559,0.754883,-0.765625,-0.617188,-2.453125,NaN,NaN,NaN,204,2017-04-14 23:38:23.123,20,1,1
1,1,Aplausing,0.72168,0.122559,0.754883,-0.765625,-0.617188,-2.453125,NaN,NaN,NaN,204,2017-04-14 23:38:23.130,20,1,1
2,1,Aplausing,0.696045,0.117432,0.754883,-3.125,0.054688,-2.234375,NaN,NaN,NaN,204,2017-04-14 23:38:23.156,20,1,1
3,1,Aplausing,0.72168,0.125977,0.77002,-2.414062,0.1875,-2.867188,NaN,NaN,NaN,204,2017-04-14 23:38:23.189,20,1,1
4,1,Aplausing,0.710449,0.118652,0.742676,-2.648438,-2.023438,-2.929688,NaN,NaN,NaN,204,2017-04-14 23:38:23.238,20,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817566,1,lateralFall,0.221436,-0.075928,-0.934082,-0.648438,0.242188,-2.53125,NaN,NaN,NaN,213,2016-06-07 21:37:28.596,20,19,6
817567,1,lateralFall,0.222412,-0.081299,-0.958496,-0.414062,0.414062,-2.0625,NaN,NaN,NaN,213,2016-06-07 21:37:28.679,20,19,6
817568,1,lateralFall,0.218994,-0.083008,-0.935791,0.75,0.554688,-2.539062,NaN,NaN,NaN,213,2016-06-07 21:37:28.759,20,19,6
817569,1,lateralFall,0.202881,-0.085938,-0.953125,0.664062,0.515625,-2.328125,NaN,NaN,NaN,213,2016-06-07 21:37:28.835,20,19,6
817570,1,lateralFall,0.219238,-0.081543,-0.954834,-0.984375,-2.039062,-2.710938,NaN,NaN,NaN,213,2016-06-07 21:37:28.969,20,19,6

In [ ]:
def convert_decimal(val):

    if isinstance(val, float):
        return val

    parts = val.split('.', 1)

    if len(parts) == 1:
        return float(parts[0])

    return float(parts[0] + '.' + parts[1].replace('.', ''))

merged_df['X_Acc'] = merged_df['X_Acc'].apply(convert_decimal)
merged_df['Y_Acc'] = merged_df['Y_Acc'].apply(convert_decimal)
merged_df['Z_Acc'] = merged_df['Z_Acc'].apply(convert_decimal)
merged_df['X_Gyro'] = merged_df['X_Gyro'].apply(convert_decimal)
merged_df['Y_Gyro'] = merged_df['Y_Gyro'].apply(convert_decimal)
merged_df['Z_Gyro'] = merged_df['Z_Gyro'].apply(convert_decimal)

In [ ]:
# Ahora realiza la conversión de las unidades.
g = 9.81
merged_df['X_Acc'] = merged_df['X_Acc'] * g
merged_df['Y_Acc'] = merged_df['Y_Acc'] * g
merged_df['Z_Acc'] = merged_df['Z_Acc'] * g

In [ ]:
merged_df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,1,Aplausing,7.079678,1.202300,7.405400,-0.765625,-0.617188,-2.453125,NaN,NaN,NaN,204,2017-04-14 23:38:23.123,20,1,1
1,1,Aplausing,7.079678,1.202300,7.405400,-0.765625,-0.617188,-2.453125,NaN,NaN,NaN,204,2017-04-14 23:38:23.130,20,1,1
2,1,Aplausing,6.828201,1.152004,7.405400,-3.125000,0.054688,-2.234375,NaN,NaN,NaN,204,2017-04-14 23:38:23.156,20,1,1
3,1,Aplausing,7.079678,1.235830,7.553892,-2.414062,0.187500,-2.867188,NaN,NaN,NaN,204,2017-04-14 23:38:23.189,20,1,1
4,1,Aplausing,6.969507,1.163979,7.285649,-2.648438,-2.023438,-2.929688,NaN,NaN,NaN,204,2017-04-14 23:38:23.238,20,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817566,1,lateralFall,2.172283,-0.744851,-9.163345,-0.648438,0.242188,-2.531250,NaN,NaN,NaN,213,2016-06-07 21:37:28.596,20,19,6
817567,1,lateralFall,2.181863,-0.797542,-9.402847,-0.414062,0.414062,-2.062500,NaN,NaN,NaN,213,2016-06-07 21:37:28.679,20,19,6
817568,1,lateralFall,2.148333,-0.814307,-9.180110,0.750000,0.554688,-2.539062,NaN,NaN,NaN,213,2016-06-07 21:37:28.759,20,19,6
817569,1,lateralFall,1.990261,-0.843047,-9.350156,0.664062,0.515625,-2.328125,NaN,NaN,NaN,213,2016-06-07 21:37:28.835,20,19,6
817570,1,lateralFall,2.150728,-0.799937,-9.366921,-0.984375,-2.039062,-2.710938,NaN,NaN,NaN,213,2016-06-07 21:37:28.969,20,19,6

In [ ]:
prueba.to_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv')

In [ ]:
prueba = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv')

In [ ]:
prueba.drop(columns=['Unnamed: 0'], inplace=True)
prueba

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,1,Aplausing,7.079678,1.202300,7.405400,-0.765625,-0.617188,-2.453125,NaN,NaN,NaN,204,2017-04-14 23:38:23.123,20,1,1
1,1,Aplausing,7.079678,1.202300,7.405400,-0.765625,-0.617188,-2.453125,NaN,NaN,NaN,204,2017-04-14 23:38:23.130,20,1,1
2,1,Aplausing,6.828201,1.152004,7.405400,-3.125000,0.054688,-2.234375,NaN,NaN,NaN,204,2017-04-14 23:38:23.156,20,1,1
3,1,Aplausing,7.079678,1.235830,7.553892,-2.414062,0.187500,-2.867188,NaN,NaN,NaN,204,2017-04-14 23:38:23.189,20,1,1
4,1,Aplausing,6.969507,1.163979,7.285649,-2.648438,-2.023438,-2.929688,NaN,NaN,NaN,204,2017-04-14 23:38:23.238,20,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817566,1,lateralFall,2.172283,-0.744851,-9.163345,-0.648438,0.242188,-2.531250,NaN,NaN,NaN,213,2016-06-07 21:37:28.596,20,19,6
817567,1,lateralFall,2.181863,-0.797542,-9.402847,-0.414062,0.414062,-2.062500,NaN,NaN,NaN,213,2016-06-07 21:37:28.679,20,19,6
817568,1,lateralFall,2.148333,-0.814307,-9.180110,0.750000,0.554688,-2.539062,NaN,NaN,NaN,213,2016-06-07 21:37:28.759,20,19,6
817569,1,lateralFall,1.990261,-0.843047,-9.350156,0.664062,0.515625,-2.328125,NaN,NaN,NaN,213,2016-06-07 21:37:28.835,20,19,6
817570,1,lateralFall,2.150728,-0.799937,-9.366921,-0.984375,-2.039062,-2.710938,NaN,NaN,NaN,213,2016-06-07 21:37:28.969,20,19,6

In [ ]:
prueba.to_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv')

Por razones que se conocieron más adelante en el proyecto, se eliminan las columnas "X_Acc_6", "Y_Acc_6", "Z_Acc_6", pues ya no son necesarias, esto sucederá en todos los datasets

In [ ]:
ruta = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_1.csv'
ruta2 = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv'
df = pd.read_csv(ruta)
df2 = pd.read_csv(ruta2)
columnas_a_eliminar = ["X_Acc_6", "Y_Acc_6", "Z_Acc_6"]
df = df.drop(columnas_a_eliminar, axis=1)
df2 = df2.drop(columnas_a_eliminar, axis=1)
df.to_csv(ruta, index=False)
df2.to_csv(ruta2,index =False)

FileNotFoundError: ignored

In [ ]:
import pandas as pd
ruta = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_1.csv'
ruta2 = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv'
dataset1_part = pd.read_csv(ruta)
dataset1_part2 = pd.read_csv(ruta2)

In [ ]:
dataset1_part

,Unnamed: 0.1,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,0,1,1,-1.361134,8.700216,3.247392,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
1,1,1,1,1,-1.355151,8.696629,3.260564,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
2,2,2,1,1,-1.322823,8.726561,3.248583,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
3,3,3,1,1,-1.375512,8.697820,3.273737,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
4,4,4,1,1,-1.364736,8.694233,3.282116,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235536,2235536,2235536,1,11,-7.588349,-2.675740,-5.789155,NaN,NaN,NaN,312,2016-06-07 21:37:28.978,200,19,6
2235537,2235537,2235537,1,11,-7.605712,-2.690709,-5.798734,NaN,NaN,NaN,312,2016-06-07 21:37:28.989,200,19,6
2235538,2235538,2235538,1,11,-7.574578,-2.674542,-5.820289,NaN,NaN,NaN,312,2016-06-07 21:37:28.992,200,19,6
2235539,2235539,2235539,1,11,-7.578170,-2.649396,-5.786161,NaN,NaN,NaN,312,2016-06-07 21:37:28.992,200,19,6
2235540,2235540,2235540,1,11,-7.594336,-2.667956,-5.772988,NaN,NaN,NaN,312,2016-06-07 21:37:29.033,200,19,6

In [ ]:
dataset1_part2

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,1,1,7.079678,1.202300,7.405400,-0.765625,-0.617188,-2.453125,204,2017-04-14 23:38:23.123,20,1,1
1,1,1,7.079678,1.202300,7.405400,-0.765625,-0.617188,-2.453125,204,2017-04-14 23:38:23.130,20,1,1
2,1,1,6.828201,1.152004,7.405400,-3.125000,0.054688,-2.234375,204,2017-04-14 23:38:23.156,20,1,1
3,1,1,7.079678,1.235830,7.553892,-2.414062,0.187500,-2.867188,204,2017-04-14 23:38:23.189,20,1,1
4,1,1,6.969507,1.163979,7.285649,-2.648438,-2.023438,-2.929688,204,2017-04-14 23:38:23.238,20,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
817566,1,11,2.172283,-0.744851,-9.163345,-0.648438,0.242188,-2.531250,213,2016-06-07 21:37:28.596,20,19,6
817567,1,11,2.181863,-0.797542,-9.402847,-0.414062,0.414062,-2.062500,213,2016-06-07 21:37:28.679,20,19,6
817568,1,11,2.148333,-0.814307,-9.180110,0.750000,0.554688,-2.539062,213,2016-06-07 21:37:28.759,20,19,6
817569,1,11,1.990261,-0.843047,-9.350156,0.664062,0.515625,-2.328125,213,2016-06-07 21:37:28.835,20,19,6
817570,1,11,2.150728,-0.799937,-9.366921,-0.984375,-2.039062,-2.710938,213,2016-06-07 21:37:28.969,20,19,6

En un principio el codigo se planteo como 012, esto es un problema pues python lee esto como 12, para esto simplemente se cambio el 0 por un 3

In [ ]:
df = dataset1_part
df['Code'] = df['Code'].replace(12, 312)
df.to_csv(ruta)
dataset1_part = pd.read_csv(ruta)
dataset1_part

,Unnamed: 0.1,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,0,1,1,-1.361134,8.700216,3.247392,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
1,1,1,1,1,-1.355151,8.696629,3.260564,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
2,2,2,1,1,-1.322823,8.726561,3.248583,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
3,3,3,1,1,-1.375512,8.697820,3.273737,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
4,4,4,1,1,-1.364736,8.694233,3.282116,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235536,2235536,2235536,1,11,-7.588349,-2.675740,-5.789155,NaN,NaN,NaN,312,2016-06-07 21:37:28.978,200,19,6
2235537,2235537,2235537,1,11,-7.605712,-2.690709,-5.798734,NaN,NaN,NaN,312,2016-06-07 21:37:28.989,200,19,6
2235538,2235538,2235538,1,11,-7.574578,-2.674542,-5.820289,NaN,NaN,NaN,312,2016-06-07 21:37:28.992,200,19,6
2235539,2235539,2235539,1,11,-7.578170,-2.649396,-5.786161,NaN,NaN,NaN,312,2016-06-07 21:37:28.992,200,19,6
2235540,2235540,2235540,1,11,-7.594336,-2.667956,-5.772988,NaN,NaN,NaN,312,2016-06-07 21:37:29.033,200,19,6

##**Actividades**

### Actividades Dataset 1 Parte 1

In [ ]:
df["Activity"].unique()

1
2
3
4
5
6
7
9
10
11
14
13

Realizamos el mapeo de actividades en base a lo concretado por los autores de acuerdo al id de actividades

In [ ]:
activity_mapping = {
    "Aplausing": 1,
    "HandsUp": 2,
    "MakingACall": 3,
    "OpeningDoor": 4,
    "Sitting_GettingUpOnAChair": 5,
    "Walking": 6,
    "Bending": 7,
    "Hopping": 9,
    "Jogging": 10,
    "LyingDown_OnABed": 11,
    "backwardFall": 11,
    "forwardFall": 11,
    "lateralFall": 11,
    "GoDownstairs": 14,
    "GoUpstairs": 13
}

file_path = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_1.csv'

df = pd.read_csv(file_path)

df['Activity'] = df['Activity'].map(activity_mapping)

df.to_csv(file_path, index=False)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_1.csv')
df

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,1,1,-1.361134,8.700216,3.247392,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
1,1,1,1,-1.355151,8.696629,3.260564,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
2,2,1,1,-1.322823,8.726561,3.248583,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
3,3,1,1,-1.375512,8.697820,3.273737,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
4,4,1,1,-1.364736,8.694233,3.282116,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,200,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235536,2235536,1,11,-7.588349,-2.675740,-5.789155,NaN,NaN,NaN,312,2016-06-07 21:37:28.978,200,19,6
2235537,2235537,1,11,-7.605712,-2.690709,-5.798734,NaN,NaN,NaN,312,2016-06-07 21:37:28.989,200,19,6
2235538,2235538,1,11,-7.574578,-2.674542,-5.820289,NaN,NaN,NaN,312,2016-06-07 21:37:28.992,200,19,6
2235539,2235539,1,11,-7.578170,-2.649396,-5.786161,NaN,NaN,NaN,312,2016-06-07 21:37:28.992,200,19,6
2235540,2235540,1,11,-7.594336,-2.667956,-5.772988,NaN,NaN,NaN,312,2016-06-07 21:37:29.033,200,19,6

### Actividades Dataset 1 Parte 2

In [ ]:
dataset1_part2["Activity"].unique()

Aplausing
HandsUp
MakingACall
OpeningDoor
Sitting_GettingUpOnAChair
Walking
Bending
Hopping
Jogging
LyingDown_OnABed
backwardFall
forwardFall
lateralFall
GoDownstairs
GoUpstairs

In [ ]:
activity_mapping = {
    "Aplausing": 1,
    "HandsUp": 2,
    "MakingACall": 3,
    "OpeningDoor": 4,
    "Sitting_GettingUpOnAChair": 5,
    "Walking": 6,
    "Bending": 7,
    "Hopping": 9,
    "Jogging": 10,
    "LyingDown_OnABed": 11,
    "backwardFall": 11,
    "forwardFall": 11,
    "lateralFall": 11,
    "GoDownstairs": 14,
    "GoUpstairs": 13
}

file_path = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv'


df = pd.read_csv(file_path)

df['Activity'] = df['Activity'].map(activity_mapping)

df.to_csv(file_path, index=False)

##Resampling

In [ ]:
ruta = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_1.csv'
ruta2 = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv'
dataset1_part = pd.read_csv(ruta)
dataset1_part2 = pd.read_csv(ruta2)

### Resampling Dataset 1 Parte 1

In [ ]:
resample1 = resample_dataframe(dataset1_part)

In [ ]:
resample1

,Unnamed: 0.1,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
2,2,2,1,1,-1.322823,8.726561,3.248583,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,50,1,1
5,5,5,1,1,-1.359944,8.702612,3.283307,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,50,1,1
8,8,8,1,1,-1.382701,8.732544,3.337202,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,50,1,1
9,9,9,1,1,-1.391081,8.722974,3.353961,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,50,1,1
11,11,11,1,1,-1.407840,8.712198,3.357548,NaN,NaN,NaN,312,2017-04-14 23:38:23.103,50,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235530,2235530,2235530,1,11,-7.591342,-2.644007,-5.792747,NaN,NaN,NaN,312,2016-06-07 21:37:28.953,50,19,6
2235532,2235532,2235532,1,11,-7.609903,-2.660772,-5.763409,NaN,NaN,NaN,312,2016-06-07 21:37:28.965,50,19,6
2235535,2235535,2235535,1,11,-7.573979,-2.651192,-5.791549,NaN,NaN,NaN,312,2016-06-07 21:37:28.977,50,19,6
2235538,2235538,2235538,1,11,-7.574578,-2.674542,-5.820289,NaN,NaN,NaN,312,2016-06-07 21:37:28.992,50,19,6
2235540,2235540,2235540,1,11,-7.594336,-2.667956,-5.772988,NaN,NaN,NaN,312,2016-06-07 21:37:29.033,50,19,6

In [ ]:
resample1 = resample1.drop(['Unnamed: 0.1','Unnamed: 0'], axis=1)
resample1

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
2,1,1,-1.322823,8.726561,3.248583,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,50,1,1
5,1,1,-1.359944,8.702612,3.283307,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,50,1,1
8,1,1,-1.382701,8.732544,3.337202,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,50,1,1
9,1,1,-1.391081,8.722974,3.353961,NaN,NaN,NaN,312,2017-04-14 23:38:23.102,50,1,1
11,1,1,-1.407840,8.712198,3.357548,NaN,NaN,NaN,312,2017-04-14 23:38:23.103,50,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235530,1,11,-7.591342,-2.644007,-5.792747,NaN,NaN,NaN,312,2016-06-07 21:37:28.953,50,19,6
2235532,1,11,-7.609903,-2.660772,-5.763409,NaN,NaN,NaN,312,2016-06-07 21:37:28.965,50,19,6
2235535,1,11,-7.573979,-2.651192,-5.791549,NaN,NaN,NaN,312,2016-06-07 21:37:28.977,50,19,6
2235538,1,11,-7.574578,-2.674542,-5.820289,NaN,NaN,NaN,312,2016-06-07 21:37:28.992,50,19,6
2235540,1,11,-7.594336,-2.667956,-5.772988,NaN,NaN,NaN,312,2016-06-07 21:37:29.033,50,19,6

In [ ]:
resample1.to_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset1_part1.csv',index=False)

### Resampling Dataset 1 Parte 2

In [ ]:
x = resample_dataframe(dataset1_part2)
x

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,1,1,7.08,1.20,7.41,-0.77,-0.62,-2.45,204,2017-04-14 23:38:23.123,50,1,1
1,1,1,7.08,1.20,7.41,-0.77,-0.62,-2.45,204,2017-04-14 23:38:23.123,50,1,1
2,1,1,7.08,1.20,7.41,-0.77,-0.62,-2.45,204,2017-04-14 23:38:23.123,50,1,1
3,1,1,7.08,1.20,7.41,-0.77,-0.62,-2.45,204,2017-04-14 23:38:23.130,50,1,1
4,1,1,7.08,1.20,7.41,-0.77,-0.62,-2.45,204,2017-04-14 23:38:23.130,50,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2043918,1,11,1.99,-0.84,-9.35,0.66,0.52,-2.33,213,2016-06-07 21:37:28.835,50,19,6
2043919,1,11,1.99,-0.84,-9.35,0.66,0.52,-2.33,213,2016-06-07 21:37:28.835,50,19,6
2043920,1,11,1.99,-0.84,-9.35,0.66,0.52,-2.33,213,2016-06-07 21:37:28.835,50,19,6
2043921,1,11,2.15,-0.80,-9.37,-0.98,-2.04,-2.71,213,2016-06-07 21:37:28.969,50,19,6
2043922,1,11,2.15,-0.80,-9.37,-0.98,-2.04,-2.71,213,2016-06-07 21:37:28.969,50,19,6

In [ ]:
pd.set_option('display.float_format', '{:.2f}'.format)
resampled_data.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,2043923.00,2043923.00,2043923.00,2043923.00,2043923.00,2043923.00,2043923.00,2043923.00,2043923.00,2043923.00,2043923.00,2043923.00
mean,1.00,7.55,5.67,-0.11,1.51,-1.93,-0.42,-0.86,211.60,50.00,11.06,2.88
std,0.00,3.70,55.58,22.58,18.27,58.76,58.08,50.27,6.55,0.00,6.05,2.36
min,1.00,1.00,-4276.07,-4303.37,-2834.27,-998.98,-999.92,-996.88,204.00,50.00,1.00,1.00
25%,1.00,4.00,0.07,-1.49,-0.96,-5.95,-4.14,-3.13,204.00,50.00,5.00,1.00
50%,1.00,9.00,7.73,-0.25,1.28,-1.81,-0.13,-1.01,213.00,50.00,11.00,2.00
75%,1.00,11.00,9.64,1.16,4.11,2.15,2.79,0.98,221.00,50.00,18.00,3.00
max,1.00,14.00,5408.43,5404.60,3567.14,998.20,998.12,998.52,221.00,50.00,19.00,18.00

In [ ]:
resampled_data.to_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset1_part2.csv',index=False)

## Análisis Gráfico del dataset1_part1

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset1_part1.csv', index_col=0)

In [ ]:
df

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,175598,1,11,-2.526270,9.140887,0.360294,NaN,NaN,NaN,312,2016-06-13 20:53:39.843,50,2,4
1,1221407,1,5,-0.833437,9.325275,3.347519,NaN,NaN,NaN,312,2016-06-06 16:48:12.998,50,13,3
2,1622336,1,13,-1.192677,13.530779,-2.290156,NaN,NaN,NaN,312,2016-06-06 15:34:54.373,50,18,3
3,1698560,1,9,0.635256,9.751572,0.102982,NaN,NaN,NaN,312,2016-06-02 00:14:50.188,50,18,7
4,150573,1,11,-3.321389,-1.272285,-9.332001,NaN,NaN,NaN,312,2016-06-13 20:52:25.749,50,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558880,1413514,1,11,-4.735609,-1.589613,-8.702139,NaN,NaN,NaN,312,2016-06-17 18:46:14.243,50,15,4
558881,988298,1,10,-0.700135,3.406224,0.117208,NaN,NaN,NaN,312,2016-06-10 17:45:56.244,50,11,3
558882,1572969,1,7,0.627473,9.890479,0.966955,NaN,NaN,NaN,312,2016-05-31 18:24:16.818,50,18,5
558883,935803,1,9,0.105377,-0.584963,1.781232,NaN,NaN,NaN,312,2016-06-06 15:46:03.331,50,10,3
558884,1113030,1,2,-2.394562,-9.871305,1.551775,NaN,NaN,NaN,312,2017-03-27 22:44:10.970,50,12,2

### Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(df)

### Valores Máximos y Mínimos del Acelerometro

In [ ]:
grafico_acelerometro_max_min(df)

## Análisis Gráfico Dataset1_part2

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset1_part2.csv', index_col=0)
df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,1,1,7.079678,1.202300,7.405400,-0.765625,-0.617188,-2.453125,204,2017-04-14 23:38:23.123,50,1,1
1,1,1,7.079678,1.202300,7.405400,-0.765625,-0.617188,-2.453125,204,2017-04-14 23:38:23.130,50,1,1
2,1,1,6.828201,1.152004,7.405400,-3.125000,0.054688,-2.234375,204,2017-04-14 23:38:23.156,50,1,1
3,1,1,7.079678,1.235830,7.553892,-2.414062,0.187500,-2.867188,204,2017-04-14 23:38:23.189,50,1,1
4,1,1,6.969507,1.163979,7.285649,-2.648438,-2.023438,-2.929688,204,2017-04-14 23:38:23.238,50,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2043922,1,11,3.688330,-9.105864,3.118315,-3.484375,-0.812500,0.109375,221,2016-06-03 20:04:49.690,50,14,1
2043923,1,11,-3.218906,1.659749,-8.669971,-2.882812,-0.460938,0.078125,208,2016-05-29 21:52:49.380,50,18,4
2043924,1,11,-8.327483,-4.955295,1.235830,-20.195312,-23.039062,-35.289062,221,2016-06-13 21:54:27.692,50,6,6
2043925,1,11,9.036409,-1.448987,-3.089575,-3.000000,2.015625,0.210938,208,2016-05-29 21:56:26.187,50,18,4
2043926,1,11,9.608818,-0.586780,-0.814307,-2.812500,4.054688,0.437500,208,2016-06-01 22:37:44.936,50,18,8

### Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(df)

### Valores Máximos y Mínimos del Acelerometro

In [ ]:
grafico_acelerometro_max_min(df)

### Valores Válidos Giroscopio

In [ ]:
grafico_giroscopio_valido(df)

### Valores Máximos y Mínimos Giroscopio

In [ ]:
grafico_giroscopio_max_min(df)

### Actividades Válidas

In [ ]:
grafico_activity(df)

In [ ]:
import pandas as pd
import json

resultado = dataset1_part1.describe()
# Convertir el resultado en un diccionario
resultado_diccionario = resultado.to_dict()

# Convertir el diccionario en una cadena JSON
json_string = json.dumps(resultado_diccionario)

# Guardar la cadena JSON en un archivo .json
ruta_json = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_1_describe.json'
with open(ruta_json, 'w') as archivo:
    archivo.write(json_string)

NameError: ignored

In [ ]:
import pandas as pd
import json

resultado2 = dataset1_part2.describe()
# Convertir el resultado en un diccionario
resultado_diccionario2 = resultado2.to_dict()

# Convertir el diccionario en una cadena JSON
json_string2 = json.dumps(resultado_diccionario2)

# Guardar la cadena JSON en un archivo .json
ruta_json2 = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2_describe.json'
with open(ruta_json2, 'w') as archivo:
    archivo.write(json_string2)

## Describe del Dataset 1

### Describe Antes Del Resampling

In [ ]:
ruta_antes = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_1.csv'
ruta2_antes = '/content/drive/MyDrive/TESIS_DATASET/1_UMAFall_Dataset/DATASETS_FINALES/Dataset_1_part_2.csv'
dataset1_part1_antes = pd.read_csv(ruta_antes, index_col=0)
dataset1_part2_antes = pd.read_csv(ruta2_antes, index_col=0)

In [ ]:
dataset1_part2.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,817571.00,817571.00,817571.00,817571.00,817571.00,817571.00,817571.00,817571.00,817571.00,817571.00,817571.00,817571.00
mean,1.00,7.55,5.67,-0.10,1.51,-1.91,-0.40,-0.89,211.60,20.00,11.06,2.88
std,0.00,3.70,55.83,22.21,18.19,58.74,58.08,50.24,6.55,0.00,6.05,2.35
min,1.00,1.00,-4276.07,-4303.37,-2834.27,-998.98,-999.92,-996.88,204.00,20.00,1.00,1.00
25%,1.00,4.00,0.07,-1.49,-0.96,-5.93,-4.13,-3.13,204.00,20.00,5.00,1.00
50%,1.00,9.00,7.73,-0.25,1.28,-1.81,-0.13,-1.01,213.00,20.00,11.00,2.00
75%,1.00,11.00,9.64,1.16,4.11,2.14,2.79,0.98,221.00,20.00,18.00,3.00
max,1.00,14.00,5408.43,5404.60,3567.14,998.20,998.12,998.52,221.00,20.00,19.00,18.00

In [ ]:
dataset1_part2_antes.describe()

,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,817571.000000,817571.000000,817571.000000,817571.000000,817571.000000,817571.000000,817571.000000,817571.000000,817571.0,817571.000000,817571.000000
mean,7.552767,5.668471,-0.103334,1.510048,-1.905549,-0.401671,-0.887908,211.599193,20.0,11.061787,2.883110
std,3.698808,55.827047,22.209243,18.190607,58.739521,58.081533,50.239775,6.549964,0.0,6.050135,2.353341
min,1.000000,-4276.067871,-4303.371094,-2834.266113,-998.984375,-999.921875,-996.875000,204.000000,20.0,1.000000,1.000000
25%,4.000000,0.071851,-1.494492,-0.955613,-5.929688,-4.132812,-3.132812,204.000000,20.0,5.000000,1.000000
50%,9.000000,7.726333,-0.251477,1.281335,-1.812500,-0.132812,-1.007812,213.000000,20.0,11.000000,2.000000
75%,11.000000,9.637559,1.156794,4.109854,2.140625,2.789062,0.976562,221.000000,20.0,18.000000,3.000000
max,14.000000,5408.433105,5404.601074,3567.142090,998.203125,998.125000,998.515625,221.000000,20.0,19.000000,18.000000

### Describe Después del Resampling

In [ ]:
ruta = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset1_part1.csv'
ruta2 = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset1_part2.csv'
dataset1_part1 = pd.read_csv(ruta, index_col=0)
dataset1_part2 = pd.read_csv(ruta2, index_col=0)

In [ ]:
dataset1_part1.describe()

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,5.588850e+05,558885.0,558885.000000,558885.000000,5.588850e+05,5.588850e+05,0.0,0.0,0.0,558885.0,558885.0,558885.000000,558885.000000
mean,1.117819e+06,1.0,7.739225,-0.398868,-1.070719e+06,-8.565769e+06,NaN,NaN,NaN,312.0,50.0,11.466608,2.998858
std,6.449945e+05,0.0,3.666315,6.488947,8.004563e+08,2.264018e+09,NaN,NaN,NaN,0.0,0.0,6.010654,2.531245
min,1.000000e+00,1.0,1.000000,-1092.568851,-5.984100e+11,-5.984100e+11,NaN,NaN,NaN,312.0,50.0,1.000000,1.000000
25%,5.590010e+05,1.0,5.000000,-2.495148,-2.620657e+00,-1.399240e+00,NaN,NaN,NaN,312.0,50.0,6.000000,1.000000
50%,1.118319e+06,1.0,9.000000,-0.474197,2.757766e+00,3.203224e-01,NaN,NaN,NaN,312.0,50.0,12.000000,2.000000
75%,1.675422e+06,1.0,11.000000,1.551917,9.243870e+00,1.608797e+00,NaN,NaN,NaN,312.0,50.0,18.000000,3.000000
max,2.235535e+06,1.0,14.000000,1821.107831,1.822006e+03,1.388044e+03,NaN,NaN,NaN,312.0,50.0,19.000000,18.000000

In [ ]:
dataset1_part2.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,2043927.0,2.043927e+06,2.043927e+06,2.043927e+06,2.043927e+06,2.043927e+06,2.043927e+06,2.043927e+06,2.043927e+06,2043927.0,2.043927e+06,2.043927e+06
mean,1.0,7.548863e+00,5.606995e+00,-1.129739e-01,1.493192e+00,-1.956546e+00,-4.008926e-01,-8.688933e-01,2.116004e+02,50.0,1.105977e+01,2.883557e+00
std,0.0,3.698642e+00,5.538391e+01,2.214383e+01,1.797261e+01,5.858364e+01,5.815378e+01,5.006430e+01,6.551930e+00,0.0,6.052420e+00,2.352806e+00
min,1.0,1.000000e+00,-4.276068e+03,-4.303371e+03,-2.834266e+03,-9.989844e+02,-9.999219e+02,-9.968750e+02,2.040000e+02,50.0,1.000000e+00,1.000000e+00
25%,1.0,4.000000e+00,8.143066e-02,-1.496887e+00,-9.604028e-01,-5.976562e+00,-4.140625e+00,-3.125000e+00,2.040000e+02,50.0,5.000000e+00,1.000000e+00
50%,1.0,9.000000e+00,7.738308e+00,-2.538721e-01,1.278940e+00,-1.820312e+00,-1.328125e-01,-1.007812e+00,2.130000e+02,50.0,1.100000e+01,2.000000e+00
75%,1.0,1.100000e+01,9.637559e+00,1.159189e+00,4.105063e+00,2.125000e+00,2.789062e+00,9.843750e-01,2.210000e+02,50.0,1.800000e+01,3.000000e+00
max,1.0,1.400000e+01,5.408433e+03,5.404601e+03,3.567142e+03,9.982031e+02,9.981250e+02,9.985156e+02,2.210000e+02,50.0,1.900000e+01,1.800000e+01

# Dataset Número 2. A Public Domain

## Preparación del Dataset Número 2

Debido a que en el dataset 2 cada usuario podia usar su frecuencia propia de celular sin realizar ninguna modificación se presentan inconvenientes y es que para trabajar con un dataset sin conocer la frecuencia es casi que imposible, por esto se propone leer las filas que hay en cada segundo para cada acticvidad de cada usuario.

In [ ]:
acc = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/sensoringData_acc.csv')

In [ ]:
acch = acc.copy()

acch['timestamp'] = pd.to_datetime(acch['timestamp'], unit='s')

In [ ]:
acc

,id,username,timestamp,acc_x_axis,acc_y_axis,acc_z_axis,activity_id,activity
0,4006559,11,1.570534e+09,-0.388868,3.812294,6.222649,-499,Walking
1,4006561,11,1.570534e+09,-0.242817,3.838631,6.059839,-499,Walking
2,4006562,11,1.570534e+09,-0.259577,3.946373,6.023924,-499,Walking
3,4006563,11,1.570534e+09,-0.048881,3.807506,6.090964,-499,Walking
4,4006564,11,1.570534e+09,0.295895,3.795534,6.040684,-499,Walking
...,...,...,...,...,...,...,...,...
17378629,39691767,2,1.576784e+09,0.234983,0.153715,-0.208087,41,Driving
17378630,39691770,2,1.576784e+09,0.143519,0.216550,-0.204246,41,Driving
17378631,39691773,2,1.576784e+09,0.110278,0.207618,-0.285629,41,Driving
17378632,39691776,2,1.576784e+09,0.111215,0.097924,-0.070788,41,Driving
17378633,39691779,2,1.576784e+09,0.030945,-0.048773,0.089122,41,Driving

El proceso que se realiza a continuación consiste en calcular la frecuencia de cada usuario, una vez calculadas las frecuencias estas serán asignadas al acc. Este proceso se realizará para el archivo del giroscopio.

Se seleccionan unicamente las columnas necesarias para que el proceso se realice más rápido

In [ ]:
columnas_deseadas = ['username','timestamp','activity']
acchc = acch[columnas_deseadas]

In [ ]:
acchc

          username                     timestamp activity
0               11 2019-10-08 11:21:49.356000000  Walking
1               11 2019-10-08 11:21:52.540999936  Walking
2               11 2019-10-08 11:21:52.562000128  Walking
3               11 2019-10-08 11:21:52.583000064  Walking
4               11 2019-10-08 11:21:52.602999808  Walking
...            ...                           ...      ...
17378629         2 2019-12-19 19:33:53.099000064  Driving
17378630         2 2019-12-19 19:33:53.299000064  Driving
17378631         2 2019-12-19 19:33:53.500000000  Driving
17378632         2 2019-12-19 19:33:53.700000000  Driving
17378633         2 2019-12-19 19:33:53.898999808  Driving

[17378634 rows x 3 columns]

In [ ]:
# Crear una nueva columna 'second' que contenga únicamente el valor de los segundos de cada registro
acch['second'] = acch['timestamp'].dt.second

In [ ]:
# Agrupar los datos por usuario y actividad
grouped_data = acchc.groupby(['username', 'activity'])

# Calcular la frecuencia para cada grupo
result = []
for group_name, group_data in grouped_data:
    username, activity = group_name
    freq = group_data.resample('S', on='timestamp').size()
    freq_nonzero = freq[freq != 0]
    freq_mean = np.mean(freq_nonzero)
    freq_median = np.median(freq_nonzero) if len(freq_nonzero) > 0 else None
    freq_mode = freq_nonzero.mode().values[0] if len(freq_nonzero) > 0 else None
    result.append((username, activity, freq, freq_mean, freq_median, freq_mode))

for username, activity, freq, freq_mean, freq_median, freq_mode in result:
    print(f"La frecuencia para la actividad {activity} en el username {username} es:")
    print(freq.head(40))
    print("...")
    print(freq.tail(40))
    print(f"La frecuencia media para la actividad {activity} en el username {username} es: {freq_mean}")
    print(f"La frecuencia mediana para la actividad {activity} en el username {username} es: {freq_median}")
    print(f"La frecuencia moda para la actividad {activity} en el username {username} es: {freq_mode}")
    print()

La frecuencia para la actividad Driving en el username 0 es:
timestamp
2019-10-10 04:57:40    17
2019-10-10 04:57:41    49
2019-10-10 04:57:42    51
2019-10-10 04:57:43    51
2019-10-10 04:57:44    51
2019-10-10 04:57:45    50
2019-10-10 04:57:46    51
2019-10-10 04:57:47    51
2019-10-10 04:57:48    50
2019-10-10 04:57:49    51
2019-10-10 04:57:50    51
2019-10-10 04:57:51    51
2019-10-10 04:57:52    50
2019-10-10 04:57:53    51
2019-10-10 04:57:54    51
2019-10-10 04:57:55    51
2019-10-10 04:57:56    50
2019-10-10 04:57:57    51
2019-10-10 04:57:58    51
2019-10-10 04:57:59    51
2019-10-10 04:58:00    50
2019-10-10 04:58:01    51
2019-10-10 04:58:02    51
2019-10-10 04:58:03    51
2019-10-10 04:58:04    50
2019-10-10 04:58:05    51
2019-10-10 04:58:06    51
2019-10-10 04:58:07    51
2019-10-10 04:58:08    50
2019-10-10 04:58:09    51
2019-10-10 04:58:10    51
2019-10-10 04:58:11    51
2019-10-10 04:58:12    50
2019-10-10 04:58:13    51
2019-10-10 04:58:14    51
2019-10-10 04:58:15    50
2019-10-10 04:58:16    51
2019-10-10 04:58:17    51
2019-10-10 04:58:18    51
2019-10-10 04:58:19    50
Freq: S, dtype: int64
...
timestamp
2019-10-10 05:17:01    51
2019-10-10 05:17:02    50
2019-10-10 05:17:03    49
2019-10-10 05:17:04    50
2019-10-10 05:17:05    51
2019-10-10 05:17:06    51
2019-10-10 05:17:07    51
2019-10-10 05:17:08    50
2019-10-10 05:17:09    51
2019-10-10 05:17:10    50
2019-10-10 05:17:11    51
2019-10-10 05:17:12    50
2019-10-10 05:17:13    51
2019-10-10 05:17:14    51
2019-10-10 05:17:15    51
2019-10-10 05:17:16    50
2019-10-10 05:17:17    48
2019-10-10 05:17:18    50
2019-10-10 05:17:19    51
2019-10-10 05:17:20    50
2019-10-10 05:17:21    51
2019-10-10 05:17:22    51
2019-10-10 05:17:23    50
2019-10-10 05:17:24    51
2019-10-10 05:17:25    50
2019-10-10 05:17:26    51
2019-10-10 05:17:27    51
2019-10-10 05:17:28    51
2019-10-10 05:17:29    50
2019-10-10 05:17:30    50
2019-10-10 05:17:31    50
2019-10-10 05:17:32    51
2019-10-10 05:17:33    51
2019-10-10 05:17:34    51
2019-10-10 05:17:35    50
2019-10-10 05:17:36    51
2019-10-10 05:17:37    50
2019-10-10 05:17:38    51
2019-10-10 05:17:39    50
2019-10-10 05:17:40    36
Freq: S, dtype: int64
La frecuencia media para la actividad Driving en el username 0 es: 54.716902581182346
La frecuencia mediana para la actividad Driving en el username 0 es: 51.0
La frecuencia moda para la actividad Driving en el username 0 es: 51

La frecuencia para la actividad Inactive en el username 0 es:
timestamp
2019-10-09 13:32:58    3
2019-10-09 13:32:59    5
2019-10-09 13:33:00    5
2019-10-09 13:33:01    6
2019-10-09 13:33:02    5
2019-10-09 13:33:03    5
2019-10-09 13:33:04    5
2019-10-09 13:33:05    5
2019-10-09 13:33:06    5
2019-10-09 13:33:07    5
2019-10-09 13:33:08    5
2019-10-09 13:33:09    5
2019-10-09 13:33:10    5
2019-10-09 13:33:11    5
2019-10-09 13:33:12    5
2019-10-09 13:33:13    5
2019-10-09 13:33:14    5
2019-10-09 13:33:15    6
2019-10-09 13:33:16    5
2019-10-09 13:33:17    5
2019-10-09 13:33:18    5
2019-10-09 13:33:19    5
2019-10-09 13:33:20    5
2019-10-09 13:33:21    5
2019-10-09 13:33:22    5
2019-10-09 13:33:23    5
2019-10-09 13:33:24    5
2019-10-09 13:33:25    5
2019-10-09 13:33:26    5
2019-10-09 13:33:27    5
2019-10-09 13:33:28    6
2019-10-09 13:33:29    5
2019-10-09 13:33:30    5
2019-10-09 13:33:31    5
2019-10-09 13:33:32    5
2019-10-09 13:33:33    5
2019-10-09 13:33:34    5
2019-10-09 13:33:35    5
2019-10-09 13:33:36    5
2019-10-09 13:33:37    5
Freq: S, dtype: int64
...
timestamp
2019-12-10 15:37:56    5
2019-12-10 15:37:57    5
2019-12-10 15:37:58    5
2019-12-10 15:37:59    5
2019-12-10 15:38:00    5
2019-12-10 15:38:01    5
2019-12-10 15:38:02    6
2019-12-10 15:38:03    5
2019-12-10 15:38:04    5
2019-12-10 15:38:05    5
2019-12-10 15:38:06    5
2019-12-10 15:38:07    5
2019-12-10 15:38:08    5
2019-12-10 15:38:09    5
2019-12-10 15:38:10    5
2019-12-10 15:38:11    5
2019-12-10 15:38:12    5
2019-12-10 15:38:13    5
2019-12-10 15:38:14    5
2019-12-10 15:38:15    6
2019-12-10 15:38:16    5
2019-12-10 15:38:17    5
2019-12-10 15:38:18    5
2019-12-10 15:38:19    5
2019-12-10 15:38:20    5
2019-12-10 15:38:21    5
2019-12-10 15:38:22    5
2019-12-10 15:38:23    5
2019-12-10 15:38:24    5
2019-12-10 15:38:25    5
2019-12-10 15:38:26    5
2019-12-10 15:38:27    5
2019-12-10 15:38:28    6
2019-12-10 15:38:29    5
2019-12-10 15:38:30    5
2019-12-10 15:38:31    5
2019-12-10 15:38:32    5
2019-12-10 15:38:33    5
2019-12-10 15:38:34    5
2019-12-10 15:38:35    4
Freq: S, dtype: int64
La frecuencia media para la actividad Inactive en el username 0 es: 6.049019607843137
La frecuencia mediana para la actividad Inactive en el username 0 es: 5.0
La frecuencia moda para la actividad Inactive en el username 0 es: 5

La frecuencia para la actividad Driving en el username 1 es:
timestamp
2019-10-17 03:00:44    46
2019-10-17 03:00:45    50
2019-10-17 03:00:46    50
2019-10-17 03:00:47    50
2019-10-17 03:00:48    51
2019-10-17 03:00:49    50
2019-10-17 03:00:50    50
2019-10-17 03:00:51    50
2019-10-17 03:00:52    51
2019-10-17 03:00:53    50
2019-10-17 03:00:54    50
2019-10-17 03:00:55    51
2019-10-17 03:00:56    50
2019-10-17 03:00:57    50
2019-10-17 03:00:58    50
2019-10-17 03:00:59    51
2019-10-17 03:01:00    50
2019-10-17 03:01:01    50
2019-10-17 03:01:02    51
2019-10-17 03:01:03    50
2019-10-17 03:01:04    50
2019-10-17 03:01:05    45
2019-10-17 03:01:06     5
2019-10-17 03:01:07     5
2019-10-17 03:01:08     5
2019-10-17 03:01:09     5
2019-10-17 03:01:10     5
2019-10-17 03:01:11     5
2019-10-17 03:01:12     5
2019-10-17 03:01:13     5
2019-10-17 03:01:14     5
2019-10-17 03:01:15     5
2019-10-17 03:01:16     5
2019-10-17 03:01:17     5
2019-10-17 03:01:18     5
2019-10-17 03:01:19     5
2019-10-17 03:01:20     5
2019-10-17 03:01:21     5
2019-10-17 03:01:22     5
2019-10-17 03:01:23     5
Freq: S, dtype: int64
...
timestamp
2019-10-28 09:17:19    46
2019-10-28 09:17:20    50
2019-10-28 09:17:21    50
2019-10-28 09:17:22    28
2019-10-28 09:17:23     5
2019-10-28 09:17:24     5
2019-10-28 09:17:25     5
2019-10-28 09:17:26     5
2019-10-28 09:17:27    19
2019-10-28 09:17:28    50
2019-10-28 09:17:29    50
2019-10-28 09:17:30    50
2019-10-28 09:17:31    10
2019-10-28 09:17:32     5
2019-10-28 09:17:33     5
2019-10-28 09:17:34     5
2019-10-28 09:17:35     5
2019-10-28 09:17:36     5
2019-10-28 09:17:37     5
2019-10-28 09:17:38     5
2019-10-28 09:17:39     6
2019-10-28 09:17:40     5
2019-10-28 09:17:41     5
2019-10-28 09:17:42     5
2019-10-28 09:17:43     5
2019-10-28 09:17:44     5
2019-10-28 09:17:45     5
2019-10-28 09:17:46     5
2019-10-28 09:17:47     6
2019-10-28 09:17:48    50
2019-10-28 09:17:49    50
2019-10-28 09:17:50    51
2019-10-28 09:17:51    28
2019-10-28 09:17:52    15
2019-10-28 09:17:53    50
2019-10-28 09:17:54    50
2019-10-28 09:17:55    51
2019-10-28 09:17:56    29
2019-10-28 09:17:57    15
2019-10-28 09:17:58    13
Freq: S, dtype: int64
La frecuencia media para la actividad Driving en el username 1 es: 9.614341776667857
La frecuencia mediana para la actividad Driving en el username 1 es: 5.0
La frecuencia moda para la actividad Driving en el username 1 es: 5

La frecuencia para la actividad Inactive en el username 1 es:
timestamp
2019-10-16 23:24:56     1
2019-10-16 23:24:57    50
2019-10-16 23:24:58    50
2019-10-16 23:24:59    50
2019-10-16 23:25:00    50
2019-10-16 23:25:01    50
2019-10-16 23:25:02    50
2019-10-16 23:25:03    50
2019-10-16 23:25:04    51
2019-10-16 23:25:05    50
2019-10-16 23:25:06    50
2019-10-16 23:25:07    51
2019-10-16 23:25:08    50
2019-10-16 23:25:09    50
2019-10-16 23:25:10    50
2019-10-16 23:25:11    51
2019-10-16 23:25:12    50
2019-10-16 23:25:13    50
2019-10-16 23:25:14    50
2019-10-16 23:25:15    51
2019-10-16 23:25:16    50
2019-10-16 23:25:17    50
2019-10-16 23:25:18    50
2019-10-16 23:25:19    50
2019-10-16 23:25:20     6
2019-10-16 23:25:21     5
2019-10-16 23:25:22     5
2019-10-16 23:25:23     5
2019-10-16 23:25:24     5
2019-10-16 23:25:25     5
2019-10-16 23:25:26     5
2019-10-16 23:25:27     6
2019-10-16 23:25:28     5
2019-10-16 23:25:29     5
2019-10-16 23:25:30     5
2019-10-16 23:25:31     5
2019-10-16 23:25:32     5
2019-10-16 23:25:33     5
2019-10-16 23:25:34     5
2019-10-16 23:25:35     5
Freq: S, dtype: int64
...
timestamp
2019-10-17 03:27:56     0
2019-10-17 03:27:57     0
2019-10-17 03:27:58     0
2019-10-17 03:27:59     0
2019-10-17 03:28:00     0
2019-10-17 03:28:01     0
2019-10-17 03:28:02     0
2019-10-17 03:28:03     0
2019-10-17 03:28:04     0
2019-10-17 03:28:05     0
2019-10-17 03:28:06     0
2019-10-17 03:28:07     0
2019-10-17 03:28:08     0
2019-10-17 03:28:09     0
2019-10-17 03:28:10     0
2019-10-17 03:28:11     0
2019-10-17 03:28:12     0
2019-10-17 03:28:13     0
2019-10-17 03:28:14     0
2019-10-17 03:28:15     0
2019-10-17 03:28:16     0
2019-10-17 03:28:17     0
2019-10-17 03:28:18     0
2019-10-17 03:28:19     0
2019-10-17 03:28:20     0
2019-10-17 03:28:21    27
2019-10-17 03:28:22    50
2019-10-17 03:28:23    50
2019-10-17 03:28:24    50
2019-10-17 03:28:25    51
2019-10-17 03:28:26    50
2019-10-17 03:28:27    50
2019-10-17 03:28:28    50
2019-10-17 03:28:29    50
2019-10-17 03:28:30    50
2019-10-17 03:28:31    49
2019-10-17 03:28:32    51
2019-10-17 03:28:33    50
2019-10-17 03:28:34    50
2019-10-17 03:28:35    24
Freq: S, dtype: int64
La frecuencia media para la actividad Inactive en el username 1 es: 18.375661375661377
La frecuencia mediana para la actividad Inactive en el username 1 es: 5.0
La frecuencia moda para la actividad Inactive en el username 1 es: 5

La frecuencia para la actividad Walking en el username 1 es:
timestamp
2019-10-17 02:26:47    18
2019-10-17 02:26:48    51
2019-10-17 02:26:49    50
2019-10-17 02:26:50    50
2019-10-17 02:26:51    50
2019-10-17 02:26:52    51
2019-10-17 02:26:53    50
2019-10-17 02:26:54    50
2019-10-17 02:26:55    51
2019-10-17 02:26:56    50
2019-10-17 02:26:57    50
2019-10-17 02:26:58    50
2019-10-17 02:26:59    51
2019-10-17 02:27:00    50
2019-10-17 02:27:01    50
2019-10-17 02:27:02    51
2019-10-17 02:27:03    50
2019-10-17 02:27:04    50
2019-10-17 02:27:05    50
2019-10-17 02:27:06    51
2019-10-17 02:27:07    51
2019-10-17 02:27:08    50
2019-10-17 02:27:09    50
2019-10-17 02:27:10    27
2019-10-17 02:27:11     5
2019-10-17 02:27:12     5
2019-10-17 02:27:13     5
2019-10-17 02:27:14     5
2019-10-17 02:27:15     5
2019-10-17 02:27:16     5
2019-10-17 02:27:17     5
2019-10-17 02:27:18     5
2019-10-17 02:27:19     5
2019-10-17 02:27:20     5
2019-10-17 02:27:21     5
2019-10-17 02:27:22     5
2019-10-17 02:27:23     5
2019-10-17 02:27:24     5
2019-10-17 02:27:25     5
2019-10-17 02:27:26     5
Freq: S, dtype: int64
...
timestamp
2019-10-28 09:42:09    50
2019-10-28 09:42:10    50
2019-10-28 09:42:11    51
2019-10-28 09:42:12    50
2019-10-28 09:42:13    50
2019-10-28 09:42:14    51
2019-10-28 09:42:15    50
2019-10-28 09:42:16    50
2019-10-28 09:42:17    50
2019-10-28 09:42:18    51
2019-10-28 09:42:19    50
2019-10-28 09:42:20    50
2019-10-28 09:42:21    51
2019-10-28 09:42:22    50
2019-10-28 09:42:23    50
2019-10-28 09:42:24    50
2019-10-28 09:42:25    51
2019-10-28 09:42:26    51
2019-10-28 09:42:27    50
2019-10-28 09:42:28    50
2019-10-28 09:42:29    50
2019-10-28 09:42:30    50
2019-10-28 09:42:31    50
2019-10-28 09:42:32    51
2019-10-28 09:42:33    50
2019-10-28 09:42:34    50
2019-10-28 09:42:35    51
2019-10-28 09:42:36    50
2019-10-28 09:42:37    50
2019-10-28 09:42:38    50
2019-10-28 09:42:39    51
2019-10-28 09:42:40    50
2019-10-28 09:42:41    51
2019-10-28 09:42:42    51
2019-10-28 09:42:43    50
2019-10-28 09:42:44    50
2019-10-28 09:42:45    50
2019-10-28 09:42:46    51
2019-10-28 09:42:47    50
2019-10-28 09:42:48    43
Freq: S, dtype: int64
La frecuencia media para la actividad Walking en el username 1 es: 34.60640200286123
La frecuencia mediana para la actividad Walking en el username 1 es: 5.0
La frecuencia moda para la actividad Walking en el username 1 es: 5

La frecuencia para la actividad Active en el username 2 es:
timestamp
2019-12-10 10:56:36    1
2019-12-10 10:56:37    0
2019-12-10 10:56:38    0
2019-12-10 10:56:39    0
2019-12-10 10:56:40    0
2019-12-10 10:56:41    0
2019-12-10 10:56:42    1
2019-12-10 10:56:43    5
2019-12-10 10:56:44    5
2019-12-10 10:56:45    5
2019-12-10 10:56:46    5
2019-12-10 10:56:47    5
2019-12-10 10:56:48    6
2019-12-10 10:56:49    5
2019-12-10 10:56:50    5
2019-12-10 10:56:51    5
2019-12-10 10:56:52    5
2019-12-10 10:56:53    5
2019-12-10 10:56:54    5
2019-12-10 10:56:55    5
2019-12-10 10:56:56    5
2019-12-10 10:56:57    5
2019-12-10 10:56:58    5
2019-12-10 10:56:59    5
2019-12-10 10:57:00    5
2019-12-10 10:57:01    5
2019-12-10 10:57:02    5
2019-12-10 10:57:03    5
2019-12-10 10:57:04    5
2019-12-10 10:57:05    5
2019-12-10 10:57:06    5
2019-12-10 10:57:07    5
2019-12-10 10:57:08    5
2019-12-10 10:57:09    5
2019-12-10 10:57:10    5
2019-12-10 10:57:11    5
2019-12-10 10:57:12    5
2019-12-10 10:57:13    5
2019-12-10 10:57:14    5
2019-12-10 10:57:15    5
Freq: S, dtype: int64
...
timestamp
2019-12-16 09:09:24    5
2019-12-16 09:09:25    5
2019-12-16 09:09:26    5
2019-12-16 09:09:27    5
2019-12-16 09:09:28    5
2019-12-16 09:09:29    5
2019-12-16 09:09:30    5
2019-12-16 09:09:31    5
2019-12-16 09:09:32    5
2019-12-16 09:09:33    5
2019-12-16 09:09:34    5
2019-12-16 09:09:35    5
2019-12-16 09:09:36    5
2019-12-16 09:09:37    5
2019-12-16 09:09:38    5
2019-12-16 09:09:39    5
2019-12-16 09:09:40    5
2019-12-16 09:09:41    5
2019-12-16 09:09:42    5
2019-12-16 09:09:43    5
2019-12-16 09:09:44    6
2019-12-16 09:09:45    5
2019-12-16 09:09:46    5
2019-12-16 09:09:47    5
2019-12-16 09:09:48    5
2019-12-16 09:09:49    4
2019-12-16 09:09:50    4
2019-12-16 09:09:51    5
2019-12-16 09:09:52    5
2019-12-16 09:09:53    5
2019-12-16 09:09:54    5
2019-12-16 09:09:55    5
2019-12-16 09:09:56    5
2019-12-16 09:09:57    5
2019-12-16 09:09:58    5
2019-12-16 09:09:59    5
2019-12-16 09:10:00    5
2019-12-16 09:10:01    5
2019-12-16 09:10:02    6
2019-12-16 09:10:03    5
Freq: S, dtype: int64
La frecuencia media para la actividad Active en el username 2 es: 5.138352733166347
La frecuencia mediana para la actividad Active en el username 2 es: 5.0
La frecuencia moda para la actividad Active en el username 2 es: 5

La frecuencia para la actividad Driving en el username 2 es:
timestamp
2019-12-12 19:15:09    3
2019-12-12 19:15:10    6
2019-12-12 19:15:11    5
2019-12-12 19:15:12    5
2019-12-12 19:15:13    5
2019-12-12 19:15:14    5
2019-12-12 19:15:15    5
2019-12-12 19:15:16    5
2019-12-12 19:15:17    5
2019-12-12 19:15:18    5
2019-12-12 19:15:19    5
2019-12-12 19:15:20    5
2019-12-12 19:15:21    5
2019-12-12 19:15:22    5
2019-12-12 19:15:23    5
2019-12-12 19:15:24    5
2019-12-12 19:15:25    5
2019-12-12 19:15:26    5
2019-12-12 19:15:27    5
2019-12-12 19:15:28    5
2019-12-12 19:15:29    5
2019-12-12 19:15:30    5
2019-12-12 19:15:31    5
2019-12-12 19:15:32    5
2019-12-12 19:15:33    5
2019-12-12 19:15:34    5
2019-12-12 19:15:35    5
2019-12-12 19:15:36    5
2019-12-12 19:15:37    5
2019-12-12 19:15:38    5
2019-12-12 19:15:39    6
2019-12-12 19:15:40    5
2019-12-12 19:15:41    5
2019-12-12 19:15:42    5
2019-12-12 19:15:43    5
2019-12-12 19:15:44    5
2019-12-12 19:15:45    5
2019-12-12 19:15:46    5
2019-12-12 19:15:47    5
2019-12-12 19:15:48    5
Freq: S, dtype: int64
...
timestamp
2019-12-19 19:33:14    5
2019-12-19 19:33:15    5
2019-12-19 19:33:16    5
2019-12-19 19:33:17    5
2019-12-19 19:33:18    5
2019-12-19 19:33:19    5
2019-12-19 19:33:20    5
2019-12-19 19:33:21    5
2019-12-19 19:33:22    5
2019-12-19 19:33:23    5
2019-12-19 19:33:24    5
2019-12-19 19:33:25    5
2019-12-19 19:33:26    5
2019-12-19 19:33:27    5
2019-12-19 19:33:28    5
2019-12-19 19:33:29    5
2019-12-19 19:33:30    5
2019-12-19 19:33:31    5
2019-12-19 19:33:32    5
2019-12-19 19:33:33    5
2019-12-19 19:33:34    5
2019-12-19 19:33:35    5
2019-12-19 19:33:36    5
2019-12-19 19:33:37    5
2019-12-19 19:33:38    5
2019-12-19 19:33:39    6
2019-12-19 19:33:40    5
2019-12-19 19:33:41    5
2019-12-19 19:33:42    5
2019-12-19 19:33:43    5
2019-12-19 19:33:44    5
2019-12-19 19:33:45    5
2019-12-19 19:33:46    5
2019-12-19 19:33:47    5
2019-12-19 19:33:48    5
2019-12-19 19:33:49    5
2019-12-19 19:33:50    5
2019-12-19 19:33:51    5
2019-12-19 19:33:52    5
2019-12-19 19:33:53    5
Freq: S, dtype: int64
La frecuencia media para la actividad Driving en el username 2 es: 6.527996681874741
La frecuencia mediana para la actividad Driving en el username 2 es: 5.0
La frecuencia moda para la actividad Driving en el username 2 es: 5

La frecuencia para la actividad Inactive en el username 2 es:
timestamp
2019-10-08 12:15:25    35
2019-10-08 12:15:26    51
2019-10-08 12:15:27    50
2019-10-08 12:15:28    51
2019-10-08 12:15:29    50
2019-10-08 12:15:30    51
2019-10-08 12:15:31    51
2019-10-08 12:15:32    51
2019-10-08 12:15:33    51
2019-10-08 12:15:34    51
2019-10-08 12:15:35    47
2019-10-08 12:15:36     0
2019-10-08 12:15:37     0
2019-10-08 12:15:38     0
2019-10-08 12:15:39     0
2019-10-08 12:15:40     0
2019-10-08 12:15:41     0
2019-10-08 12:15:42     0
2019-10-08 12:15:43     0
2019-10-08 12:15:44     0
2019-10-08 12:15:45     0
2019-10-08 12:15:46     0
2019-10-08 12:15:47     0
2019-10-08 12:15:48     0
2019-10-08 12:15:49     0
2019-10-08 12:15:50     0
2019-10-08 12:15:51     0
2019-10-08 12:15:52     0
2019-10-08 12:15:53     0
2019-10-08 12:15:54     0
2019-10-08 12:15:55     0
2019-10-08 12:15:56     0
2019-10-08 12:15:57     0
2019-10-08 12:15:58     0
2019-10-08 12:15:59     0
2019-10-08 12:16:00     0
2019-10-08 12:16:01     0
2019-10-08 12:16:02     0
2019-10-08 12:16:03     0
2019-10-08 12:16:04     0
Freq: S, dtype: int64
...
timestamp
2019-12-17 14:10:28    5
2019-12-17 14:10:29    5
2019-12-17 14:10:30    5
2019-12-17 14:10:31    5
2019-12-17 14:10:32    5
2019-12-17 14:10:33    5
2019-12-17 14:10:34    5
2019-12-17 14:10:35    5
2019-12-17 14:10:36    5
2019-12-17 14:10:37    6
2019-12-17 14:10:38    5
2019-12-17 14:10:39    5
2019-12-17 14:10:40    5
2019-12-17 14:10:41    5
2019-12-17 14:10:42    5
2019-12-17 14:10:43    5
2019-12-17 14:10:44    5
2019-12-17 14:10:45    5
2019-12-17 14:10:46    5
2019-12-17 14:10:47    5
2019-12-17 14:10:48    5
2019-12-17 14:10:49    5
2019-12-17 14:10:50    5
2019-12-17 14:10:51    5
2019-12-17 14:10:52    5
2019-12-17 14:10:53    5
2019-12-17 14:10:54    5
2019-12-17 14:10:55    5
2019-12-17 14:10:56    5
2019-12-17 14:10:57    5
2019-12-17 14:10:58    5
2019-12-17 14:10:59    5
2019-12-17 14:11:00    5
2019-12-17 14:11:01    5
2019-12-17 14:11:02    5
2019-12-17 14:11:03    5
2019-12-17 14:11:04    5
2019-12-17 14:11:05    5
2019-12-17 14:11:06    6
2019-12-17 14:11:07    4
Freq: S, dtype: int64
La frecuencia media para la actividad Inactive en el username 2 es: 9.848484848484848
La frecuencia mediana para la actividad Inactive en el username 2 es: 5.0
La frecuencia moda para la actividad Inactive en el username 2 es: 5

La frecuencia para la actividad Walking en el username 2 es:
timestamp
2019-10-18 17:10:08     5
2019-10-18 17:10:09    51
2019-10-18 17:10:10    50
2019-10-18 17:10:11    51
2019-10-18 17:10:12    51
2019-10-18 17:10:13    50
2019-10-18 17:10:14    51
2019-10-18 17:10:15    50
2019-10-18 17:10:16    52
2019-10-18 17:10:17    50
2019-10-18 17:10:18    51
2019-10-18 17:10:19    50
2019-10-18 17:10:20    50
2019-10-18 17:10:21    51
2019-10-18 17:10:22    51
2019-10-18 17:10:23    50
2019-10-18 17:10:24    51
2019-10-18 17:10:25    50
2019-10-18 17:10:26    51
2019-10-18 17:10:27    51
2019-10-18 17:10:28    50
2019-10-18 17:10:29    51
2019-10-18 17:10:30    50
2019-10-18 17:10:31    51
2019-10-18 17:10:32    52
2019-10-18 17:10:33    50
2019-10-18 17:10:34    50

El código anterior brinda información tanto de la media como de la mediana y moda, en casos donde estos 3 valores no sean similares se decidio no incluir estos valores, por eso se realiza lo siguiente, donde solo se agregan las frecuencias "Estables" y posteriormente se eliminan las filas con frecuencia vacia

In [ ]:
def calculate_frequency(row):

    if row['username'] == 0 and row['activity'] == 'Driving':
        return 50
    elif row['username'] == 0 and row['activity'] == 'Inactive':
        return 5

    elif row['username'] == 2 and row['activity'] == 'Active':
        return 5
    elif row['username'] == 2 and row['activity'] == 'Driving':
        return 5

    elif row['username'] == 3:
        return 5

    elif row['username'] == 4 and row['activity'] == 'Driving':
        return 98
    elif row['username'] == 4 and row['activity'] == 'Inactive':
        return 85
    elif row['username'] == 4 and row['activity'] == 'Active':
        return 98
    elif row['username'] == 4 and row['activity'] == 'Walking':
        return 98

    elif row['username'] == 5 and row['activity'] == 'Walking':
        return 50

    elif row['username'] == 6 and row['activity'] == 'Driving':
        return 50
    elif row['username'] == 6 and row['activity'] == 'Inactive':
        return 5
    elif row['username'] == 6 and row['activity'] == 'Walking':
        return 50

    elif row['username'] == 7 and row['activity'] == 'Inactive':
        return 5

    elif row['username'] == 8 and row['activity'] == 'Walking':
        return 5

    elif row['username'] == 9:
        return 50

    elif row['username'] == 10 and row['activity'] == 'Driving':
        return 50

    elif row['username'] == 10 and row['activity'] == 'Walking':
        return 50

    elif row['username'] == 11:
       return 50

    elif row['username'] == 12 and row['activity'] == 'Active':
        return 50
    elif row['username'] == 12 and row['activity'] == 'Walking':
        return 50

    elif row['username'] == 14:
        return 50

    elif row['username'] == 15:
        return 5

    elif row['username'] == 0 and row['activity'] == 'Driving':
        return 50

    elif row['username'] == 2 and row['activity'] == 'Walking':
        return 50

acc['frequency'] = acc.apply(calculate_frequency, axis=1)

In [ ]:
filas_vacias = acc['frequency'].isnull()
acc = acc[~filas_vacias]

In [ ]:
acc.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/acc_with_frequency_and_without_strange_values.csv')

In [ ]:
acc_frequency = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/acc_with_frequency_and_without_strange_values.csv')

In [ ]:
acc_frequency

,Unnamed: 0,id,username,timestamp,acc_x_axis,acc_y_axis,acc_z_axis,activity_id,activity,frequency
0,0,4006559,11,1.570534e+09,-0.388868,3.812294,6.222649,-499,Walking,50.0
1,1,4006561,11,1.570534e+09,-0.242817,3.838631,6.059839,-499,Walking,50.0
2,2,4006562,11,1.570534e+09,-0.259577,3.946373,6.023924,-499,Walking,50.0
3,3,4006563,11,1.570534e+09,-0.048881,3.807506,6.090964,-499,Walking,50.0
4,4,4006564,11,1.570534e+09,0.295895,3.795534,6.040684,-499,Walking,50.0
...,...,...,...,...,...,...,...,...,...,...
12174498,17378629,39691767,2,1.576784e+09,0.234983,0.153715,-0.208087,41,Driving,5.0
12174499,17378630,39691770,2,1.576784e+09,0.143519,0.216550,-0.204246,41,Driving,5.0
12174500,17378631,39691773,2,1.576784e+09,0.110278,0.207618,-0.285629,41,Driving,5.0
12174501,17378632,39691776,2,1.576784e+09,0.111215,0.097924,-0.070788,41,Driving,5.0
12174502,17378633,39691779,2,1.576784e+09,0.030945,-0.048773,0.089122,41,Driving,5.0

Ahora se realizará el mismo proceso pero al gyroscopio

In [ ]:
gyro = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/sensoringData_gyro.csv')
gyro

,id,username,timestamp,gyro_x_axis,gyro_y_axis,gyro_z_axis,activity_id,activity
0,4006559,11,1.570534e+09,-0.339005,-0.016215,-0.066681,-499,Walking
1,4006573,11,1.570534e+09,-0.257149,0.072972,0.117189,-499,Walking
2,4006584,11,1.570534e+09,0.094710,-0.013771,0.052437,-499,Walking
3,4006602,11,1.570534e+09,0.545528,0.071750,0.296783,-499,Walking
4,4006622,11,1.570534e+09,0.036067,0.150551,0.119632,-499,Walking
...,...,...,...,...,...,...,...,...
3242316,39691768,2,1.576784e+09,0.023458,0.022109,-0.012746,41,Driving
3242317,39691771,2,1.576784e+09,-0.015828,0.055907,0.023195,41,Driving
3242318,39691774,2,1.576784e+09,-0.022495,-0.012176,0.017558,41,Driving
3242319,39691777,2,1.576784e+09,-0.003558,0.031918,0.014676,41,Driving
3242320,39691780,2,1.576784e+09,-0.000646,0.028983,0.010752,41,Driving

In [ ]:
gyroh = gyro.copy()

gyroh['timestamp'] = pd.to_datetime(gyroh['timestamp'], unit='s')
columnas_deseadas = ['username','timestamp','activity']
gyrohc = gyroh[columnas_deseadas]

In [ ]:
grouped_data = gyrohc.groupby(['username', 'activity'])

result = []
for group_name, group_data in grouped_data:
    username, activity = group_name
    freq = group_data.resample('S', on='timestamp').size()
    freq_nonzero = freq[freq != 0]
    freq_mean = np.mean(freq_nonzero)
    freq_median = np.median(freq_nonzero) if len(freq_nonzero) > 0 else None
    freq_mode = freq_nonzero.mode().values[0] if len(freq_nonzero) > 0 else None
    result.append((username, activity, freq, freq_mean, freq_median, freq_mode))

for username, activity, freq, freq_mean, freq_median, freq_mode in result:
    print(f"La frecuencia para la actividad {activity} en el username {username} es:")
    print(freq.head(50))
    print("...")
    print(freq.tail(50))
    print(f"La frecuencia media para la actividad {activity} en el username {username} es: {freq_mean}")
    print(f"La frecuencia mediana para la actividad {activity} en el username {username} es: {freq_median}")
    print(f"La frecuencia moda para la actividad {activity} en el username {username} es: {freq_mode}")
    print()

La frecuencia para la actividad Driving en el username 0 es:
timestamp
2019-10-10 04:57:40    1
2019-10-10 04:57:41    6
2019-10-10 04:57:42    5
2019-10-10 04:57:43    5
2019-10-10 04:57:44    5
2019-10-10 04:57:45    5
2019-10-10 04:57:46    5
2019-10-10 04:57:47    5
2019-10-10 04:57:48    5
2019-10-10 04:57:49    5
2019-10-10 04:57:50    5
2019-10-10 04:57:51    5
2019-10-10 04:57:52    5
2019-10-10 04:57:53    5
2019-10-10 04:57:54    6
2019-10-10 04:57:55    5
2019-10-10 04:57:56    5
2019-10-10 04:57:57    5
2019-10-10 04:57:58    5
2019-10-10 04:57:59    5
2019-10-10 04:58:00    5
2019-10-10 04:58:01    5
2019-10-10 04:58:02    5
2019-10-10 04:58:03    5
2019-10-10 04:58:04    5
2019-10-10 04:58:05    5
2019-10-10 04:58:06    5
2019-10-10 04:58:07    6
2019-10-10 04:58:08    5
2019-10-10 04:58:09    5
2019-10-10 04:58:10    5
2019-10-10 04:58:11    5
2019-10-10 04:58:12    5
2019-10-10 04:58:13    5
2019-10-10 04:58:14    5
2019-10-10 04:58:15    5
2019-10-10 04:58:16    5
2019-10-10 04:58:17    5
2019-10-10 04:58:18    5
2019-10-10 04:58:19    5
2019-10-10 04:58:20    5
2019-10-10 04:58:21    5
2019-10-10 04:58:22    6
2019-10-10 04:58:23    5
2019-10-10 04:58:24    5
2019-10-10 04:58:25    5
2019-10-10 04:58:26    5
2019-10-10 04:58:27    5
2019-10-10 04:58:28    5
2019-10-10 04:58:29    5
Freq: S, dtype: int64
...
timestamp
2019-10-10 05:16:51    5
2019-10-10 05:16:52    5
2019-10-10 05:16:53    5
2019-10-10 05:16:54    5
2019-10-10 05:16:55    6
2019-10-10 05:16:56    5
2019-10-10 05:16:57    5
2019-10-10 05:16:58    5
2019-10-10 05:16:59    5
2019-10-10 05:17:00    5
2019-10-10 05:17:01    5
2019-10-10 05:17:02    5
2019-10-10 05:17:03    5
2019-10-10 05:17:04    5
2019-10-10 05:17:05    5
2019-10-10 05:17:06    5
2019-10-10 05:17:07    5
2019-10-10 05:17:08    6
2019-10-10 05:17:09    5
2019-10-10 05:17:10    5
2019-10-10 05:17:11    5
2019-10-10 05:17:12    5
2019-10-10 05:17:13    5
2019-10-10 05:17:14    5
2019-10-10 05:17:15    5
2019-10-10 05:17:16    5
2019-10-10 05:17:17    5
2019-10-10 05:17:18    5
2019-10-10 05:17:19    5
2019-10-10 05:17:20    5
2019-10-10 05:17:21    6
2019-10-10 05:17:22    5
2019-10-10 05:17:23    5
2019-10-10 05:17:24    5
2019-10-10 05:17:25    5
2019-10-10 05:17:26    5
2019-10-10 05:17:27    5
2019-10-10 05:17:28    5
2019-10-10 05:17:29    5
2019-10-10 05:17:30    5
2019-10-10 05:17:31    5
2019-10-10 05:17:32    5
2019-10-10 05:17:33    5
2019-10-10 05:17:34    6
2019-10-10 05:17:35    5
2019-10-10 05:17:36    5
2019-10-10 05:17:37    5
2019-10-10 05:17:38    5
2019-10-10 05:17:39    5
2019-10-10 05:17:40    2
Freq: S, dtype: int64
La frecuencia media para la actividad Driving en el username 0 es: 5.064113238967527
La frecuencia mediana para la actividad Driving en el username 0 es: 5.0
La frecuencia moda para la actividad Driving en el username 0 es: 5

La frecuencia para la actividad Inactive en el username 0 es:
timestamp
2019-10-09 13:32:58    2
2019-10-09 13:32:59    5
2019-10-09 13:33:00    5
2019-10-09 13:33:01    5
2019-10-09 13:33:02    5
2019-10-09 13:33:03    5
2019-10-09 13:33:04    5
2019-10-09 13:33:05    5
2019-10-09 13:33:06    5
2019-10-09 13:33:07    5
2019-10-09 13:33:08    5
2019-10-09 13:33:09    5
2019-10-09 13:33:10    6
2019-10-09 13:33:11    5
2019-10-09 13:33:12    5
2019-10-09 13:33:13    5
2019-10-09 13:33:14    5
2019-10-09 13:33:15    5
2019-10-09 13:33:16    5
2019-10-09 13:33:17    5
2019-10-09 13:33:18    5
2019-10-09 13:33:19    5
2019-10-09 13:33:20    5
2019-10-09 13:33:21    5
2019-10-09 13:33:22    5
2019-10-09 13:33:23    5
2019-10-09 13:33:24    5
2019-10-09 13:33:25    6
2019-10-09 13:33:26    5
2019-10-09 13:33:27    5
2019-10-09 13:33:28    5
2019-10-09 13:33:29    5
2019-10-09 13:33:30    5
2019-10-09 13:33:31    5
2019-10-09 13:33:32    5
2019-10-09 13:33:33    5
2019-10-09 13:33:34    5
2019-10-09 13:33:35    5
2019-10-09 13:33:36    5
2019-10-09 13:33:37    5
2019-10-09 13:33:38    6
2019-10-09 13:33:39    5
2019-10-09 13:33:40    5
2019-10-09 13:33:41    5
2019-10-09 13:33:42    5
2019-10-09 13:33:43    5
2019-10-09 13:33:44    5
2019-10-09 13:33:45    3
2019-10-09 13:33:46    0
2019-10-09 13:33:47    0
Freq: S, dtype: int64
...
timestamp
2019-12-10 15:37:46    5
2019-12-10 15:37:47    5
2019-12-10 15:37:48    5
2019-12-10 15:37:49    5
2019-12-10 15:37:50    5
2019-12-10 15:37:51    5
2019-12-10 15:37:52    5
2019-12-10 15:37:53    5
2019-12-10 15:37:54    5
2019-12-10 15:37:55    5
2019-12-10 15:37:56    6
2019-12-10 15:37:57    5
2019-12-10 15:37:58    5
2019-12-10 15:37:59    5
2019-12-10 15:38:00    5
2019-12-10 15:38:01    5
2019-12-10 15:38:02    5
2019-12-10 15:38:03    5
2019-12-10 15:38:04    5
2019-12-10 15:38:05    5
2019-12-10 15:38:06    5
2019-12-10 15:38:07    5
2019-12-10 15:38:08    5
2019-12-10 15:38:09    5
2019-12-10 15:38:10    6
2019-12-10 15:38:11    5
2019-12-10 15:38:12    5
2019-12-10 15:38:13    5
2019-12-10 15:38:14    5
2019-12-10 15:38:15    5
2019-12-10 15:38:16    5
2019-12-10 15:38:17    5
2019-12-10 15:38:18    5
2019-12-10 15:38:19    5
2019-12-10 15:38:20    5
2019-12-10 15:38:21    5
2019-12-10 15:38:22    5
2019-12-10 15:38:23    5
2019-12-10 15:38:24    6
2019-12-10 15:38:25    5
2019-12-10 15:38:26    5
2019-12-10 15:38:27    5
2019-12-10 15:38:28    5
2019-12-10 15:38:29    5
2019-12-10 15:38:30    5
2019-12-10 15:38:31    5
2019-12-10 15:38:32    5
2019-12-10 15:38:33    5
2019-12-10 15:38:34    5
2019-12-10 15:38:35    5
Freq: S, dtype: int64
La frecuencia media para la actividad Inactive en el username 0 es: 5.0632040050062574
La frecuencia mediana para la actividad Inactive en el username 0 es: 5.0
La frecuencia moda para la actividad Inactive en el username 0 es: 5

La frecuencia para la actividad Driving en el username 1 es:
timestamp
2019-10-17 03:00:44    5
2019-10-17 03:00:45    5
2019-10-17 03:00:46    5
2019-10-17 03:00:47    5
2019-10-17 03:00:48    5
2019-10-17 03:00:49    5
2019-10-17 03:00:50    5
2019-10-17 03:00:51    5
2019-10-17 03:00:52    5
2019-10-17 03:00:53    5
2019-10-17 03:00:54    5
2019-10-17 03:00:55    5
2019-10-17 03:00:56    5
2019-10-17 03:00:57    5
2019-10-17 03:00:58    5
2019-10-17 03:00:59    5
2019-10-17 03:01:00    5
2019-10-17 03:01:01    5
2019-10-17 03:01:02    5
2019-10-17 03:01:03    5
2019-10-17 03:01:04    5
2019-10-17 03:01:05    5
2019-10-17 03:01:06    4
2019-10-17 03:01:07    6
2019-10-17 03:01:08    5
2019-10-17 03:01:09    5
2019-10-17 03:01:10    5
2019-10-17 03:01:11    5
2019-10-17 03:01:12    5
2019-10-17 03:01:13    5
2019-10-17 03:01:14    5
2019-10-17 03:01:15    5
2019-10-17 03:01:16    5
2019-10-17 03:01:17    5
2019-10-17 03:01:18    5
2019-10-17 03:01:19    5
2019-10-17 03:01:20    5
2019-10-17 03:01:21    5
2019-10-17 03:01:22    5
2019-10-17 03:01:23    5
2019-10-17 03:01:24    5
2019-10-17 03:01:25    5
2019-10-17 03:01:26    5
2019-10-17 03:01:27    5
2019-10-17 03:01:28    5
2019-10-17 03:01:29    5
2019-10-17 03:01:30    5
2019-10-17 03:01:31    5
2019-10-17 03:01:32    5
2019-10-17 03:01:33    5
Freq: S, dtype: int64
...
timestamp
2019-10-28 09:17:09    5
2019-10-28 09:17:10    5
2019-10-28 09:17:11    5
2019-10-28 09:17:12    5
2019-10-28 09:17:13    5
2019-10-28 09:17:14    5
2019-10-28 09:17:15    5
2019-10-28 09:17:16    5
2019-10-28 09:17:17    5
2019-10-28 09:17:18    5
2019-10-28 09:17:19    5
2019-10-28 09:17:20    5
2019-10-28 09:17:21    6
2019-10-28 09:17:22    4
2019-10-28 09:17:23    5
2019-10-28 09:17:24    5
2019-10-28 09:17:25    5
2019-10-28 09:17:26    5
2019-10-28 09:17:27    5
2019-10-28 09:17:28    6
2019-10-28 09:17:29    5
2019-10-28 09:17:30    5
2019-10-28 09:17:31    4
2019-10-28 09:17:32    5
2019-10-28 09:17:33    5
2019-10-28 09:17:34    5
2019-10-28 09:17:35    5
2019-10-28 09:17:36    5
2019-10-28 09:17:37    5
2019-10-28 09:17:38    5
2019-10-28 09:17:39    5
2019-10-28 09:17:40    5
2019-10-28 09:17:41    5
2019-10-28 09:17:42    5
2019-10-28 09:17:43    5
2019-10-28 09:17:44    5
2019-10-28 09:17:45    5
2019-10-28 09:17:46    5
2019-10-28 09:17:47    5
2019-10-28 09:17:48    5
2019-10-28 09:17:49    5
2019-10-28 09:17:50    5
2019-10-28 09:17:51    5
2019-10-28 09:17:52    5
2019-10-28 09:17:53    5
2019-10-28 09:17:54    5
2019-10-28 09:17:55    5
2019-10-28 09:17:56    4
2019-10-28 09:17:57    5
2019-10-28 09:17:58    4
Freq: S, dtype: int64
La frecuencia media para la actividad Driving en el username 1 es: 5.017487508922199
La frecuencia mediana para la actividad Driving en el username 1 es: 5.0
La frecuencia moda para la actividad Driving en el username 1 es: 5

La frecuencia para la actividad Inactive en el username 1 es:
timestamp
2019-10-16 23:24:57    5
2019-10-16 23:24:58    5
2019-10-16 23:24:59    5
2019-10-16 23:25:00    5
2019-10-16 23:25:01    5
2019-10-16 23:25:02    5
2019-10-16 23:25:03    5
2019-10-16 23:25:04    5
2019-10-16 23:25:05    5
2019-10-16 23:25:06    5
2019-10-16 23:25:07    5
2019-10-16 23:25:08    5
2019-10-16 23:25:09    5
2019-10-16 23:25:10    5
2019-10-16 23:25:11    5
2019-10-16 23:25:12    5
2019-10-16 23:25:13    5
2019-10-16 23:25:14    5
2019-10-16 23:25:15    5
2019-10-16 23:25:16    5
2019-10-16 23:25:17    5
2019-10-16 23:25:18    5
2019-10-16 23:25:19    5
2019-10-16 23:25:20    4
2019-10-16 23:25:21    5
2019-10-16 23:25:22    5
2019-10-16 23:25:23    4
2019-10-16 23:25:24    5
2019-10-16 23:25:25    5
2019-10-16 23:25:26    5
2019-10-16 23:25:27    4
2019-10-16 23:25:28    5
2019-10-16 23:25:29    5
2019-10-16 23:25:30    4
2019-10-16 23:25:31    5
2019-10-16 23:25:32    4
2019-10-16 23:25:33    3
2019-10-16 23:25:34    4
2019-10-16 23:25:35    5
2019-10-16 23:25:36    5
2019-10-16 23:25:37    5
2019-10-16 23:25:38    5
2019-10-16 23:25:39    5
2019-10-16 23:25:40    5
2019-10-16 23:25:41    5
2019-10-16 23:25:42    5
2019-10-16 23:25:43    6
2019-10-16 23:25:44    5
2019-10-16 23:25:45    5
2019-10-16 23:25:46    4
Freq: S, dtype: int64
...
timestamp
2019-10-17 03:27:46    0
2019-10-17 03:27:47    0
2019-10-17 03:27:48    0
2019-10-17 03:27:49    0
2019-10-17 03:27:50    0
2019-10-17 03:27:51    0
2019-10-17 03:27:52    0
2019-10-17 03:27:53    0
2019-10-17 03:27:54    0
2019-10-17 03:27:55    0
2019-10-17 03:27:56    0
2019-10-17 03:27:57    0
2019-10-17 03:27:58    0
2019-10-17 03:27:59    0
2019-10-17 03:28:00    0
2019-10-17 03:28:01    0
2019-10-17 03:28:02    0
2019-10-17 03:28:03    0
2019-10-17 03:28:04    0
2019-10-17 03:28:05    0
2019-10-17 03:28:06    0
2019-10-17 03:28:07    0
2019-10-17 03:28:08    0
2019-10-17 03:28:09    0
2019-10-17 03:28:10    0
2019-10-17 03:28:11    0
2019-10-17 03:28:12    0
2019-10-17 03:28:13    0
2019-10-17 03:28:14    0
2019-10-17 03:28:15    0
2019-10-17 03:28:16    0
2019-10-17 03:28:17    0
2019-10-17 03:28:18    0
2019-10-17 03:28:19    0
2019-10-17 03:28:20    0
2019-10-17 03:28:21    3
2019-10-17 03:28:22    5
2019-10-17 03:28:23    5
2019-10-17 03:28:24    5
2019-10-17 03:28:25    5
2019-10-17 03:28:26    5
2019-10-17 03:28:27    5
2019-10-17 03:28:28    5
2019-10-17 03:28:29    5
2019-10-17 03:28:30    5
2019-10-17 03:28:31    5
2019-10-17 03:28:32    5
2019-10-17 03:28:33    5
2019-10-17 03:28:34    5
2019-10-17 03:28:35    1
Freq: S, dtype: int64
La frecuencia media para la actividad Inactive en el username 1 es: 4.813529411764706
La frecuencia mediana para la actividad Inactive en el username 1 es: 5.0
La frecuencia moda para la actividad Inactive en el username 1 es: 5

La frecuencia para la actividad Walking en el username 1 es:
timestamp
2019-10-17 02:26:47    2
2019-10-17 02:26:48    5
2019-10-17 02:26:49    5
2019-10-17 02:26:50    5
2019-10-17 02:26:51    5
2019-10-17 02:26:52    5
2019-10-17 02:26:53    5
2019-10-17 02:26:54    5
2019-10-17 02:26:55    5
2019-10-17 02:26:56    5
2019-10-17 02:26:57    5
2019-10-17 02:26:58    5
2019-10-17 02:26:59    5
2019-10-17 02:27:00    5
2019-10-17 02:27:01    5
2019-10-17 02:27:02    5
2019-10-17 02:27:03    5
2019-10-17 02:27:04    5
2019-10-17 02:27:05    5
2019-10-17 02:27:06    5
2019-10-17 02:27:07    5
2019-10-17 02:27:08    5
2019-10-17 02:27:09    6
2019-10-17 02:27:10    3
2019-10-17 02:27:11    5
2019-10-17 02:27:12    5
2019-10-17 02:27:13    5
2019-10-17 02:27:14    5
2019-10-17 02:27:15    5
2019-10-17 02:27:16    5
2019-10-17 02:27:17    5
2019-10-17 02:27:18    5
2019-10-17 02:27:19    5
2019-10-17 02:27:20    5
2019-10-17 02:27:21    5
2019-10-17 02:27:22    6
2019-10-17 02:27:23    5
2019-10-17 02:27:24    5
2019-10-17 02:27:25    5
2019-10-17 02:27:26    5
2019-10-17 02:27:27    5
2019-10-17 02:27:28    5
2019-10-17 02:27:29    5
2019-10-17 02:27:30    5
2019-10-17 02:27:31    5
2019-10-17 02:27:32    5
2019-10-17 02:27:33    5
2019-10-17 02:27:34    5
2019-10-17 02:27:35    5
2019-10-17 02:27:36    5
Freq: S, dtype: int64
...
timestamp
2019-10-28 09:41:59    5
2019-10-28 09:42:00    5
2019-10-28 09:42:01    5
2019-10-28 09:42:02    5
2019-10-28 09:42:03    5
2019-10-28 09:42:04    5
2019-10-28 09:42:05    5
2019-10-28 09:42:06    5
2019-10-28 09:42:07    5
2019-10-28 09:42:08    5
2019-10-28 09:42:09    5
2019-10-28 09:42:10    5
2019-10-28 09:42:11    5
2019-10-28 09:42:12    5
2019-10-28 09:42:13    5
2019-10-28 09:42:14    5
2019-10-28 09:42:15    5
2019-10-28 09:42:16    5
2019-10-28 09:42:17    5
2019-10-28 09:42:18    5
2019-10-28 09:42:19    5
2019-10-28 09:42:20    5
2019-10-28 09:42:21    5
2019-10-28 09:42:22    5
2019-10-28 09:42:23    5
2019-10-28 09:42:24    5
2019-10-28 09:42:25    5
2019-10-28 09:42:26    5
2019-10-28 09:42:27    5
2019-10-28 09:42:28    6
2019-10-28 09:42:29    5
2019-10-28 09:42:30    5
2019-10-28 09:42:31    5
2019-10-28 09:42:32    5
2019-10-28 09:42:33    5
2019-10-28 09:42:34    5
2019-10-28 09:42:35    5
2019-10-28 09:42:36    5
2019-10-28 09:42:37    5
2019-10-28 09:42:38    5
2019-10-28 09:42:39    5
2019-10-28 09:42:40    5
2019-10-28 09:42:41    5
2019-10-28 09:42:42    5
2019-10-28 09:42:43    5
2019-10-28 09:42:44    5
2019-10-28 09:42:45    5
2019-10-28 09:42:46    5
2019-10-28 09:42:47    5
2019-10-28 09:42:48    3
Freq: S, dtype: int64
La frecuencia media para la actividad Walking en el username 1 es: 5.011627906976744
La frecuencia mediana para la actividad Walking en el username 1 es: 5.0
La frecuencia moda para la actividad Walking en el username 1 es: 5

La frecuencia para la actividad Active en el username 2 es:
timestamp
2019-12-10 10:56:43    5
2019-12-10 10:56:44    4
2019-12-10 10:56:45    5
2019-12-10 10:56:46    5
2019-12-10 10:56:47    5
2019-12-10 10:56:48    5
2019-12-10 10:56:49    5
2019-12-10 10:56:50    5
2019-12-10 10:56:51    5
2019-12-10 10:56:52    5
2019-12-10 10:56:53    5
2019-12-10 10:56:54    5
2019-12-10 10:56:55    5
2019-12-10 10:56:56    5
2019-12-10 10:56:57    5
2019-12-10 10:56:58    5
2019-12-10 10:56:59    5
2019-12-10 10:57:00    5
2019-12-10 10:57:01    5
2019-12-10 10:57:02    5
2019-12-10 10:57:03    5
2019-12-10 10:57:04    5
2019-12-10 10:57:05    5
2019-12-10 10:57:06    6
2019-12-10 10:57:07    5
2019-12-10 10:57:08    5
2019-12-10 10:57:09    5
2019-12-10 10:57:10    5
2019-12-10 10:57:11    5
2019-12-10 10:57:12    5
2019-12-10 10:57:13    5
2019-12-10 10:57:14    5
2019-12-10 10:57:15    5
2019-12-10 10:57:16    5
2019-12-10 10:57:17    5
2019-12-10 10:57:18    5
2019-12-10 10:57:19    5
2019-12-10 10:57:20    5
2019-12-10 10:57:21    5
2019-12-10 10:57:22    5
2019-12-10 10:57:23    5
2019-12-10 10:57:24    5
2019-12-10 10:57:25    5
2019-12-10 10:57:26    5
2019-12-10 10:57:27    5
2019-12-10 10:57:28    5
2019-12-10 10:57:29    5
2019-12-10 10:57:30    5
2019-12-10 10:57:31    5
2019-12-10 10:57:32    5
Freq: S, dtype: int64
...
timestamp
2019-12-16 09:09:15    5
2019-12-16 09:09:16    5
2019-12-16 09:09:17    5
2019-12-16 09:09:18    5
2019-12-16 09:09:19    5
2019-12-16 09:09:20    5
2019-12-16 09:09:21    5
2019-12-16 09:09:22    5
2019-12-16 09:09:23    5
2019-12-16 09:09:24    5
2019-12-16 09:09:25    5
2019-12-16 09:09:26    5
2019-12-16 09:09:27    6
2019-12-16 09:09:28    5
2019-12-16 09:09:29    5
2019-12-16 09:09:30    5
2019-12-16 09:09:31    5
2019-12-16 09:09:32    5
2019-12-16 09:09:33    5
2019-12-16 09:09:34    5
2019-12-16 09:09:35    5
2019-12-16 09:09:36    5
2019-12-16 09:09:37    5
2019-12-16 09:09:38    5
2019-12-16 09:09:39    5
2019-12-16 09:09:40    5
2019-12-16 09:09:41    5
2019-12-16 09:09:42    5
2019-12-16 09:09:43    5
2019-12-16 09:09:44    5
2019-12-16 09:09:45    5
2019-12-16 09:09:46    5
2019-12-16 09:09:47    5
2019-12-16 09:09:48    5
2019-12-16 09:09:49    3
2019-12-16 09:09:50    3
2019-12-16 09:09:51    5
2019-12-16 09:09:52    5
2019-12-16 09:09:53    5
2019-12-16 09:09:54    5
2019-12-16 09:09:55    5
2019-12-16 09:09:56    5
2019-12-16 09:09:57    5
2019-12-16 09:09:58    5
2019-12-16 09:09:59    5
2019-12-16 09:10:00    5
2019-12-16 09:10:01    5
2019-12-16 09:10:02    5
2019-12-16 09:10:03    5
2019-12-16 09:10:04    1
Freq: S, dtype: int64
La frecuencia media para la actividad Active en el username 2 es: 5.100368459837878
La frecuencia mediana para la actividad Active en el username 2 es: 5.0
La frecuencia moda para la actividad Active en el username 2 es: 5

La frecuencia para la actividad Driving en el username 2 es:
timestamp
2019-12-12 19:15:09    3
2019-12-12 19:15:10    5
2019-12-12 19:15:11    5
2019-12-12 19:15:12    5
2019-12-12 19:15:13    5
2019-12-12 19:15:14    5
2019-12-12 19:15:15    5
2019-12-12 19:15:16    5
2019-12-12 19:15:17    5
2019-12-12 19:15:18    5
2019-12-12 19:15:19    5
2019-12-12 19:15:20    5
2019-12-12 19:15:21    5
2019-12-12 19:15:22    5
2019-12-12 19:15:23    5
2019-12-12 19:15:24    5
2019-12-12 19:15:25    5
2019-12-12 19:15:26    5
2019-12-12 19:15:27    5
2019-12-12 19:15:28    5
2019-12-12 19:15:29    5
2019-12-12 19:15:30    5
2019-12-12 19:15:31    5
2019-12-12 19:15:32    5
2019-12-12 19:15:33    5
2019-12-12 19:15:34    5
2019-12-12 19:15:35    5
2019-12-12 19:15:36    5
2019-12-12 19:15:37    5
2019-12-12 19:15:38    5
2019-12-12 19:15:39    5
2019-12-12 19:15:40    5
2019-12-12 19:15:41    5
2019-12-12 19:15:42    5
2019-12-12 19:15:43    5
2019-12-12 19:15:44    5
2019-12-12 19:15:45    5
2019-12-12 19:15:46    5
2019-12-12 19:15:47    5
2019-12-12 19:15:48    5
2019-12-12 19:15:49    5
2019-12-12 19:15:50    5
2019-12-12 19:15:51    5
2019-12-12 19:15:52    5
2019-12-12 19:15:53    5
2019-12-12 19:15:54    5
2019-12-12 19:15:55    5
2019-12-12 19:15:56    5
2019-12-12 19:15:57    5
2019-12-12 19:15:58    5
Freq: S, dtype: int64
...
timestamp
2019-12-19 19:33:04    5
2019-12-19 19:33:05    5
2019-12-19 19:33:06    5
2019-12-19 19:33:07    5
2019-12-19 19:33:08    5
2019-12-19 19:33:09    5
2019-12-19 19:33:10    4
2019-12-19 19:33:11    5
2019-12-19 19:33:12    5
2019-12-19 19:33:13    5
2019-12-19 19:33:14    5
2019-12-19 19:33:15    5
2019-12-19 19:33:16    5
2019-12-19 19:33:17    5
2019-12-19 19:33:18    5
2019-12-19 19:33:19    5
2019-12-19 19:33:20    5
2019-12-19 19:33:21    5
2019-12-19 19:33:22    5
2019-12-19 19:33:23    5
2019-12-19 19:33:24    5
2019-12-19 19:33:25    5
2019-12-19 19:33:26    5
2019-12-19 19:33:27    5
2019-12-19 19:33:28    5
2019-12-19 19:33:29    5
2019-12-19 19:33:30    5
2019-12-19 19:33:31    5
2019-12-19 19:33:32    5
2019-12-19 19:33:33    5
2019-12-19 19:33:34    5
2019-12-19 19:33:35    5
2019-12-19 19:33:36    5
2019-12-19 19:33:37    5
2019-12-19 19:33:38    5
2019-12-19 19:33:39    5
2019-12-19 19:33:40    5
2019-12-19 19:33:41    5
2019-12-19 19:33:42    5
2019-12-19 19:33:43    5
2019-12-19 19:33:44    5
2019-12-19 19:33:45    5
2019-12-19 19:33:46    5
2019-12-19 19:33:47    5
2019-12-19 19:33:48    5
2019-12-19 19:33:49    5
2019-12-19 19:33:50    5
2019-12-19 19:33:51    5
2019-12-19 19:33:52    5
2019-12-19 19:33:53    5
Freq: S, dtype: int64
La frecuencia media para la actividad Driving en el username 2 es: 4.994190871369295
La frecuencia mediana para la actividad Driving en el username 2 es: 5.0
La frecuencia moda para la actividad Driving en el username 2 es: 5


In [ ]:
def calculate_frequency_for_gyro(row):

    if row['username'] == 0 and row['activity'] == 'Driving':
        return 5
    elif row['username'] == 0 and row['activity'] == 'Inactive':
        return 5

    elif row['username'] == 1 and row['activity'] == 'Driving':
        return 5
    elif row['username'] == 1 and row['activity'] == 'Inactive':
        return 5
    elif row['username'] == 1 and row['activity'] == 'Walking':
        return 5

    elif row['username'] == 2:
        return 5

    elif row['username'] == 3:
        return 5

    elif row['username'] == 5:
        return 5

    elif row['username'] == 6 and row['activity'] == 'Driving':
        return 5
    elif row['username'] == 6 and row['activity'] == 'Inactive':
        return 2

    elif row['username'] == 7:
        return 5

    elif row['username'] == 8:
        return 5

    elif row['username'] == 9:
        return 5

    elif row['username'] == 10:
        return 5

    elif row['username'] == 11:
       return 5

    elif row['username'] == 12:
       return 5

    elif row['username'] == 13:
       return 5

    elif row['username'] == 16:
       return 5


gyro['frequency'] = gyro.apply(calculate_frequency_for_gyro, axis=1)

In [ ]:
filas_vacias = gyro['frequency'].isnull()
gyro = gyro[~filas_vacias]

In [ ]:
gyro.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/gyro_with_frequency_and_without_strange_values.csv')

In [ ]:
gyro_frequency = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/gyro_with_frequency_and_without_strange_values.csv')

In [ ]:
gyro_frequency

,Unnamed: 0,id,username,timestamp,gyro_x_axis,gyro_y_axis,gyro_z_axis,activity_id,activity,frequency
0,0,4006559,11,1.570534e+09,-0.339005,-0.016215,-0.066681,-499,Walking,5.0
1,1,4006573,11,1.570534e+09,-0.257149,0.072972,0.117189,-499,Walking,5.0
2,2,4006584,11,1.570534e+09,0.094710,-0.013771,0.052437,-499,Walking,5.0
3,3,4006602,11,1.570534e+09,0.545528,0.071750,0.296783,-499,Walking,5.0
4,4,4006622,11,1.570534e+09,0.036067,0.150551,0.119632,-499,Walking,5.0
...,...,...,...,...,...,...,...,...,...,...
3085846,3242316,39691768,2,1.576784e+09,0.023458,0.022109,-0.012746,41,Driving,5.0
3085847,3242317,39691771,2,1.576784e+09,-0.015828,0.055907,0.023195,41,Driving,5.0
3085848,3242318,39691774,2,1.576784e+09,-0.022495,-0.012176,0.017558,41,Driving,5.0
3085849,3242319,39691777,2,1.576784e+09,-0.003558,0.031918,0.014676,41,Driving,5.0
3085850,3242320,39691780,2,1.576784e+09,-0.000646,0.028983,0.010752,41,Driving,5.0

In [ ]:
#ordenarlos por timestamp
acc_frequency = acc_frequency.sort_values('timestamp')
gyro_frequency = gyro_frequency.sort_values('timestamp')

In [ ]:
gyro_frequency

,Unnamed: 0,id,username,timestamp,gyro_x_axis,gyro_y_axis,gyro_z_axis,activity_id,activity,frequency
0,0,4006559,11,1.570534e+09,-0.339005,-0.016215,-0.066681,-499,Walking,5.0
1,1,4006573,11,1.570534e+09,-0.257149,0.072972,0.117189,-499,Walking,5.0
2,2,4006584,11,1.570534e+09,0.094710,-0.013771,0.052437,-499,Walking,5.0
3,3,4006602,11,1.570534e+09,0.545528,0.071750,0.296783,-499,Walking,5.0
4,4,4006622,11,1.570534e+09,0.036067,0.150551,0.119632,-499,Walking,5.0
...,...,...,...,...,...,...,...,...,...,...
601398,757868,39691558,6,1.576861e+09,0.030000,0.060000,0.000000,16,Driving,5.0
601399,757869,39691570,6,1.576861e+09,0.000000,0.050000,0.010000,16,Driving,5.0
601400,757870,39691582,6,1.576861e+09,0.020000,0.010000,0.000000,16,Driving,5.0
601401,757871,39691594,6,1.576861e+09,0.000000,-0.010000,0.000000,16,Driving,5.0
601402,757872,39691606,6,1.576861e+09,-1.220000,-1.750000,0.140000,16,Driving,5.0

Debido al tema de las frecuencias se consideró mejor dejar los datasets separados

Primero comenzamos por el acelerometro

In [ ]:
#Modificación del acelerometro
acc_frequency.drop(columns=['Unnamed: 0'], inplace=True)

En cuanto a la asignación del código, el tercer digito se dificulta puesto que una vez los participantes indicaban en la app que actividad iban a realizar estos usaban el celular de la manera que les pareciera, por lo tanto podría estar en su bolsillo, mano o incluso en una mesa, etc. Estos inconvenientos replantean si el uso de este dataset es indicado en nuestro estudio.

In [ ]:
acc_frequency = acc_frequency.rename(columns={'acc_x_axis': 'X_Acc'})
acc_frequency = acc_frequency.rename(columns={'acc_y_axis': 'Y_Acc'})
acc_frequency = acc_frequency.rename(columns={'acc_z_axis': 'Z_Acc'})
acc_frequency = acc_frequency.rename(columns={'activity': 'Activity'})
acc_frequency = acc_frequency.rename(columns={'frequency': 'Frequency'})
acc_frequency = acc_frequency.rename(columns={'username': 'User'})
acc_frequency = acc_frequency.rename(columns={'timestamp': 'TimeStamp'})

In [ ]:
acc_frequency = acc_frequency.rename(columns={'timestamp': 'TimeStamp'})

In [ ]:
acc_frequency.insert(9,'Code', '009')
acc_frequency.insert(10,'Dataset', 2)
acc_frequency.insert(11,'X_Gyro', np.nan)
acc_frequency.insert(12,'Y_Gyro', np.nan)
acc_frequency.insert(13,'Z_Gyro', np.nan)
acc_frequency.insert(14,'X_Acc_6', np.nan)
acc_frequency.insert(15,'Y_Acc_6', np.nan)
acc_frequency.insert(16,'Z_Acc_6', np.nan)
acc_frequency.insert(17,'Trial', np.nan)

In [ ]:
acc_frequency = acc_frequency.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])

In [ ]:
acc_frequency.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_acc.csv')

In [ ]:
acc = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_acc.csv')
acc['TimeStamp'] = pd.to_datetime(acc['TimeStamp'], unit='s')

In [ ]:
acc.drop(columns=['Unnamed: 0'], inplace=True)
acc

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,2,Walking,-0.388868,3.812294,6.222649,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-10-08 11:21:49.356000000,50.0,11,NaN
1,2,Walking,-0.242817,3.838631,6.059839,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-10-08 11:21:52.540999936,50.0,11,NaN
2,2,Walking,-0.259577,3.946373,6.023924,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-10-08 11:21:52.562000128,50.0,11,NaN
3,2,Walking,-0.048881,3.807506,6.090964,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-10-08 11:21:52.583000064,50.0,11,NaN
4,2,Walking,0.295895,3.795534,6.040684,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-10-08 11:21:52.602999808,50.0,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12174498,2,Driving,0.234983,0.153715,-0.208087,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-12-19 19:33:53.099000064,5.0,2,NaN
12174499,2,Driving,0.143519,0.216550,-0.204246,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-12-19 19:33:53.299000064,5.0,2,NaN
12174500,2,Driving,0.110278,0.207618,-0.285629,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-12-19 19:33:53.500000000,5.0,2,NaN
12174501,2,Driving,0.111215,0.097924,-0.070788,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-12-19 19:33:53.700000000,5.0,2,NaN
12174502,2,Driving,0.030945,-0.048773,0.089122,NaN,NaN,NaN,NaN,NaN,NaN,9,2019-12-19 19:33:53.898999808,5.0,2,NaN

In [ ]:
acc.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1.csv')

Continuamos con el giroscopio

In [ ]:
#Realizamos el mismo proceso para el gyro
gyro_frequency.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
gyro_frequency = gyro_frequency.rename(columns={'gyro_x_axis': 'X_Gyro'})
gyro_frequency = gyro_frequency.rename(columns={'gyro_y_axis': 'Y_Gyro'})
gyro_frequency = gyro_frequency.rename(columns={'gyro_z_axis': 'Z_Gyro'})
gyro_frequency = gyro_frequency.rename(columns={'activity': 'Activity'})
gyro_frequency = gyro_frequency.rename(columns={'frequency': 'Frequency'})
gyro_frequency = gyro_frequency.rename(columns={'username': 'User'})
gyro_frequency = gyro_frequency.rename(columns={'timestamp': 'TimeStamp'})

In [ ]:
gyro_frequency.insert(9,'Code', '009')
gyro_frequency.insert(10,'Dataset', 2)
gyro_frequency.insert(11,'X_Acc', np.nan)
gyro_frequency.insert(12,'Y_Acc', np.nan)
gyro_frequency.insert(13,'Z_Acc', np.nan)
gyro_frequency.insert(14,'X_Acc_6', np.nan)
gyro_frequency.insert(15,'Y_Acc_6', np.nan)
gyro_frequency.insert(16,'Z_Acc_6', np.nan)
gyro_frequency.insert(17,'Trial', np.nan)

In [ ]:
gyro_frequency = gyro_frequency.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])

In [ ]:
gyro = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_gyro.csv')

In [ ]:
gyro.drop(columns=['Unnamed: 0'], inplace=True)
gyro

Convertimos los valores del giroscopio a dps

In [ ]:
rad_to_dps = 57.2958

# Conversión para cada columna
gyro['X_Gyro'] = gyro['X_Gyro'] * rad_to_dps
gyro['Y_Gyro'] = gyro['Y_Gyro'] * rad_to_dps
gyro['Z_Gyro'] = gyro['Z_Gyro'] * rad_to_dps

In [ ]:
gyro['TimeStamp'] = pd.to_datetime(gyro['TimeStamp'], unit='s')
gyro

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,2,Walking,NaN,NaN,NaN,-19.423537,-0.929040,-3.820567,NaN,NaN,NaN,9,2019-10-08 11:21:49.356000000,5.0,11,NaN
1,2,Walking,NaN,NaN,NaN,-14.733536,4.180962,6.714438,NaN,NaN,NaN,9,2019-10-08 11:21:52.763000064,5.0,11,NaN
2,2,Walking,NaN,NaN,NaN,5.426472,-0.789040,3.004436,NaN,NaN,NaN,9,2019-10-08 11:21:52.956000000,5.0,11,NaN
3,2,Walking,NaN,NaN,NaN,31.256480,4.110961,17.004442,NaN,NaN,NaN,9,2019-10-08 11:21:53.127000064,5.0,11,NaN
4,2,Walking,NaN,NaN,NaN,2.066471,8.625963,6.854438,NaN,NaN,NaN,9,2019-10-08 11:21:53.311000064,5.0,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3085846,2,Driving,NaN,NaN,NaN,1.344052,1.266757,-0.730264,NaN,NaN,NaN,9,2019-12-19 19:33:53.128000000,5.0,2,NaN
3085847,2,Driving,NaN,NaN,NaN,-0.906868,3.203255,1.328963,NaN,NaN,NaN,9,2019-12-19 19:33:53.328000000,5.0,2,NaN
3085848,2,Driving,NaN,NaN,NaN,-1.288852,-0.697637,1.005981,NaN,NaN,NaN,9,2019-12-19 19:33:53.528999936,5.0,2,NaN
3085849,2,Driving,NaN,NaN,NaN,-0.203872,1.828786,0.840859,NaN,NaN,NaN,9,2019-12-19 19:33:53.729000192,5.0,2,NaN
3085850,2,Driving,NaN,NaN,NaN,-0.037015,1.660588,0.616056,NaN,NaN,NaN,9,2019-12-19 19:33:53.928999936,5.0,2,NaN

In [ ]:
gyro.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2.csv')

In [ ]:
dataset2_part2 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2.csv')

In [ ]:
dataset2_part2 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2.csv')

columns_to_drop = ["X_Acc_6", "Y_Acc_6", "Z_Acc_6"]
dataset2_part2.drop(columns=columns_to_drop, inplace=True)

dataset2_part2.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2.csv', index=False)

In [ ]:
dataset2_part2.describe()

,Unnamed: 0,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,3.085851e+06,3085851.0,0.0,0.0,0.0,3.085851e+06,3.085851e+06,3.085851e+06,3085851.0,3.085851e+06,3.085851e+06,0.0
mean,1.542925e+06,2.0,NaN,NaN,NaN,4.455114e-02,-3.098402e-02,-1.333336e-01,9.0,4.999703e+00,7.628846e+00,NaN
std,8.908086e+05,0.0,NaN,NaN,NaN,3.287389e+01,2.291384e+01,1.489714e+01,0.0,2.987260e-02,2.446735e+00,NaN
min,0.000000e+00,2.0,NaN,NaN,NaN,-6.822512e+02,-7.377401e+02,-6.171840e+02,9.0,2.000000e+00,0.000000e+00,NaN
25%,7.714625e+05,2.0,NaN,NaN,NaN,-1.174850e-01,-4.808455e-02,-6.982783e-02,9.0,5.000000e+00,7.000000e+00,NaN
50%,1.542925e+06,2.0,NaN,NaN,NaN,-1.906872e-03,2.132606e-03,-1.954829e-03,9.0,5.000000e+00,7.000000e+00,NaN
75%,2.314388e+06,2.0,NaN,NaN,NaN,5.337106e-02,7.729201e-02,2.924802e-02,9.0,5.000000e+00,1.000000e+01,NaN
max,3.085850e+06,2.0,NaN,NaN,NaN,5.841028e+02,1.498522e+03,5.688049e+02,9.0,5.000000e+00,1.600000e+01,NaN

In [ ]:
dataset2_part1 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1.csv')

In [ ]:
dataset2_part1 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1.csv')

columns_to_drop = ["X_Acc_6", "Y_Acc_6", "Z_Acc_6"]
dataset2_part1.drop(columns=columns_to_drop, inplace=True)

dataset2_part1.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1.csv', index=False)

In [ ]:
dataset2_part1.describe()

,Unnamed: 0,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,1.217450e+07,12174503.0,1.217450e+07,1.217450e+07,1.217450e+07,0.0,0.0,0.0,12174503.0,1.217450e+07,1.217450e+07,0.0
mean,6.087251e+06,2.0,4.343586e-02,-1.288717e-01,2.962449e-01,NaN,NaN,NaN,9.0,5.706281e+01,7.284959e+00,NaN
std,3.514476e+06,0.0,1.651604e+00,2.020694e+00,2.413436e+00,NaN,NaN,NaN,0.0,2.886446e+01,2.982114e+00,NaN
min,0.000000e+00,2.0,-4.537716e+01,-7.259351e+01,-6.098931e+01,NaN,NaN,NaN,9.0,5.000000e+00,0.000000e+00,NaN
25%,3.043626e+06,2.0,-1.937054e-01,-2.629126e-01,-2.211032e-01,NaN,NaN,NaN,9.0,5.000000e+01,4.000000e+00,NaN
50%,6.087251e+06,2.0,1.230821e-03,-7.448196e-04,2.590179e-03,NaN,NaN,NaN,9.0,5.000000e+01,7.000000e+00,NaN
75%,9.130876e+06,2.0,2.402588e-01,1.980100e-01,3.279712e-01,NaN,NaN,NaN,9.0,9.800000e+01,1.000000e+01,NaN
max,1.217450e+07,2.0,6.034109e+01,4.625486e+01,5.224711e+01,NaN,NaN,NaN,9.0,9.800000e+01,1.500000e+01,NaN

In [ ]:
import pandas as pd
import json

resultado1 = dataset2_part1.describe()
resultado2 = dataset2_part2.describe()
# Convertir el resultado en un diccionario
resultado_diccionario1 = resultado1.to_dict()
resultado_diccionario2 = resultado2.to_dict()

# Convertir el diccionario en una cadena JSON
json_string1 = json.dumps(resultado_diccionario1)
json_string2 = json.dumps(resultado_diccionario2)

# Guardar la cadena JSON en un archivo .json
ruta_json1 = '/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1_describe.json'
ruta_json2 = '/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2_describe.json'
with open(ruta_json2, 'w') as archivo:
    archivo.write(json_string2)
with open(ruta_json1, 'w') as archivo:
    archivo.write(json_string1)

### Modificación de la parte 1, acelerometro

In [ ]:
Dataset_2 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1.csv')

In [ ]:
Dataset_2['Code'] = Dataset_2['Code'].replace(9, 309)

In [ ]:
Dataset_2 = Dataset_2.drop(columns=['Unnamed: 0'])

In [ ]:
Dataset_2.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1.csv', index=False)

En un futuro de la investigación del proyecto se planteó la dificultad que plantea el trebajar con varias frecuencias en un mismo dataset, por lo que solo dejamos la frecuencia de 50 Hz, adicionalmente teniendo en cuenta que las actividades no son especificas, consideramos dejar la actividad de conduciendo unicamente, esto solo con el fin de no eliminar por completo el dataset, aunque si se propone debido a como fue el etiquetado y que las actividades son muy generales

In [ ]:
Dataset_2 = Dataset_2[~Dataset_2['Activity'].isin(['Walking', 'Active', 'Inactive'])]

Dataset_2 = Dataset_2[Dataset_2['Frequency'] == 50]

In [ ]:
Dataset_2.reset_index(drop=True, inplace=True)

In [ ]:
Dataset_2

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2,Driving,-2.015789,4.959241,5.242635,NaN,NaN,NaN,309,2019-12-11 17:53:19.448000000,50.0,11,NaN
1,2,Driving,-1.848190,4.691082,5.407840,NaN,NaN,NaN,309,2019-12-11 17:53:19.448000000,50.0,11,NaN
2,2,Driving,-1.224591,2.878019,2.725262,NaN,NaN,NaN,309,2019-12-11 17:53:19.676999936,50.0,11,NaN
3,2,Driving,-0.951644,2.686477,2.773147,NaN,NaN,NaN,309,2019-12-11 17:53:19.877000192,50.0,11,NaN
4,2,Driving,-1.949071,1.851629,1.480463,NaN,NaN,NaN,309,2019-12-11 17:53:20.078000128,50.0,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2825508,2,Driving,-1.356559,-0.127326,0.764153,NaN,NaN,NaN,309,2019-12-18 19:54:22.428999936,50.0,10,NaN
2825509,2,Driving,-1.291881,-0.080614,0.537777,NaN,NaN,NaN,309,2019-12-18 19:54:22.448999936,50.0,10,NaN
2825510,2,Driving,-1.139766,0.003228,0.249119,NaN,NaN,NaN,309,2019-12-18 19:54:22.470000128,50.0,10,NaN
2825511,2,Driving,-1.241575,-0.080614,0.198814,NaN,NaN,NaN,309,2019-12-18 19:54:22.490000128,50.0,10,NaN
2825512,2,Driving,-1.227202,-0.123733,0.235945,NaN,NaN,NaN,309,2019-12-18 19:54:22.509999872,50.0,10,NaN

In [ ]:
Dataset_2.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1_Only_Driving.csv', index=False)

###Modificación de la parte 2, giroscopio

In [ ]:
Dataset_2_2 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2.csv')

In [ ]:
Dataset_2_2['Code'] = Dataset_2_2['Code'].replace(9, 309)

In [ ]:
Dataset_2_2 = Dataset_2_2.drop(columns=['Unnamed: 0'])
Dataset_2_2 = Dataset_2_2[~Dataset_2_2['Activity'].isin(['Walking', 'Active', 'Inactive'])]

Dataset_2_2 = Dataset_2_2[Dataset_2_2['Frequency'] == 5]
Dataset_2_2.reset_index(drop=True, inplace=True)

In [ ]:
Dataset_2_2

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2,Driving,NaN,NaN,NaN,5.247552,11.094723,-5.734297,309,2019-12-11 17:53:19.477999872,5.0,11,NaN
1,2,Driving,NaN,NaN,NaN,5.807552,-2.030281,-1.289295,309,2019-12-11 17:53:19.639000064,5.0,11,NaN
2,2,Driving,NaN,NaN,NaN,-2.207451,1.749721,-2.934296,309,2019-12-11 17:53:19.828999936,5.0,11,NaN
3,2,Driving,NaN,NaN,NaN,-5.427452,32.479733,16.140711,309,2019-12-11 17:53:20.017999872,5.0,11,NaN
4,2,Driving,NaN,NaN,NaN,4.337552,17.289727,27.655714,309,2019-12-11 17:53:20.209000192,5.0,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
435202,2,Driving,NaN,NaN,NaN,1.344052,1.266757,-0.730264,309,2019-12-19 19:33:53.128000000,5.0,2,NaN
435203,2,Driving,NaN,NaN,NaN,-0.906868,3.203255,1.328963,309,2019-12-19 19:33:53.328000000,5.0,2,NaN
435204,2,Driving,NaN,NaN,NaN,-1.288852,-0.697637,1.005981,309,2019-12-19 19:33:53.528999936,5.0,2,NaN
435205,2,Driving,NaN,NaN,NaN,-0.203872,1.828786,0.840859,309,2019-12-19 19:33:53.729000192,5.0,2,NaN
435206,2,Driving,NaN,NaN,NaN,-0.037015,1.660588,0.616056,309,2019-12-19 19:33:53.928999936,5.0,2,NaN

In [ ]:
Dataset_2_2.to_csv('/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2_Only_Driving.csv', index=False)

## Actividades

In [ ]:
ruta1 = '/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1_Only_Driving.csv'
ruta2 = '/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2_Only_Driving.csv'
dataset2_part1 = pd.read_csv(ruta1)
dataset2_part2 = pd.read_csv(ruta2)

In [ ]:
dataset2_part2

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2,Driving,NaN,NaN,NaN,5.25,11.09,-5.73,309,2019-12-11 17:53:19.477999872,5.00,11,NaN
1,2,Driving,NaN,NaN,NaN,5.81,-2.03,-1.29,309,2019-12-11 17:53:19.639000064,5.00,11,NaN
2,2,Driving,NaN,NaN,NaN,-2.21,1.75,-2.93,309,2019-12-11 17:53:19.828999936,5.00,11,NaN
3,2,Driving,NaN,NaN,NaN,-5.43,32.48,16.14,309,2019-12-11 17:53:20.017999872,5.00,11,NaN
4,2,Driving,NaN,NaN,NaN,4.34,17.29,27.66,309,2019-12-11 17:53:20.209000192,5.00,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
435202,2,Driving,NaN,NaN,NaN,1.34,1.27,-0.73,309,2019-12-19 19:33:53.128000000,5.00,2,NaN
435203,2,Driving,NaN,NaN,NaN,-0.91,3.20,1.33,309,2019-12-19 19:33:53.328000000,5.00,2,NaN
435204,2,Driving,NaN,NaN,NaN,-1.29,-0.70,1.01,309,2019-12-19 19:33:53.528999936,5.00,2,NaN
435205,2,Driving,NaN,NaN,NaN,-0.20,1.83,0.84,309,2019-12-19 19:33:53.729000192,5.00,2,NaN
435206,2,Driving,NaN,NaN,NaN,-0.04,1.66,0.62,309,2019-12-19 19:33:53.928999936,5.00,2,NaN

In [ ]:
dataset2_part1["Activity"].unique()

Driving

In [ ]:
f = dataset2_part1.copy()

df['Activity'] = df['Activity'].apply(lambda x: 12 if x == 'Driving' else x)

df

Proceso completado con éxito.

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2,12,-2.02,4.96,5.24,NaN,NaN,NaN,309,2019-12-11 17:53:19.448000000,50.00,11,NaN
1,2,12,-1.85,4.69,5.41,NaN,NaN,NaN,309,2019-12-11 17:53:19.448000000,50.00,11,NaN
2,2,12,-1.22,2.88,2.73,NaN,NaN,NaN,309,2019-12-11 17:53:19.676999936,50.00,11,NaN
3,2,12,-0.95,2.69,2.77,NaN,NaN,NaN,309,2019-12-11 17:53:19.877000192,50.00,11,NaN
4,2,12,-1.95,1.85,1.48,NaN,NaN,NaN,309,2019-12-11 17:53:20.078000128,50.00,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2825508,2,12,-1.36,-0.13,0.76,NaN,NaN,NaN,309,2019-12-18 19:54:22.428999936,50.00,10,NaN
2825509,2,12,-1.29,-0.08,0.54,NaN,NaN,NaN,309,2019-12-18 19:54:22.448999936,50.00,10,NaN
2825510,2,12,-1.14,0.00,0.25,NaN,NaN,NaN,309,2019-12-18 19:54:22.470000128,50.00,10,NaN
2825511,2,12,-1.24,-0.08,0.20,NaN,NaN,NaN,309,2019-12-18 19:54:22.490000128,50.00,10,NaN
2825512,2,12,-1.23,-0.12,0.24,NaN,NaN,NaN,309,2019-12-18 19:54:22.509999872,50.00,10,NaN

In [ ]:
dataset2_part2["Activity"].unique()

Driving

In [ ]:
df = dataset2_part2.copy()

df['Activity'] = df['Activity'].apply(lambda x: 12 if x == 'Driving' else x)

df

Proceso completado con éxito.

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2,12,NaN,NaN,NaN,5.25,11.09,-5.73,309,2019-12-11 17:53:19.477999872,5.00,11,NaN
1,2,12,NaN,NaN,NaN,5.81,-2.03,-1.29,309,2019-12-11 17:53:19.639000064,5.00,11,NaN
2,2,12,NaN,NaN,NaN,-2.21,1.75,-2.93,309,2019-12-11 17:53:19.828999936,5.00,11,NaN
3,2,12,NaN,NaN,NaN,-5.43,32.48,16.14,309,2019-12-11 17:53:20.017999872,5.00,11,NaN
4,2,12,NaN,NaN,NaN,4.34,17.29,27.66,309,2019-12-11 17:53:20.209000192,5.00,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
435202,2,12,NaN,NaN,NaN,1.34,1.27,-0.73,309,2019-12-19 19:33:53.128000000,5.00,2,NaN
435203,2,12,NaN,NaN,NaN,-0.91,3.20,1.33,309,2019-12-19 19:33:53.328000000,5.00,2,NaN
435204,2,12,NaN,NaN,NaN,-1.29,-0.70,1.01,309,2019-12-19 19:33:53.528999936,5.00,2,NaN
435205,2,12,NaN,NaN,NaN,-0.20,1.83,0.84,309,2019-12-19 19:33:53.729000192,5.00,2,NaN
435206,2,12,NaN,NaN,NaN,-0.04,1.66,0.62,309,2019-12-19 19:33:53.928999936,5.00,2,NaN

## Resampling

In [ ]:
ruta1_antes = '/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_1_Only_Driving.csv'
ruta2_antes = '/content/drive/MyDrive/TESIS_DATASET/2. A Public Domain Dataset For Real-life Human Activity Recognition Using Smartphone Sensors/Dataset_2_Final/Dataset_2_part_2_Only_Driving.csv'
ruta1 = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset2_part1.csv'
ruta2= '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset2_part2.csv'
dataset2_parte1_antes = pd.read_csv(ruta1_antes)
dataset2_parte2_antes = pd.read_csv(ruta2_antes)
dataset2_parte1 = pd.read_csv(ruta1)
dataset2_parte2 = pd.read_csv(ruta2)

### Resampling Antes

In [ ]:
dataset2_parte1_antes.describe()

,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,2825513.0,2.825513e+06,2.825513e+06,2.825513e+06,0.0,0.0,0.0,2825513.0,2825513.0,2.825513e+06,0.0
mean,2.0,-8.443335e-02,-2.558697e-01,3.465701e-01,NaN,NaN,NaN,309.0,50.0,7.809671e+00,NaN
std,0.0,1.034653e+00,1.174070e+00,1.619404e+00,NaN,NaN,NaN,0.0,0.0,2.184136e+00,NaN
min,2.0,-3.474371e+01,-3.775605e+01,-3.590360e+01,NaN,NaN,NaN,309.0,50.0,0.000000e+00,NaN
25%,2.0,-5.034314e-01,-7.495232e-01,-4.657879e-01,NaN,NaN,NaN,309.0,50.0,6.000000e+00,NaN
50%,2.0,-2.788115e-02,-9.281945e-02,-2.999783e-02,NaN,NaN,NaN,309.0,50.0,9.000000e+00,NaN
75%,2.0,3.655224e-01,3.109115e-01,6.580429e-01,NaN,NaN,NaN,309.0,50.0,1.000000e+01,NaN
max,2.0,3.031244e+01,3.817853e+01,4.070599e+01,NaN,NaN,NaN,309.0,50.0,1.100000e+01,NaN

In [ ]:
dataset2_parte2_antes.describe()

,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,435207.0,0.0,0.0,0.0,435207.000000,435207.000000,435207.000000,435207.0,435207.0,435207.000000,0.0
mean,2.0,NaN,NaN,NaN,0.045852,0.158757,-0.139068,309.0,5.0,7.168007,NaN
std,0.0,NaN,NaN,NaN,11.014274,11.364713,9.555931,0.0,0.0,2.604967,NaN
min,2.0,NaN,NaN,NaN,-463.523031,-686.035428,-425.629456,309.0,5.0,0.000000,NaN
25%,2.0,NaN,NaN,NaN,-0.936572,-1.145916,-1.145916,309.0,5.0,6.000000,NaN
50%,2.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,309.0,5.0,7.000000,NaN
75%,2.0,NaN,NaN,NaN,0.976563,1.223960,0.816690,309.0,5.0,9.000000,NaN
max,2.0,NaN,NaN,NaN,397.632855,574.402066,568.804916,309.0,5.0,11.000000,NaN

### Resampling Después

In [ ]:
dataset2_parte1 = resample_dataframe(dataset2_parte1)
dataset2_parte1.to_csv(ruta1, index=False)

In [ ]:
dataset2_parte2 = resample_dataframe(df)

In [ ]:
dataset2_parte1

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2,12,-2.015789,4.959241,5.242635,NaN,NaN,NaN,309,2019-12-11 17:53:19.448000000,50.0,11,NaN
1,2,12,-1.848190,4.691082,5.407840,NaN,NaN,NaN,309,2019-12-11 17:53:19.448000000,50.0,11,NaN
2,2,12,-1.224591,2.878019,2.725262,NaN,NaN,NaN,309,2019-12-11 17:53:19.676999936,50.0,11,NaN
3,2,12,-0.951644,2.686477,2.773147,NaN,NaN,NaN,309,2019-12-11 17:53:19.877000192,50.0,11,NaN
4,2,12,-1.949071,1.851629,1.480463,NaN,NaN,NaN,309,2019-12-11 17:53:20.078000128,50.0,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2825508,2,12,-1.356559,-0.127326,0.764153,NaN,NaN,NaN,309,2019-12-18 19:54:22.428999936,50.0,10,NaN
2825509,2,12,-1.291881,-0.080614,0.537777,NaN,NaN,NaN,309,2019-12-18 19:54:22.448999936,50.0,10,NaN
2825510,2,12,-1.139766,0.003228,0.249119,NaN,NaN,NaN,309,2019-12-18 19:54:22.470000128,50.0,10,NaN
2825511,2,12,-1.241575,-0.080614,0.198814,NaN,NaN,NaN,309,2019-12-18 19:54:22.490000128,50.0,10,NaN
2825512,2,12,-1.227202,-0.123733,0.235945,NaN,NaN,NaN,309,2019-12-18 19:54:22.509999872,50.0,10,NaN

In [ ]:
dataset2_parte2

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2,12,NaN,NaN,NaN,45.00,0.76,27.61,309,2019-10-10 04:57:40.821000192,50,0,NaN
1,2,12,NaN,NaN,NaN,45.00,0.76,27.61,309,2019-10-10 04:57:40.821000192,50,0,NaN
2,2,12,NaN,NaN,NaN,45.00,0.76,27.61,309,2019-10-10 04:57:40.821000192,50,0,NaN
3,2,12,NaN,NaN,NaN,45.00,0.76,27.61,309,2019-10-10 04:57:40.821000192,50,0,NaN
4,2,12,NaN,NaN,NaN,45.00,0.76,27.61,309,2019-10-10 04:57:40.821000192,50,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4352065,2,12,NaN,NaN,NaN,54.75,22.88,1.44,309,2019-12-18 08:35:19.496000000,50,11,NaN
4352066,2,12,NaN,NaN,NaN,54.75,22.88,1.44,309,2019-12-18 08:35:19.496000000,50,11,NaN
4352067,2,12,NaN,NaN,NaN,54.75,22.88,1.44,309,2019-12-18 08:35:19.496000000,50,11,NaN
4352068,2,12,NaN,NaN,NaN,54.75,22.88,1.44,309,2019-12-18 08:35:19.496000000,50,11,NaN
4352069,2,12,NaN,NaN,NaN,54.75,22.88,1.44,309,2019-12-18 08:35:19.496000000,50,11,NaN

In [ ]:
dataset2_parte2.to_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset2_part2.csv',index=False)

##Análisis Gráfico Dataset 2 parte 1

In [ ]:
ruta1 = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset2_part1.csv'
ruta2= '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset2_part2.csv'
dataset2_parte1 = pd.read_csv(ruta1)
dataset2_parte2 = pd.read_csv(ruta2)

In [ ]:
df = dataset2_parte1
df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2,12,-2.015789,4.959241,5.242635,NaN,NaN,NaN,309,2019-12-11 17:53:19.448000000,50.0,11,NaN
1,2,12,-1.848190,4.691082,5.407840,NaN,NaN,NaN,309,2019-12-11 17:53:19.448000000,50.0,11,NaN
2,2,12,-1.224591,2.878019,2.725262,NaN,NaN,NaN,309,2019-12-11 17:53:19.676999936,50.0,11,NaN
3,2,12,-0.951644,2.686477,2.773147,NaN,NaN,NaN,309,2019-12-11 17:53:19.877000192,50.0,11,NaN
4,2,12,-1.949071,1.851629,1.480463,NaN,NaN,NaN,309,2019-12-11 17:53:20.078000128,50.0,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2825508,2,12,-1.356559,-0.127326,0.764153,NaN,NaN,NaN,309,2019-12-18 19:54:22.428999936,50.0,10,NaN
2825509,2,12,-1.291881,-0.080614,0.537777,NaN,NaN,NaN,309,2019-12-18 19:54:22.448999936,50.0,10,NaN
2825510,2,12,-1.139766,0.003228,0.249119,NaN,NaN,NaN,309,2019-12-18 19:54:22.470000128,50.0,10,NaN
2825511,2,12,-1.241575,-0.080614,0.198814,NaN,NaN,NaN,309,2019-12-18 19:54:22.490000128,50.0,10,NaN
2825512,2,12,-1.227202,-0.123733,0.235945,NaN,NaN,NaN,309,2019-12-18 19:54:22.509999872,50.0,10,NaN

###Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(df)

### Valores Máximo y Mínimos Acelerometro

In [ ]:
grafico_acelerometro_max_min(df)

### Valores Válidos Giroscopio

In [ ]:
grafico_giroscopio_valido(df)

###Valores Máximo y Mínimos Giroscopio

In [ ]:
grafico_giroscopio_max_min(df)

###Actividades Válidas

In [ ]:
grafico_activity(df)

## Análisis Gráfico Dataset 2 parte 2

In [ ]:
df = dataset2_parte2

###Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(df)

### Valores Máximo y Mínimos Acelerometro

In [ ]:
grafico_acelerometro_max_min(df)

### Valores Válidos Giroscopio

In [ ]:
grafico_giroscopio_valido(df)

###Valores Máximo y Mínimos Giroscopio

In [ ]:
grafico_giroscopio_max_min(df)

###Actividades Válidas

In [ ]:
grafico_activity(df)

## Describe

In [ ]:
ruta1 = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset2_part1.csv'
ruta2= '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset2_part2.csv'
dataset2_parte1 = pd.read_csv(ruta1)
dataset2_parte2 = pd.read_csv(ruta2)

In [ ]:
dataset2_parte1.describe()

,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,2260410.0,2.260410e+06,2.260410e+06,2.260410e+06,0.0,0.0,0.0,2260410.0,2260410.0,2.260410e+06,0.0
mean,12.0,-8.416110e-02,-2.556334e-01,3.464736e-01,NaN,NaN,NaN,309.0,40.0,7.810241e+00,NaN
std,0.0,1.035463e+00,1.173124e+00,1.618826e+00,NaN,NaN,NaN,0.0,0.0,2.183176e+00,NaN
min,12.0,-3.474371e+01,-3.775605e+01,-3.590360e+01,NaN,NaN,NaN,309.0,40.0,0.000000e+00,NaN
25%,12.0,-5.029827e-01,-7.491450e-01,-4.655343e-01,NaN,NaN,NaN,309.0,40.0,6.000000e+00,NaN
50%,12.0,-2.773796e-02,-9.291941e-02,-2.999926e-02,NaN,NaN,NaN,309.0,40.0,9.000000e+00,NaN
75%,12.0,3.658168e-01,3.107141e-01,6.579942e-01,NaN,NaN,NaN,309.0,40.0,1.000000e+01,NaN
max,12.0,3.031244e+01,2.594598e+01,3.938272e+01,NaN,NaN,NaN,309.0,40.0,1.100000e+01,NaN

In [ ]:
dataset2_parte2.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,4352070.00,4352070.00,0.00,0.00,0.00,4352070.00,4352070.00,4352070.00,4352070.00,4352070.00,4352070.00,0.00
mean,2.00,12.00,NaN,NaN,NaN,0.05,0.16,-0.14,309.00,50.00,7.17,NaN
std,0.00,0.00,NaN,NaN,NaN,11.01,11.36,9.56,0.00,0.00,2.60,NaN
min,2.00,12.00,NaN,NaN,NaN,-463.52,-686.04,-425.63,309.00,50.00,0.00,NaN
25%,2.00,12.00,NaN,NaN,NaN,-0.94,-1.15,-1.15,309.00,50.00,6.00,NaN
50%,2.00,12.00,NaN,NaN,NaN,0.00,0.00,0.00,309.00,50.00,7.00,NaN
75%,2.00,12.00,NaN,NaN,NaN,0.98,1.22,0.82,309.00,50.00,9.00,NaN
max,2.00,12.00,NaN,NaN,NaN,397.63,574.40,568.80,309.00,50.00,11.00,NaN

# Dataset número 3. THE USC SIPI Human

## Preparación del Dataset Número 3

In [ ]:
import scipy.io

# Cargar el archivo .mat
ruta_archivo_mat = "/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject1/a10t1.mat"
data = scipy.io.loadmat(ruta_archivo_mat)

# Imprimir la información de la estructura del archivo
scipy.io.whosmat(ruta_archivo_mat)

In [ ]:
# Imprimir la información de la estructura del archivo
scipy.io.whosmat(ruta_archivo_mat)
import scipy.io

mat_file = scipy.io.loadmat('/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject1/a10t1.mat')

print(scipy.io.whosmat('/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject1/a10t1.mat'))

In [ ]:
import scipy.io
import pandas as pd
import os

ruta_origen = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject1/a10t1.mat'
ruta_destino = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject_1_MATtoCSV'

data = scipy.io.loadmat(ruta_origen)

# Extraer sensor readings
sensor_readings = data['sensor_readings']

# Extraer sujeto y actividad
subject = data['subject'][0]
activity = data['activity'][0]
trial = data['trial'][0]

df = pd.DataFrame(sensor_readings, columns=['x_ace', 'y_ace', 'z_ace', 'x_giro', 'y_giro', 'z_giro'])

# Agregar columna de sujeto, actividad y trial
df.insert(0, 'subject', subject)
df.insert(1, 'activity', activity)
df.insert(2, 'trial', trial)

# Escribir archivo csv
nombre_archivo = f'csv_at1t1.csv'
ruta_archivo = os.path.join(ruta_destino, nombre_archivo)
df.to_csv(ruta_archivo, index=False)

print(f'Se ha creado exitosamente el archivo csv en la siguiente ruta: {ruta_archivo}')

Se ha creado exitosamente el archivo csv en la siguiente ruta: /content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject_1_MATtoCSV/csv_at1t1.csv

In [ ]:
Archivo_Prueba_CSV = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject_1_MATtoCSV/csv_at1t1.csv')
Archivo_Prueba_CSV

,subject,activity,trial,x_ace,y_ace,z_ace,x_giro,y_giro,z_giro
0,1,sleeping,1,-0.653698,0.711878,-0.423886,-0.203916,-0.309533,-0.464422
1,1,sleeping,1,-0.646831,0.708259,-0.420226,0.103647,-0.161285,-0.241990
2,1,sleeping,1,-0.650265,0.711878,-0.423886,0.069611,-0.108322,-0.162525
3,1,sleeping,1,-0.646831,0.711878,-0.423886,0.352995,0.220050,0.179550
4,1,sleeping,1,-0.643397,0.711878,-0.427546,0.279527,0.174251,0.142181
...,...,...,...,...,...,...,...,...,...
4495,1,sleeping,1,-0.626228,0.614162,-0.551991,-7.180061,-9.711401,-2.717374
4496,1,sleeping,1,-0.633096,0.610543,-0.551991,-7.180061,-10.114233,-4.722544
4497,1,sleeping,1,-0.646831,0.614162,-0.544671,-6.777229,-9.711401,-5.528208
4498,1,sleeping,1,-0.657132,0.610543,-0.537351,-6.777229,-8.905737,-5.528208
4499,1,sleeping,1,-0.670867,0.610543,-0.530030,-7.180061,-8.502905,-4.319712

A continuación con el código de prueba, se va a realizar este mismo procedimiento para todos las carpetas de sujetos (Subject1 - Subject14) y se va a crear una nueva carpeta con esta información en CSV de nombre: Subjects_1_14_CSV

In [ ]:
import os
import pandas as pd
import scipy.io

ruta_origen = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD'
ruta_destino = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject1_14_CSV'

# Obtener la lista de carpetas de Subject1 a Subject14 en la ruta de origen
carpetas = [x for x in os.listdir(ruta_origen) if x.startswith('Subject')]

# Imprimir el número de archivos por carpeta en la ruta de origen
for carpeta in carpetas:
    ruta_carpeta = os.path.join(ruta_origen, carpeta)
    archivos_mat = [x for x in os.listdir(ruta_carpeta) if x.endswith('.mat')]
    print(f'La carpeta {carpeta} contiene {len(archivos_mat)} archivos .mat')

# Procesar cada carpeta y transformar archivos .mat a archivos .csv
for carpeta in carpetas:
    ruta_carpeta = os.path.join(ruta_origen, carpeta)
    archivos_mat = [x for x in os.listdir(ruta_carpeta) if x.endswith('.mat')]
    ruta_destino_carpeta = os.path.join(ruta_destino, f'{carpeta}_CSV')

    # Crear la carpeta de destino si no existe
    if not os.path.exists(ruta_destino_carpeta):
        os.makedirs(ruta_destino_carpeta)

    # Procesar cada archivo .mat en la carpeta y transformarlo a .csv
    num_archivos = 0
    for archivo in archivos_mat:
        ruta_origen_archivo = os.path.join(ruta_carpeta, archivo)
        data = scipy.io.loadmat(ruta_origen_archivo)
        sensor_readings = data['sensor_readings']
        subject = data['subject'][0]
        activity = data['activity'][0]
        trial = data['trial'][0]
        df = pd.DataFrame(sensor_readings, columns=['x_ace', 'y_ace', 'z_ace', 'x_giro', 'y_giro', 'z_giro'])
        df.insert(0, 'subject', subject)
        df.insert(1, 'activity', activity)
        df.insert(2, 'trial', trial)
        nombre_archivo = f'new_{archivo[:-4]}.csv'
        ruta_destino_archivo = os.path.join(ruta_destino_carpeta, nombre_archivo)
        df.to_csv(ruta_destino_archivo, index=False)
        num_archivos += 1

    print(f'Se crearon {num_archivos} archivos de {len(archivos_mat)} en la carpeta {carpeta}_CSV')

La carpeta Subject1 contiene 60 archivos .mat
La carpeta Subject10 contiene 60 archivos .mat
La carpeta Subject11 contiene 60 archivos .mat
La carpeta Subject6 contiene 60 archivos .mat
La carpeta Subject13 contiene 60 archivos .mat
La carpeta Subject5 contiene 60 archivos .mat
La carpeta Subject2 contiene 60 archivos .mat
La carpeta Subject3 contiene 60 archivos .mat
La carpeta Subject14 contiene 60 archivos .mat
La carpeta Subject4 contiene 60 archivos .mat
La carpeta Subject7 contiene 60 archivos .mat
La carpeta Subject12 contiene 60 archivos .mat
La carpeta Subject8 contiene 60 archivos .mat
La carpeta Subject9 contiene 60 archivos .mat
La carpeta Subject1_14_CSV contiene 0 archivos .mat
Se crearon 60 archivos de 60 en la carpeta Subject1_CSV
Se crearon 60 archivos de 60 en la carpeta Subject10_CSV
Se crearon 60 archivos de 60 en la carpeta Subject11_CSV
Se crearon 60 archivos de 60 en la carpeta Subject6_CSV

KeyError: ignored

Como se puede ver se crearon 60 nuevos arvhicos CSV a partir de los archivos .mat de cada una de las carpetas de los sujetos anteriores, a continuación se obtendrá un Dataset único por el USC_HAD_Dataset

In [ ]:
# Ruta donde se encuentran las carpetas Subject1, Subject2, ..., Subject14
folder_path = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject1_14_CSV/'

df_list = []

num_files = 0
num_rows = 0

# Iteramos sobre todas las carpetas de la ruta folder_path
for folder_name in os.listdir(folder_path):

    current_folder_path = os.path.join(folder_path, folder_name)

    if not os.path.isdir(current_folder_path):
        continue

    # Obtenemos los nombres de los archivos CSV en la carpeta
    files = os.listdir(current_folder_path)
    files = [f for f in files if f.endswith('.csv')]

    # Ignoramos la carpeta si no contiene archivos CSV
    if len(files) == 0:
        continue

    # Incrementamos el número total de archivos procesados
    num_files += len(files)

    temp_df_list = []

    # Iteramos sobre los archivos CSV de la carpeta actual
    for file in files:
        file_path = os.path.join(current_folder_path, file)
        temp_df = pd.read_csv(file_path, delimiter=';')
        temp_df_list.append(temp_df)

    # Concatenamos los DataFrames de la carpeta y los agregamos a la lista principal
    folder_df = pd.concat(temp_df_list, ignore_index=True)
    df_list.append(folder_df)
    print(f'{len(files)} archivos de la carpeta {folder_name} procesados exitosamente.')

# Concatenamos todos los DataFrames en uno solo
USC_HAD_Dataset = pd.concat(df_list, ignore_index=True)

# Guardamos el dataset completo como un archivo CSV
USC_HAD_Dataset.to_csv('/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_Dataset.csv', index=False)

print(f'Total de {num_files} archivos procesados y {len(USC_HAD_Dataset)} filas en el nuevo dataset.')

60 archivos de la carpeta Subject1_CSV procesados exitosamente.
60 archivos de la carpeta Subject10_CSV procesados exitosamente.
60 archivos de la carpeta Subject11_CSV procesados exitosamente.
60 archivos de la carpeta Subject6_CSV procesados exitosamente.
60 archivos de la carpeta Subject13_CSV procesados exitosamente.
60 archivos de la carpeta Subject5_CSV procesados exitosamente.
60 archivos de la carpeta Subject2_CSV procesados exitosamente.
60 archivos de la carpeta Subject3_CSV procesados exitosamente.
60 archivos de la carpeta Subject14_CSV procesados exitosamente.
60 archivos de la carpeta Subject4_CSV procesados exitosamente.
60 archivos de la carpeta Subject7_CSV procesados exitosamente.
60 archivos de la carpeta Subject12_CSV procesados exitosamente.
60 archivos de la carpeta Subject8_CSV procesados exitosamente.
60 archivos de la carpeta Subject9_CSV procesados exitosamente.
Total de 840 archivos procesados y 2811490 filas en el nuevo dataset.

In [ ]:
import re

source_dir = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/Subject1_14_CSV/'

dest_file = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAR_Definitivo_intento2.csv'

subject_dirs = [d for d in os.listdir(source_dir) if os.path.isdir(os.path.join(source_dir, d))]

# Ordenar los directorios de Subject en función del número
subject_dirs.sort(key=lambda d: int(re.search(r'\d+', d).group()))

dataframes = []

for dir in subject_dirs:

    dir_path = os.path.join(source_dir, dir)

    csv_files = [f for f in os.listdir(dir_path) if f.endswith('.csv')]

    # Ordenar los archivos CSV en función del número después de 'a' y luego después de 't'
    csv_files.sort(key=lambda f: (int(re.search(r'a(\d+)', f).group(1)), int(re.search(r't(\d+)', f).group(1))))

    # Recorrer cada archivo CSV y agregarlo a la lista de dataframes
    for file in csv_files:

        file_path = os.path.join(dir_path, file)

        # Leer el archivo CSV y agregarlo a la lista de dataframes
        df = pd.read_csv(file_path)
        dataframes.append(df)

# Concatenar todos los dataframes
result = pd.concat(dataframes)

# Escribir el dataframe resultante en el archivo de destino
result.to_csv(dest_file, index=False)

In [ ]:
prueba = "/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAR_Definitivo_intento2.csv"
pruebas = pd.read_csv(prueba)
pruebas

,subject,activity,trial,x_ace,y_ace,z_ace,x_giro,y_giro,z_giro
0,1,walking-forward,1,1.162780,-0.189287,-0.295781,-18.781324,3.361872,-16.863129
1,1,walking-forward,1,1.032296,-0.200145,-0.376304,-13.544509,5.778864,-14.446136
2,1,walking-forward,1,0.905245,-0.203764,-0.394605,-24.823805,6.987360,-21.697113
3,1,walking-forward,1,0.778195,-0.211002,-0.376304,-26.032301,11.821344,-21.697113
4,1,walking-forward,1,0.633975,-0.229098,-0.379964,-15.961501,15.446833,-7.597991
...,...,...,...,...,...,...,...,...,...
2811485,14,elevator-down,5,0.936149,0.364441,-0.017609,-0.143234,0.664059,-0.541099
2811486,14,elevator-down,5,0.939583,0.368060,-0.017609,-0.544398,-0.141163,0.263745
2811487,14,elevator-down,5,0.943017,0.368060,-0.017609,-0.542735,-0.140722,-0.540238
2811488,14,elevator-down,5,0.939583,0.368060,-0.017609,-0.541076,0.662866,-0.538562
2811489,14,elevator-down,5,0.939583,0.364441,-0.017609,0.263779,0.259223,-0.536891

A continuación se hace el ajuste del Dataset para que se pueda unir con los demás datasets que se han hecho.

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAR_Definitivo_intento2.csv")

df = df.rename(columns={
    'activity': 'Activity',
    'x_ace': 'X_Acc',
    'y_ace': 'Y_Acc',
    'z_ace': 'Z_Acc',
    'x_giro': 'X_Gyro',
    'y_giro': 'Y_Gyro',
    'z_giro': 'Z_Gyro',
    'subject': 'User',
    'trial': 'Trial'
})

df['Dataset'] = 3
df['X_Acc_6'] = np.nan
df['Y_Acc_6'] = np.nan
df['Z_Acc_6'] = np.nan
df['Code'] = '212'
df['TimesTamp'] = 10
df['Frequency'] = 100


df = df[['Dataset', 'Activity', 'X_Acc', 'Y_Acc', 'Z_Acc', 'X_Gyro', 'Y_Gyro', 'Z_Gyro', 'X_Acc_6', 'Y_Acc_6', 'Z_Acc_6', 'Code', 'TimesTamp', 'Frequency', 'User', 'Trial']]

df.to_csv('/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo.csv', index=False)

In [ ]:
source_file = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo.csv'
dest_file = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo_intento2.csv'

df = pd.read_csv(source_file)

# Convertir las columnas de aceleración de g a m/s²
df['X_Acc'] = df['X_Acc'] * 9.81
df['Y_Acc'] = df['Y_Acc'] * 9.81
df['Z_Acc'] = df['Z_Acc'] * 9.81

df.to_csv(dest_file, index=False)

In [ ]:
Prueba = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo_intento2.csv')
Prueba

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimesTamp,Frequency,User,Trial
0,3,walking-forward,11.406871,-1.856909,-2.901607,-18.781324,3.361872,-16.863129,NaN,NaN,NaN,212,10,100,1,1
1,3,walking-forward,10.126821,-1.963421,-3.691542,-13.544509,5.778864,-14.446136,NaN,NaN,NaN,212,10,100,1,1
2,3,walking-forward,8.880456,-1.998924,-3.871072,-24.823805,6.987360,-21.697113,NaN,NaN,NaN,212,10,100,1,1
3,3,walking-forward,7.634091,-2.069932,-3.691542,-26.032301,11.821344,-21.697113,NaN,NaN,NaN,212,10,100,1,1
4,3,walking-forward,6.219298,-2.247451,-3.727448,-15.961501,15.446833,-7.597991,NaN,NaN,NaN,212,10,100,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2811485,3,elevator-down,9.183626,3.575167,-0.172743,-0.143234,0.664059,-0.541099,NaN,NaN,NaN,212,10,100,14,5
2811486,3,elevator-down,9.217311,3.610670,-0.172743,-0.544398,-0.141163,0.263745,NaN,NaN,NaN,212,10,100,14,5
2811487,3,elevator-down,9.250997,3.610670,-0.172743,-0.542735,-0.140722,-0.540238,NaN,NaN,NaN,212,10,100,14,5
2811488,3,elevator-down,9.217311,3.610670,-0.172743,-0.541076,0.662866,-0.538562,NaN,NaN,NaN,212,10,100,14,5
2811489,3,elevator-down,9.217311,3.575167,-0.172743,0.263779,0.259223,-0.536891,NaN,NaN,NaN,212,10,100,14,5

In [ ]:
Prueba = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo_intento2.csv')

columns_to_drop = ["X_Acc_6", "Y_Acc_6", "Z_Acc_6"]
Prueba.drop(columns=columns_to_drop, inplace=True)

Prueba.to_csv('/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo_intento2.csv', index=False)

In [ ]:
Prueba.describe()

,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimesTamp,Frequency,User,Trial
count,2811490.0,2.811490e+06,2.811490e+06,2.811490e+06,2.811490e+06,2.811490e+06,2.811490e+06,2811490.0,2811490.0,2811490.0,2.811490e+06,2.811490e+06
mean,3.0,7.679263e+00,1.975112e+00,-6.073370e-01,-4.138871e-01,-3.517485e-01,-1.747959e-01,212.0,10.0,100.0,8.205919e+00,3.019252e+00
std,0.0,6.327050e+00,3.815964e+00,3.293107e+00,5.237366e+01,2.757491e+01,4.773775e+01,0.0,0.0,0.0,4.024173e+00,1.412155e+00
min,3.0,-3.288962e+01,-6.295888e+01,-5.313426e+01,-7.708486e+02,-7.754454e+02,-8.081837e+02,212.0,10.0,100.0,1.000000e+00,1.000000e+00
25%,3.0,6.050870e+00,-8.172114e-02,-2.398922e+00,-1.074605e+01,-6.752421e+00,-6.280653e+00,212.0,10.0,100.0,5.000000e+00,2.000000e+00
50%,3.0,8.644657e+00,2.261527e+00,-8.549587e-01,-5.208981e-02,-1.471133e-01,7.424915e-03,212.0,10.0,100.0,9.000000e+00,3.000000e+00
75%,3.0,9.621538e+00,4.249738e+00,1.083971e+00,9.589783e+00,4.131121e+00,7.904181e+00,212.0,10.0,100.0,1.200000e+01,4.000000e+00
max,3.0,6.799859e+01,4.855844e+01,4.453037e+01,8.563609e+02,5.596140e+02,8.165777e+02,212.0,10.0,100.0,1.400000e+01,5.000000e+00

In [ ]:
import pandas as pd
import json

resultado1 = Prueba.describe()

# Convertir el resultado en un diccionario
resultado_diccionario1 = resultado1.to_dict()


# Convertir el diccionario en una cadena JSON
json_string1 = json.dumps(resultado_diccionario1)

# Guardar la cadena JSON en un archivo .json
ruta_json1 = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo_intento2_Describe.json'

with open(ruta_json1, 'w') as archivo:
    archivo.write(json_string1)

## Actividades

In [ ]:
ruta = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo_intento2.csv'
dataset3 = pd.read_csv(ruta)
dataset3

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimesTamp,Frequency,User,Trial
0,3,walking-forward,11.406871,-1.856909,-2.901607,-18.781324,3.361872,-16.863129,212,10,100,1,1
1,3,walking-forward,10.126821,-1.963421,-3.691542,-13.544509,5.778864,-14.446136,212,10,100,1,1
2,3,walking-forward,8.880456,-1.998924,-3.871072,-24.823805,6.987360,-21.697113,212,10,100,1,1
3,3,walking-forward,7.634091,-2.069932,-3.691542,-26.032301,11.821344,-21.697113,212,10,100,1,1
4,3,walking-forward,6.219298,-2.247451,-3.727448,-15.961501,15.446833,-7.597991,212,10,100,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2811485,3,elevator-down,9.183626,3.575167,-0.172743,-0.143234,0.664059,-0.541099,212,10,100,14,5
2811486,3,elevator-down,9.217311,3.610670,-0.172743,-0.544398,-0.141163,0.263745,212,10,100,14,5
2811487,3,elevator-down,9.250997,3.610670,-0.172743,-0.542735,-0.140722,-0.540238,212,10,100,14,5
2811488,3,elevator-down,9.217311,3.610670,-0.172743,-0.541076,0.662866,-0.538562,212,10,100,14,5
2811489,3,elevator-down,9.217311,3.575167,-0.172743,0.263779,0.259223,-0.536891,212,10,100,14,5

In [ ]:
dataset3["Activity"].unique()

walking-forward
walking-left
walking-right
walking-upstairs
walking-downstairs
run
jump
sitting
standing
sleeping
elevator-up
elevator-down
walking-up
walking-down
sit
stand
walk-forward
walk-left
walk-right
walk-up
walk-upstairs
walk-downstairs
running
jumping

In [ ]:
activity_mapping = {
    'walking-forward': 6,
    'walking-left': 6,
    'walking-right': 6,
    'walking-upstairs': 13,
    'walking-downstairs': 14,
    'run': 15,
    'jump': 8,
    'sitting': 16,
    'standing': 17,
    'sleeping': 18,
    'elevator-up': 19,
    'elevator-down': 20,
    'walking-up': 6,
    'walking-down': 6,
    'sit': 16,
    'stand': 17,
    'walk-forward': 6,
    'walk-left': 6,
    'walk-right': 6,
    'walk-up': 6,
    'walk-upstairs': 13,
    'walk-downstairs': 14,
    'running': 15,
    'jumping': 8
}

ruta_entrada = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo_intento2.csv'
ruta_salida = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset3.csv'

data = pd.read_csv(ruta_entrada)

data['Activity'] = data['Activity'].map(activity_mapping)

data.to_csv(ruta_salida, index=False)

print("Proceso de remapeo completado y archivo guardado con éxito.")

Proceso de remapeo completado y archivo guardado con éxito.

In [ ]:
dataset3 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset3.csv')
dataset3

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimesTamp,Frequency,User,Trial
0,3,6,11.406871,-1.856909,-2.901607,-18.781324,3.361872,-16.863129,212,10,100,1,1
1,3,6,10.126821,-1.963421,-3.691542,-13.544509,5.778864,-14.446136,212,10,100,1,1
2,3,6,8.880456,-1.998924,-3.871072,-24.823805,6.987360,-21.697113,212,10,100,1,1
3,3,6,7.634091,-2.069932,-3.691542,-26.032301,11.821344,-21.697113,212,10,100,1,1
4,3,6,6.219298,-2.247451,-3.727448,-15.961501,15.446833,-7.597991,212,10,100,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2811485,3,20,9.183626,3.575167,-0.172743,-0.143234,0.664059,-0.541099,212,10,100,14,5
2811486,3,20,9.217311,3.610670,-0.172743,-0.544398,-0.141163,0.263745,212,10,100,14,5
2811487,3,20,9.250997,3.610670,-0.172743,-0.542735,-0.140722,-0.540238,212,10,100,14,5
2811488,3,20,9.217311,3.610670,-0.172743,-0.541076,0.662866,-0.538562,212,10,100,14,5
2811489,3,20,9.217311,3.575167,-0.172743,0.263779,0.259223,-0.536891,212,10,100,14,5

## Resampling

In [ ]:
dataset3 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset3.csv')
dataset3

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimesTamp,Frequency,User,Trial
0,3,6,11.406871,-1.856909,-2.901607,-18.781324,3.361872,-16.863129,212,10,100,1,1
1,3,6,10.126821,-1.963421,-3.691542,-13.544509,5.778864,-14.446136,212,10,100,1,1
2,3,6,8.880456,-1.998924,-3.871072,-24.823805,6.987360,-21.697113,212,10,100,1,1
3,3,6,7.634091,-2.069932,-3.691542,-26.032301,11.821344,-21.697113,212,10,100,1,1
4,3,6,6.219298,-2.247451,-3.727448,-15.961501,15.446833,-7.597991,212,10,100,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2811485,3,20,9.183626,3.575167,-0.172743,-0.143234,0.664059,-0.541099,212,10,100,14,5
2811486,3,20,9.217311,3.610670,-0.172743,-0.544398,-0.141163,0.263745,212,10,100,14,5
2811487,3,20,9.250997,3.610670,-0.172743,-0.542735,-0.140722,-0.540238,212,10,100,14,5
2811488,3,20,9.217311,3.610670,-0.172743,-0.541076,0.662866,-0.538562,212,10,100,14,5
2811489,3,20,9.217311,3.575167,-0.172743,0.263779,0.259223,-0.536891,212,10,100,14,5

In [ ]:
dataset3Final = resample_dataframe(dataset3)

In [ ]:
dataset3Final

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimesTamp,Frequency,User,Trial
0,3,6,11.406871,-1.856909,-2.901607,-18.781324,3.361872,-16.863129,212,10,50,1,1
3,3,6,7.634091,-2.069932,-3.691542,-26.032301,11.821344,-21.697113,212,10,50,1,1
4,3,6,6.219298,-2.247451,-3.727448,-15.961501,15.446833,-7.597991,212,10,50,1,1
7,3,6,5.781386,-1.892413,-4.912349,4.180100,15.849665,59.674957,212,10,50,1,1
8,3,6,7.196179,-1.217842,-5.091880,-3.070876,19.475153,71.357086,212,10,50,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2811484,3,20,9.183626,3.575167,-0.172743,-0.143673,0.263306,-0.139950,212,10,50,14,5
2811486,3,20,9.217311,3.610670,-0.172743,-0.544398,-0.141163,0.263745,212,10,50,14,5
2811487,3,20,9.250997,3.610670,-0.172743,-0.542735,-0.140722,-0.540238,212,10,50,14,5
2811488,3,20,9.217311,3.610670,-0.172743,-0.541076,0.662866,-0.538562,212,10,50,14,5
2811489,3,20,9.217311,3.575167,-0.172743,0.263779,0.259223,-0.536891,212,10,50,14,5

In [ ]:
dataset3Final.to_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset3.csv', index=False)

## Análisis Gráfico Dataset 3

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset3.csv')

###Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(df)

### Valores Máximo y Mínimos Acelerometro

In [ ]:
grafico_acelerometro_max_min(df)

### Valores Válidos Giroscopio

In [ ]:

grafico_giroscopio_valido(df)

###Valores Máximo y Mínimos Giroscopio

In [ ]:
grafico_giroscopio_max_min(df)

###Actividades Válidas

In [ ]:
grafico_activity(df)

## Describe

In [ ]:
ruta_antes = '/content/drive/MyDrive/TESIS_DATASET/3_The_USC_SIPI_Human_Activiry_Dataset/USC-HAD/USC_HAD_DATASET_Final_Definitivo_intento2.csv'
ruta_despues = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset3.csv'
dataset3_antes = pd.read_csv(ruta_antes)
dataset3_despues = pd.read_csv(ruta_despues)

### Describe Antes

In [ ]:
dataset3_antes.describe()

,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimesTamp,Frequency,User,Trial
count,2811490.0,2.811490e+06,2.811490e+06,2.811490e+06,2.811490e+06,2.811490e+06,2.811490e+06,2811490.0,2811490.0,2811490.0,2.811490e+06,2.811490e+06
mean,3.0,7.679263e+00,1.975112e+00,-6.073370e-01,-4.138871e-01,-3.517485e-01,-1.747959e-01,212.0,10.0,100.0,8.205919e+00,3.019252e+00
std,0.0,6.327050e+00,3.815964e+00,3.293107e+00,5.237366e+01,2.757491e+01,4.773775e+01,0.0,0.0,0.0,4.024173e+00,1.412155e+00
min,3.0,-3.288962e+01,-6.295888e+01,-5.313426e+01,-7.708486e+02,-7.754454e+02,-8.081837e+02,212.0,10.0,100.0,1.000000e+00,1.000000e+00
25%,3.0,6.050870e+00,-8.172114e-02,-2.398922e+00,-1.074605e+01,-6.752421e+00,-6.280653e+00,212.0,10.0,100.0,5.000000e+00,2.000000e+00
50%,3.0,8.644657e+00,2.261527e+00,-8.549587e-01,-5.208981e-02,-1.471133e-01,7.424915e-03,212.0,10.0,100.0,9.000000e+00,3.000000e+00
75%,3.0,9.621538e+00,4.249738e+00,1.083971e+00,9.589783e+00,4.131121e+00,7.904181e+00,212.0,10.0,100.0,1.200000e+01,4.000000e+00
max,3.0,6.799859e+01,4.855844e+01,4.453037e+01,8.563609e+02,5.596140e+02,8.165777e+02,212.0,10.0,100.0,1.400000e+01,5.000000e+00

### Describe Después

In [ ]:
dataset3_despues.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimesTamp,Frequency,User,Trial
count,1405745.0,1.405745e+06,1.405745e+06,1.405745e+06,1.405745e+06,1.405745e+06,1.405745e+06,1.405745e+06,1405745.0,1405745.0,1405745.0,1.405745e+06,1.405745e+06
mean,3.0,1.262396e+01,7.679029e+00,1.974493e+00,-6.060395e-01,-4.529186e-01,-3.625048e-01,-1.922221e-01,212.0,10.0,50.0,8.209410e+00,3.019398e+00
std,0.0,5.342374e+00,6.321889e+00,3.815286e+00,3.289886e+00,5.239233e+01,2.750565e+01,4.763415e+01,0.0,0.0,0.0,4.023418e+00,1.412469e+00
min,3.0,6.000000e+00,-3.288962e+01,-6.189377e+01,-4.893324e+01,-7.684316e+02,-7.754454e+02,-8.047173e+02,212.0,10.0,50.0,1.000000e+00,1.000000e+00
25%,3.0,6.000000e+00,6.050870e+00,-8.172114e-02,-2.398922e+00,-1.076114e+01,-6.751668e+00,-6.293229e+00,212.0,10.0,50.0,5.000000e+00,2.000000e+00
50%,3.0,1.400000e+01,8.644657e+00,2.297031e+00,-8.549587e-01,-5.429714e-02,-1.482508e-01,7.217583e-03,212.0,10.0,50.0,9.000000e+00,3.000000e+00
75%,3.0,1.800000e+01,9.621538e+00,4.249738e+00,1.083971e+00,9.487876e+00,4.093040e+00,7.861037e+00,212.0,10.0,50.0,1.200000e+01,4.000000e+00
max,3.0,2.000000e+01,6.799859e+01,4.855844e+01,4.201694e+01,8.563609e+02,5.560552e+02,8.165777e+02,212.0,10.0,50.0,1.400000e+01,5.000000e+00

# Dataset Número 4. WISDM_Wireless_Sensor_Data_Mining

## Preparación del Dataset Número 4

In [ ]:
WISDM_ar_v1_raw_txt = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_ar_v1.1_raw.txt'
WISDM_ar_v1_transformed_arff = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_ar_v1.1_transformed.arff'

Primero se va a trabajar con el archivo TXT, que se visualizará y después se pasará a formato CSV, para poder trabajarlo como los demás archivos de este proyecto de Preparación de datos, así mismo, se conoce con anterioridad gracias a la documentación de WISDM: https://www.cis.fordham.edu/wisdm/dataset.php que los archivos txt manejan los siguientes nombres de las columnas: 'user_id', 'activity', 'timestamp', 'x_accel', 'y_accel', 'z_accel', los cuales se tendrán en cuenta para el procesamiento de estos datos.

In [ ]:
WISDM_ar_v1_raw = pd.read_csv(WISDM_ar_v1_raw_txt, header=None, names=['user_id', 'activity', 'timestamp', 'x_accel', 'y_accel', 'z_accel'])

WISDM_ar_v1_raw

         user_id activity        timestamp   x_accel    y_accel       z_accel
0             33  Jogging   49105962326000 -0.694638  12.680544   0.50395286;
1             33  Jogging   49106062271000  5.012288  11.264028   0.95342433;
2             33  Jogging   49106112167000  4.903325  10.882658  -0.08172209;
3             33  Jogging   49106222305000 -0.612916  18.496431    3.0237172;
4             33  Jogging   49106332290000 -1.184970  12.108489     7.205164;
...          ...      ...              ...       ...        ...           ...
1098199       19  Sitting  131623331483000  9.000000  -1.570000         1.69;
1098200       19  Sitting  131623371431000  9.040000  -1.460000         1.73;
1098201       19  Sitting  131623411592000  9.080000  -1.380000         1.69;
1098202       19  Sitting  131623491487000  9.000000  -1.460000         1.73;
1098203       19  Sitting  131623531465000  8.880000  -1.330000         1.61;

[1098204 rows x 6 columns]

Ahora se va a convertir en un archivo CSV.

In [ ]:
Ruta_Destino = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/new_WISDM_ar_raw.csv'
WISDM_ar_v1_raw.to_csv(Ruta_Destino, index=False)
new_WISDM_ar_v1_raw = pd.read_csv(Ruta_Destino)
new_WISDM_ar_v1_raw

         user_id activity        timestamp   x_accel    y_accel       z_accel
0             33  Jogging   49105962326000 -0.694638  12.680544   0.50395286;
1             33  Jogging   49106062271000  5.012288  11.264028   0.95342433;
2             33  Jogging   49106112167000  4.903325  10.882658  -0.08172209;
3             33  Jogging   49106222305000 -0.612916  18.496431    3.0237172;
4             33  Jogging   49106332290000 -1.184970  12.108489     7.205164;
...          ...      ...              ...       ...        ...           ...
1098199       19  Sitting  131623331483000  9.000000  -1.570000         1.69;
1098200       19  Sitting  131623371431000  9.040000  -1.460000         1.73;
1098201       19  Sitting  131623411592000  9.080000  -1.380000         1.69;
1098202       19  Sitting  131623491487000  9.000000  -1.460000         1.73;
1098203       19  Sitting  131623531465000  8.880000  -1.330000         1.61;

[1098204 rows x 6 columns]

Ahora se va a hacer el procedimiento para el archivo .ARFF, primero se hará la visualización y posterior a ello, se hará la conversión a archivo CSV. Para poder realizar esto, previamente se tuvo que instalar la librearía liac-arff, para poder hacer uso de la librería arff de python.

In [ ]:
Ruta_Origen_ARFF = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_ar_v1.1_transformed.arff'

WISDM_ar_v1_transformed_ARFF = pd.read_csv(Ruta_Origen_ARFF, comment='@', delimiter=",")
WISDM_ar_v1_transformed_ARFF

,1,33,0.04,0.09,0.14,0.12,0.11,0.1,0.08,0.13,...,293.94,1550,3.29,7.21,4,4.05,8.17,4.05.1,11.96,Jogging
0,2,33,0.12,0.12,0.06,0.07,0.11,0.10,0.11,0.09,...,269.44,1233.33,4.23,6.88,4.05,5.43,8.19,5.43,12.05,Jogging
1,3,33,0.14,0.09,0.11,0.09,0.09,0.11,0.12,0.08,...,248.65,1780,4.18,6.89,4.07,5.55,8.19,5.55,11.99,Jogging
2,4,33,0.06,0.10,0.09,0.09,0.11,0.07,0.12,0.10,...,709.09,1380,2.26,4.13,2.49,2.87,4.95,2.87,10.69,Walking
3,5,33,0.12,0.11,0.10,0.08,0.10,0.14,0.10,0.11,...,3300,1775,2.29,3.94,2.41,3.08,4.64,3.08,10.80,Walking
4,6,33,0.09,0.09,0.10,0.12,0.08,0.06,0.09,0.08,...,1337.5,2675,2.00,3.39,1.94,3.13,4.95,3.13,8.63,Walking
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5412,382,19,0.18,0.17,0.00,0.00,0.28,0.00,0.00,0.00,...,?,208.33,8.91,0.15,0.16,8.91,0.17,8.91,9.28,Sitting
5413,383,19,0.11,0.15,0.00,0.00,0.34,0.00,0.00,0.00,...,?,361.11,8.95,0.11,0.14,8.95,0.14,8.95,9.30,Sitting
5414,384,19,0.18,0.07,0.00,0.00,0.22,0.00,0.00,0.00,...,?,287.5,8.96,0.19,0.19,8.97,0.23,8.97,9.28,Sitting
5415,385,19,0.17,0.25,0.00,0.00,0.23,0.00,0.00,0.00,...,?,1233.33,8.95,0.17,0.33,8.96,0.30,8.96,9.28,Sitting
5416,386,19,0.05,0.08,0.00,0.00,0.09,0.00,0.00,0.00,...,?,266.67,2.36,0.25,0.44,8.90,0.96,8.90,2.46,Sitting

Como se puede observar en el anterior código, no se esta trabajando la data decuadamente, porque hace falta los nombres de las columnas que son la información de los atributos en el siguiente código ya se tiene en cuenta el Header, con los atributos que se obtuvieron abriendo el archivo con el NotePad++

In [ ]:

with open(Ruta_Origen_ARFF) as f:
    lines = f.readlines()

# Encontrar la línea que contiene "@data"
data_line_index = None
for i, line in enumerate(lines):
    if line.startswith('@data'):
        data_line_index = i
        break

# Leer el archivo ARFF a un DataFrame de Pandas, saltándose las líneas antes de "@data"
WISDM_ar_v1_transformed_ARFF = pd.read_csv(
    Ruta_Origen_ARFF,
    skiprows=data_line_index + 1,  # Iniciar desde la línea siguiente de "@data"
    header=None,  # No hay encabezados en el archivo
    names=[
        "UNIQUE_ID",
        "user",
        "X0",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "X8",
        "X9",
        "Y0",
        "Y1",
        "Y2",
        "Y3",
        "Y4",
        "Y5",
        "Y6",
        "Y7",
        "Y8",
        "Y9",
        "Z0",
        "Z1",
        "Z2",
        "Z3",
        "Z4",
        "Z5",
        "Z6",
        "Z7",
        "Z8",
        "Z9",
        "XAVG",
        "YAVG",
        "ZAVG",
        "XPEAK",
        "YPEAK",
        "ZPEAK",
        "XABSOLDEV",
        "YABSOLDEV",
        "ZABSOLDEV",
        "XSTANDDEV",
        "YSTANDDEV",
        "ZSTANDDEV",
        "RESULTANT",
        "Activity"
    ],
    na_values=['?']  # Marcar los valores desconocidos como NaN
)

WISDM_ar_v1_transformed_ARFF

,UNIQUE_ID,user,X0,X1,X2,X3,X4,X5,X6,X7,...,YPEAK,ZPEAK,XABSOLDEV,YABSOLDEV,ZABSOLDEV,XSTANDDEV,YSTANDDEV,ZSTANDDEV,RESULTANT,Activity
0,1,33,0.04,0.09,0.14,0.12,0.11,0.10,0.08,0.13,...,293.94,1550.00,3.29,7.21,4.00,4.05,8.17,4.05,11.96,Jogging
1,2,33,0.12,0.12,0.06,0.07,0.11,0.10,0.11,0.09,...,269.44,1233.33,4.23,6.88,4.05,5.43,8.19,5.43,12.05,Jogging
2,3,33,0.14,0.09,0.11,0.09,0.09,0.11,0.12,0.08,...,248.65,1780.00,4.18,6.89,4.07,5.55,8.19,5.55,11.99,Jogging
3,4,33,0.06,0.10,0.09,0.09,0.11,0.07,0.12,0.10,...,709.09,1380.00,2.26,4.13,2.49,2.87,4.95,2.87,10.69,Walking
4,5,33,0.12,0.11,0.10,0.08,0.10,0.14,0.10,0.11,...,3300.00,1775.00,2.29,3.94,2.41,3.08,4.64,3.08,10.80,Walking
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5413,382,19,0.18,0.17,0.00,0.00,0.28,0.00,0.00,0.00,...,NaN,208.33,8.91,0.15,0.16,8.91,0.17,8.91,9.28,Sitting
5414,383,19,0.11,0.15,0.00,0.00,0.34,0.00,0.00,0.00,...,NaN,361.11,8.95,0.11,0.14,8.95,0.14,8.95,9.30,Sitting
5415,384,19,0.18,0.07,0.00,0.00,0.22,0.00,0.00,0.00,...,NaN,287.50,8.96,0.19,0.19,8.97,0.23,8.97,9.28,Sitting
5416,385,19,0.17,0.25,0.00,0.00,0.23,0.00,0.00,0.00,...,NaN,1233.33,8.95,0.17,0.33,8.96,0.30,8.96,9.28,Sitting
5417,386,19,0.05,0.08,0.00,0.00,0.09,0.00,0.00,0.00,...,NaN,266.67,2.36,0.25,0.44,8.90,0.96,8.90,2.46,Sitting

Lo siguiente es convertir ese archivo a CSV.

In [ ]:
Ruta_Destino = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/new_WISDM_ar_transformed.csv'
WISDM_ar_v1_transformed_ARFF.to_csv(Ruta_Destino, index=False)

new_WISDM_ar_1_transformed = pd.read_csv(Ruta_Destino)

'/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/new_WISDM_ar_transformed.csv'

In [ ]:
new_WISDM_ar_1_transformed

,UNIQUE_ID,user,X0,X1,X2,X3,X4,X5,X6,X7,...,YPEAK,ZPEAK,XABSOLDEV,YABSOLDEV,ZABSOLDEV,XSTANDDEV,YSTANDDEV,ZSTANDDEV,RESULTANT,Activity
0,1,33,0.04,0.09,0.14,0.12,0.11,0.10,0.08,0.13,...,293.94,1550.00,3.29,7.21,4.00,4.05,8.17,4.05,11.96,Jogging
1,2,33,0.12,0.12,0.06,0.07,0.11,0.10,0.11,0.09,...,269.44,1233.33,4.23,6.88,4.05,5.43,8.19,5.43,12.05,Jogging
2,3,33,0.14,0.09,0.11,0.09,0.09,0.11,0.12,0.08,...,248.65,1780.00,4.18,6.89,4.07,5.55,8.19,5.55,11.99,Jogging
3,4,33,0.06,0.10,0.09,0.09,0.11,0.07,0.12,0.10,...,709.09,1380.00,2.26,4.13,2.49,2.87,4.95,2.87,10.69,Walking
4,5,33,0.12,0.11,0.10,0.08,0.10,0.14,0.10,0.11,...,3300.00,1775.00,2.29,3.94,2.41,3.08,4.64,3.08,10.80,Walking
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5413,382,19,0.18,0.17,0.00,0.00,0.28,0.00,0.00,0.00,...,NaN,208.33,8.91,0.15,0.16,8.91,0.17,8.91,9.28,Sitting
5414,383,19,0.11,0.15,0.00,0.00,0.34,0.00,0.00,0.00,...,NaN,361.11,8.95,0.11,0.14,8.95,0.14,8.95,9.30,Sitting
5415,384,19,0.18,0.07,0.00,0.00,0.22,0.00,0.00,0.00,...,NaN,287.50,8.96,0.19,0.19,8.97,0.23,8.97,9.28,Sitting
5416,385,19,0.17,0.25,0.00,0.00,0.23,0.00,0.00,0.00,...,NaN,1233.33,8.95,0.17,0.33,8.96,0.30,8.96,9.28,Sitting
5417,386,19,0.05,0.08,0.00,0.00,0.09,0.00,0.00,0.00,...,NaN,266.67,2.36,0.25,0.44,8.90,0.96,8.90,2.46,Sitting

Concluyendo este Dataset, se tiene dos archivos resultantes ahora en formato CSV, se tiene new_WISDM_ar_raw y también así mismo new_WISDM_ar_transformed. No obstante, para el interés de este estudio se requiere simplemente el primer archivo de la data en crudo, sin ninguna transformada, la cual tendrá la estructura que se maneja en el Header para los demás archivos.

In [ ]:
ruta_origen = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/new_WISDM_ar_raw.csv'

df = pd.read_csv(ruta_origen)

df = df.rename(columns={
    'activity': 'Activity',
    'x_accel': 'X_Acc',
    'y_accel': 'Y_Acc',
    'z_accel': 'Z_Acc',
    'user_id': 'User',
    'timestamp': 'TimesTamp'
})

df['Dataset'] = 4
df['X_Gyro'] = np.nan
df['Y_Gyro'] = np.nan
df['Z_Gyro'] = np.nan
df['X_Acc_6'] = np.nan
df['Y_Acc_6'] = np.nan
df['Z_Acc_6'] = np.nan
df['Code'] = '011'
df['Frequency'] = 20
df['Trial'] = np.nan

df = df[['Dataset', 'Activity', 'X_Acc', 'Y_Acc', 'Z_Acc', 'X_Gyro', 'Y_Gyro', 'Z_Gyro', 'X_Acc_6', 'Y_Acc_6', 'Z_Acc_6', 'Code', 'TimesTamp', 'Frequency', 'User', 'Trial']]

ruta_destino = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv'

df.to_csv(ruta_destino, index=False)

In [ ]:
#Visualización Dataset Final
Ruta = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv'
WISDM_DATASET = pd.read_csv(Ruta)
WISDM_DATASET=df
df['Z_Acc'] = df['Z_Acc'].str.replace(';', '')
df.to_csv('/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv', index=False)

In [ ]:
source_file = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv'

df = pd.read_csv(source_file)

df = df.drop('Code',axis=1)
df['Code'] = 311
df['Code'] = df['Code'].astype(str)

df['Code'] = df['Code'].replace('311','011')

In [ ]:
df['TimesTamp'] = pd.to_datetime(df['TimesTamp'] +  1262304000000000000, unit='ns')

df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,TimesTamp,Frequency,User,Trial,Code
0,4,Jogging,-6.814396,124.396137,4.943778,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-01 13:38:25.962326,20,33,NaN,011
1,4,Jogging,49.170545,110.500115,9.353093,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-01 13:38:26.062271,20,33,NaN,011
2,4,Jogging,48.101618,106.758875,-0.801694,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-01 13:38:26.112167,20,33,NaN,011
3,4,Jogging,-6.012702,181.449988,29.662666,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-01 13:38:26.222305,20,33,NaN,011
4,4,Jogging,-11.624559,118.784277,70.682659,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-01 13:38:26.332290,20,33,NaN,011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098199,4,Sitting,88.290000,-15.401700,16.578900,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-02 12:33:43.331483,20,19,NaN,011
1098200,4,Sitting,88.682400,-14.322600,16.971300,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-02 12:33:43.371431,20,19,NaN,011
1098201,4,Sitting,89.074800,-13.537800,16.578900,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-02 12:33:43.411592,20,19,NaN,011
1098202,4,Sitting,88.290000,-14.322600,16.971300,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-02 12:33:43.491487,20,19,NaN,011
1098203,4,Sitting,87.112800,-13.047300,15.794100,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-02 12:33:43.531465,20,19,NaN,011

In [ ]:
df.to_csv('/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv', index=False)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv')

columns_to_drop = ["X_Acc_6", "Y_Acc_6", "Z_Acc_6"]
df.drop(columns=columns_to_drop, inplace=True)

df.to_csv('/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv', index=False)

In [ ]:
df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,TimesTamp,Frequency,User,Trial,Code
0,4,Jogging,-6.814396,124.396137,4.943778,NaN,NaN,NaN,2010-01-01 13:38:25.962326,20,33,NaN,11
1,4,Jogging,49.170545,110.500115,9.353093,NaN,NaN,NaN,2010-01-01 13:38:26.062271,20,33,NaN,11
2,4,Jogging,48.101618,106.758875,-0.801694,NaN,NaN,NaN,2010-01-01 13:38:26.112167,20,33,NaN,11
3,4,Jogging,-6.012702,181.449988,29.662666,NaN,NaN,NaN,2010-01-01 13:38:26.222305,20,33,NaN,11
4,4,Jogging,-11.624559,118.784277,70.682659,NaN,NaN,NaN,2010-01-01 13:38:26.332290,20,33,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098199,4,Sitting,88.290000,-15.401700,16.578900,NaN,NaN,NaN,2010-01-02 12:33:43.331483,20,19,NaN,11
1098200,4,Sitting,88.682400,-14.322600,16.971300,NaN,NaN,NaN,2010-01-02 12:33:43.371431,20,19,NaN,11
1098201,4,Sitting,89.074800,-13.537800,16.578900,NaN,NaN,NaN,2010-01-02 12:33:43.411592,20,19,NaN,11
1098202,4,Sitting,88.290000,-14.322600,16.971300,NaN,NaN,NaN,2010-01-02 12:33:43.491487,20,19,NaN,11
1098203,4,Sitting,87.112800,-13.047300,15.794100,NaN,NaN,NaN,2010-01-02 12:33:43.531465,20,19,NaN,11

In [ ]:
df.describe()

,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Frequency,User,Trial,Code
count,1098204.0,1.098204e+06,1.098204e+06,1.098203e+06,0.0,0.0,0.0,1098204.0,1.098204e+06,0.0,1098204.0
mean,4.0,6.502735e+00,7.117782e+01,4.032515e+00,NaN,NaN,NaN,20.0,1.886066e+01,NaN,11.0
std,0.0,6.718926e+01,6.618026e+01,4.663781e+01,NaN,NaN,NaN,0.0,1.021423e+01,NaN,0.0
min,4.0,-1.923741e+02,-1.923741e+02,-1.942380e+02,NaN,NaN,NaN,20.0,1.000000e+00,NaN,11.0
25%,4.0,-2.815470e+01,3.109770e+01,-2.177820e+01,NaN,NaN,NaN,20.0,1.000000e+01,NaN,11.0
50%,4.0,2.648700e+00,7.779330e+01,0.000000e+00,NaN,NaN,NaN,20.0,1.900000e+01,NaN,11.0
75%,4.0,4.355640e+01,1.134036e+02,2.668320e+01,NaN,NaN,NaN,20.0,2.800000e+01,NaN,11.0
max,4.0,1.957095e+02,1.965924e+02,1.923741e+02,NaN,NaN,NaN,20.0,3.600000e+01,NaN,11.0

In [ ]:
import pandas as pd
import json

resultado1 = df.describe()

# Convertir el resultado en un diccionario
resultado_diccionario1 = resultado1.to_dict()


# Convertir el diccionario en una cadena JSON
json_string1 = json.dumps(resultado_diccionario1)

# Guardar la cadena JSON en un archivo .json
ruta_json1 = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV_describe.json'

with open(ruta_json1, 'w') as archivo:
    archivo.write(json_string1)

## Actividades

In [ ]:
dataset4 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv')
dataset4

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,TimesTamp,Frequency,User,Trial,Code
0,4,Jogging,-6.81,124.40,4.94,NaN,NaN,NaN,2010-01-01 13:38:25.962326,20,33,NaN,11
1,4,Jogging,49.17,110.50,9.35,NaN,NaN,NaN,2010-01-01 13:38:26.062271,20,33,NaN,11
2,4,Jogging,48.10,106.76,-0.80,NaN,NaN,NaN,2010-01-01 13:38:26.112167,20,33,NaN,11
3,4,Jogging,-6.01,181.45,29.66,NaN,NaN,NaN,2010-01-01 13:38:26.222305,20,33,NaN,11
4,4,Jogging,-11.62,118.78,70.68,NaN,NaN,NaN,2010-01-01 13:38:26.332290,20,33,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098199,4,Sitting,88.29,-15.40,16.58,NaN,NaN,NaN,2010-01-02 12:33:43.331483,20,19,NaN,11
1098200,4,Sitting,88.68,-14.32,16.97,NaN,NaN,NaN,2010-01-02 12:33:43.371431,20,19,NaN,11
1098201,4,Sitting,89.07,-13.54,16.58,NaN,NaN,NaN,2010-01-02 12:33:43.411592,20,19,NaN,11
1098202,4,Sitting,88.29,-14.32,16.97,NaN,NaN,NaN,2010-01-02 12:33:43.491487,20,19,NaN,11
1098203,4,Sitting,87.11,-13.05,15.79,NaN,NaN,NaN,2010-01-02 12:33:43.531465,20,19,NaN,11

In [ ]:
dataset4["Activity"].unique()

Jogging
Walking
Upstairs
Downstairs
Sitting
Standing

In [ ]:
mapping = {
    'Jogging': 9,
    'Walking': 6,
    'Upstairs': 13,
    'Downstairs': 14,
    'Sitting': 16,
    'Standing': 17
}

data = dataset4.copy()

data['Activity'] = data['Activity'].map(mapping)

In [ ]:
data

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,TimesTamp,Frequency,User,Trial,Code
0,4,9,-6.81,124.40,4.94,NaN,NaN,NaN,2010-01-01 13:38:25.962326,20,33,NaN,11
1,4,9,49.17,110.50,9.35,NaN,NaN,NaN,2010-01-01 13:38:26.062271,20,33,NaN,11
2,4,9,48.10,106.76,-0.80,NaN,NaN,NaN,2010-01-01 13:38:26.112167,20,33,NaN,11
3,4,9,-6.01,181.45,29.66,NaN,NaN,NaN,2010-01-01 13:38:26.222305,20,33,NaN,11
4,4,9,-11.62,118.78,70.68,NaN,NaN,NaN,2010-01-01 13:38:26.332290,20,33,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098199,4,16,88.29,-15.40,16.58,NaN,NaN,NaN,2010-01-02 12:33:43.331483,20,19,NaN,11
1098200,4,16,88.68,-14.32,16.97,NaN,NaN,NaN,2010-01-02 12:33:43.371431,20,19,NaN,11
1098201,4,16,89.07,-13.54,16.58,NaN,NaN,NaN,2010-01-02 12:33:43.411592,20,19,NaN,11
1098202,4,16,88.29,-14.32,16.97,NaN,NaN,NaN,2010-01-02 12:33:43.491487,20,19,NaN,11
1098203,4,16,87.11,-13.05,15.79,NaN,NaN,NaN,2010-01-02 12:33:43.531465,20,19,NaN,11

## Resampling

In [ ]:
dataset4Final = resample_dataframe(data)
dataset4Final

In [ ]:
pd.set_option('display.float_format', '{:.4f}'.format)
dataset4Final

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,TimesTamp,Frequency,User,Trial,Code
0,4,6,6.7689,105.9480,-19.9143,NaN,NaN,NaN,2010-01-01 01:23:11.922345,50,1,NaN,11
1,4,6,6.7689,105.9480,-19.9143,NaN,NaN,NaN,2010-01-01 01:23:11.922345,50,1,NaN,11
2,4,6,67.1985,72.9864,-4.9050,NaN,NaN,NaN,2010-01-01 01:23:11.972333,50,1,NaN,11
3,4,6,67.1985,72.9864,-4.9050,NaN,NaN,NaN,2010-01-01 01:23:11.972333,50,1,NaN,11
4,4,6,67.1985,72.9864,-4.9050,NaN,NaN,NaN,2010-01-01 01:23:11.972333,50,1,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2745496,4,17,-20.3067,86.0337,21.3785,NaN,NaN,NaN,2010-01-01 04:10:49.162275,50,36,NaN,11
2745497,4,17,-20.3067,86.0337,21.3785,NaN,NaN,NaN,2010-01-01 04:10:49.162275,50,36,NaN,11
2745498,4,17,-20.3067,86.0337,21.3785,NaN,NaN,NaN,2010-01-01 04:10:49.162275,50,36,NaN,11
2745499,4,17,-20.9934,97.0209,31.9341,NaN,NaN,NaN,2010-01-01 04:10:49.212262,50,36,NaN,11
2745500,4,17,-20.9934,97.0209,31.9341,NaN,NaN,NaN,2010-01-01 04:10:49.212262,50,36,NaN,11

In [ ]:
dataset4Final.to_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset4.csv', index=False)

## Análisis Gráfico Dataset 4

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset4.csv')

###Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(df)

### Valores Máximo y Mínimos Acelerometro

In [ ]:
grafico_acelerometro_max_min(df)

### Valores Válidos Giroscopio

In [ ]:
grafico_giroscopio_valido(df)

###Valores Máximo y Mínimos Giroscopio

In [ ]:
grafico_giroscopio_max_min(df)

###Actividades Válidas

In [ ]:
grafico_activity(df)

## Describe

In [ ]:
ruta_entrada = '/content/drive/MyDrive/TESIS_DATASET/4_WISDM_Wireless_Sensor_Data_Mining/WISDM_ar_v1.1/WISDM_CSV.csv'
ruta_salida = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset4.csv'
dataset4_antes = pd.read_csv(ruta_entrada)
dataset4_despues = pd.read_csv(ruta_salida)

### Describe Antes

In [ ]:
data.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Frequency,User,Trial,Code
count,1098204.0000,1098204.0000,1098204.0000,1098204.0000,1098203.0000,0.0000,0.0000,0.0000,1098204.0000,1098204.0000,0.0000,1098204.0000
mean,4.0000,9.4800,6.5027,71.1778,4.0325,NaN,NaN,NaN,20.0000,18.8607,NaN,11.0000
std,0.0000,3.5803,67.1893,66.1803,46.6378,NaN,NaN,NaN,0.0000,10.2142,NaN,0.0000
min,4.0000,6.0000,-192.3741,-192.3741,-194.2380,NaN,NaN,NaN,20.0000,1.0000,NaN,11.0000
25%,4.0000,6.0000,-28.1547,31.0977,-21.7782,NaN,NaN,NaN,20.0000,10.0000,NaN,11.0000
50%,4.0000,9.0000,2.6487,77.7933,0.0000,NaN,NaN,NaN,20.0000,19.0000,NaN,11.0000
75%,4.0000,13.0000,43.5564,113.4036,26.6832,NaN,NaN,NaN,20.0000,28.0000,NaN,11.0000
max,4.0000,17.0000,195.7095,196.5924,192.3741,NaN,NaN,NaN,20.0000,36.0000,NaN,11.0000

### Describe Después

In [ ]:
dataset4Final.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Frequency,User,Trial,Code
count,2745501.0000,2745501.0000,2745501.0000,2745501.0000,2745497.0000,0.0000,0.0000,0.0000,2745501.0000,2745501.0000,0.0000,2745501.0000
mean,4.0000,9.4795,6.4914,71.1817,4.0199,NaN,NaN,NaN,50.0000,18.8607,NaN,11.0000
std,0.0000,3.5799,67.1969,66.1957,46.6332,NaN,NaN,NaN,0.0000,10.2142,NaN,0.0000
min,4.0000,6.0000,-192.3741,-192.3741,-194.2380,NaN,NaN,NaN,50.0000,1.0000,NaN,11.0000
25%,4.0000,6.0000,-28.5471,31.0977,-21.7793,NaN,NaN,NaN,50.0000,10.0000,NaN,11.0000
50%,4.0000,9.0000,2.6487,77.7933,0.0000,NaN,NaN,NaN,50.0000,19.0000,NaN,11.0000
75%,4.0000,13.0000,43.5564,113.4036,26.6832,NaN,NaN,NaN,50.0000,28.0000,NaN,11.0000
max,4.0000,17.0000,195.7095,196.5924,192.3741,NaN,NaN,NaN,50.0000,36.0000,NaN,11.0000

In [ ]:
df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,9,13,9.551126,-1.744000,-0.286125,4.602500,-6.912500,4.235000,208,NaN,40,11,23
1,9,13,8.720001,-3.447125,-2.765875,15.540000,18.182500,13.860000,208,NaN,40,24,48
2,9,17,9.796375,-2.261750,-1.008250,-0.420000,-3.045000,0.735000,208,NaN,40,28,57
3,9,18,0.517750,7.888875,6.417375,-0.892500,4.375000,0.472500,208,NaN,40,30,61
4,9,6,12.248876,1.253500,-3.896750,-1.382500,5.932500,5.162500,208,NaN,40,17,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...
652486,9,13,5.163875,-5.708875,-1.062750,26.477500,-44.537502,-12.407501,208,NaN,40,19,38
652487,9,16,9.278625,2.902125,2.084625,0.175000,1.575000,0.017500,208,NaN,40,4,7
652488,9,16,9.782750,1.035500,1.635000,1.207500,-7.000000,2.695000,208,NaN,40,26,53
652489,9,18,-1.635000,-1.662250,-9.646501,1.767500,-0.175000,0.175000,208,NaN,40,28,57
652490,9,13,7.929750,-2.289000,-0.654000,108.079998,-59.027499,1.347500,208,NaN,40,11,23

# Dataset Número 5. PAMAP2

##Preparación del Dataset 5 Protocol

In [ ]:
import csv

with open(PAMAP2_Protocol_1, 'r') as f:
    contenido = f.readlines()

datos = []
for linea in contenido:
    fila = linea.strip().split()
    datos.append(fila)

with open('PAMAP2_Protocol_1.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(datos)

In [ ]:
Protocol_Subject101 = pd.read_csv('PAMAP2_Protocol_1.csv', header=None)
Protocol_Subject101

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376412,3772.50,0,NaN,30.5,2.02477,7.29553,5.74194,2.06573,6.57692,5.92695,...,0.048745,-0.008034,0.018600,-58.8381,-36.2397,-11.0980,1.0,0.0,0.0,0.0
376413,3772.51,0,NaN,30.5,2.10836,7.86504,5.85674,2.08754,7.42244,5.87977,...,0.042113,0.024647,0.013375,-58.9537,-36.3379,-11.7170,1.0,0.0,0.0,0.0
376414,3772.52,0,NaN,30.5,2.07163,8.39581,5.77742,2.13833,8.05640,5.90853,...,-0.014889,0.026009,0.025054,-59.1781,-35.8985,-10.9678,1.0,0.0,0.0,0.0
376415,3772.53,0,NaN,30.5,2.19569,8.77634,6.00892,2.11251,8.53989,5.93770,...,0.047026,-0.035531,0.024640,-58.8299,-36.6845,-10.8553,1.0,0.0,0.0,0.0
376416,3772.54,0,NaN,30.5,2.14774,8.66047,5.73918,2.15810,8.59995,5.92242,...,0.042585,0.017541,-0.037893,-59.1707,-36.7731,-11.5961,1.0,0.0,0.0,0.0

In [ ]:
header = ['timestamp', 'activityID', 'heart rate', 'IMU_hand_temperature', 'IMU_hand_x_accel_16g', 'IMU_hand_y_accel_16g', 'IMU_hand_z_accel_16g', 'IMU_hand_x_accel_6g',
          'IMU_hand_y_accel_6g', 'IMU_hand_z_accel_6g', 'IMU_hand_x_gyro', 'IMU_hand_y_gyro', 'IMU_hand_z_gyro', 'IMU_hand_x_magn', 'IMU_hand_y_magn',
          'IMU_hand_z_magn', 'IMU_hand_1_orientation', 'IMU_hand_2_orientation', 'IMU_hand_3_orientation', 'IMU_hand_4_orientation',
          'IMU_chest_temperature', 'IMU_chest_x_accel_16g', 'IMU_chest_y_accel_16g', 'IMU_chest_z_accel_16g', 'IMU_chest_x_accel_6g',
          'IMU_chest_y_accel_6g', 'IMU_chest_z_accel_6g', 'IMU_chest_x_gyro', 'IMU_chest_y_gyro', 'IMU_chest_z_gyro', 'IMU_chest_x_magn', 'IMU_chest_y_magn',
          'IMU_chest_z_magn', 'IMU_chest_1_orientation', 'IMU_chest_2_orientation', 'IMU_chest_3_orientation', 'IMU_chest_4_orientation',
          'IMU_ankle_temperature', 'IMU_ankle_x_accel_16g', 'IMU_ankle_y_accel_16g', 'IMU_ankle_z_accel_16g', 'IMU_ankle_x_accel_6g',
          'IMU_ankle_y_accel_6g', 'IMU_ankle_z_accel_6g', 'IMU_ankle_x_gyro', 'IMU_ankle_y_gyro', 'IMU_ankle_z_gyro', 'IMU_ankle_x_magn', 'IMU_ankle_y_magn',
          'IMU_ankle_z_magn', 'IMU_ankle_1_orientation', 'IMU_ankle_2_orientation', 'IMU_ankle_3_orientation', 'IMU_ankle_4_orientation']
Protocol_Subject101.columns = header

In [ ]:
Protocol_Subject101

,timestamp,activityID,heart rate,IMU_hand_temperature,IMU_hand_x_accel_16g,IMU_hand_y_accel_16g,IMU_hand_z_accel_16g,IMU_hand_x_accel_6g,IMU_hand_y_accel_6g,IMU_hand_z_accel_6g,...,IMU_ankle_x_gyro,IMU_ankle_y_gyro,IMU_ankle_z_gyro,IMU_ankle_x_magn,IMU_ankle_y_magn,IMU_ankle_z_magn,IMU_ankle_1_orientation,IMU_ankle_2_orientation,IMU_ankle_3_orientation,IMU_ankle_4_orientation
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376412,3772.50,0,NaN,30.5,2.02477,7.29553,5.74194,2.06573,6.57692,5.92695,...,0.048745,-0.008034,0.018600,-58.8381,-36.2397,-11.0980,1.0,0.0,0.0,0.0
376413,3772.51,0,NaN,30.5,2.10836,7.86504,5.85674,2.08754,7.42244,5.87977,...,0.042113,0.024647,0.013375,-58.9537,-36.3379,-11.7170,1.0,0.0,0.0,0.0
376414,3772.52,0,NaN,30.5,2.07163,8.39581,5.77742,2.13833,8.05640,5.90853,...,-0.014889,0.026009,0.025054,-59.1781,-35.8985,-10.9678,1.0,0.0,0.0,0.0
376415,3772.53,0,NaN,30.5,2.19569,8.77634,6.00892,2.11251,8.53989,5.93770,...,0.047026,-0.035531,0.024640,-58.8299,-36.6845,-10.8553,1.0,0.0,0.0,0.0
376416,3772.54,0,NaN,30.5,2.14774,8.66047,5.73918,2.15810,8.59995,5.92242,...,0.042585,0.017541,-0.037893,-59.1707,-36.7731,-11.5961,1.0,0.0,0.0,0.0

En el dataframe resultante se aprecia que hay bastantes columnas que podemos eliminar puesto que nos centramos unicamente en los sensores acelerometro y giroscopio.
Procedemos a eliminar estas columnas y a agragar una nueva columna llamada Subject para así poder unir los datasets.

In [ ]:
columnas_a_conservar = ['timestamp','activityID', 'IMU_hand_x_accel_16g', 'IMU_hand_y_accel_16g', 'IMU_hand_z_accel_16g', 'IMU_hand_x_accel_6g',
          'IMU_hand_y_accel_6g', 'IMU_hand_z_accel_6g', 'IMU_hand_x_gyro', 'IMU_hand_y_gyro', 'IMU_hand_z_gyro',
          'IMU_chest_x_accel_16g', 'IMU_chest_y_accel_16g', 'IMU_chest_z_accel_16g', 'IMU_chest_x_accel_6g',
          'IMU_chest_y_accel_6g', 'IMU_chest_z_accel_6g', 'IMU_chest_x_gyro', 'IMU_chest_y_gyro', 'IMU_chest_z_gyro',
          'IMU_ankle_x_accel_16g', 'IMU_ankle_y_accel_16g', 'IMU_ankle_z_accel_16g', 'IMU_ankle_x_accel_6g',
          'IMU_ankle_y_accel_6g', 'IMU_ankle_z_accel_6g', 'IMU_ankle_x_gyro', 'IMU_ankle_y_gyro', 'IMU_ankle_z_gyro']

Protocol_Subject101 = Protocol_Subject101[columnas_a_conservar]

Protocol_Subject101.insert(0, 'Subject', 1)
Protocol_Subject101

,Subject,timestamp,activityID,IMU_hand_x_accel_16g,IMU_hand_y_accel_16g,IMU_hand_z_accel_16g,IMU_hand_x_accel_6g,IMU_hand_y_accel_6g,IMU_hand_z_accel_6g,IMU_hand_x_gyro,...,IMU_chest_z_gyro,IMU_ankle_x_accel_16g,IMU_ankle_y_accel_16g,IMU_ankle_z_accel_16g,IMU_ankle_x_accel_6g,IMU_ankle_y_accel_6g,IMU_ankle_z_accel_6g,IMU_ankle_x_gyro,IMU_ankle_y_gyro,IMU_ankle_z_gyro
0,1,8.38,0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,-0.092217,...,-0.005663,9.65918,-1.655690,-0.099797,9.64689,-1.555760,0.310404,0.008300,0.009250,-0.017580
1,1,8.39,0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,-0.024413,...,-0.041522,9.69370,-1.579020,-0.215687,9.61670,-1.616300,0.280488,-0.006577,-0.004638,0.000368
2,1,8.40,0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,-0.057976,...,-0.002113,9.58944,-1.732760,0.092914,9.63173,-1.586050,0.280311,0.003014,0.000148,0.022495
3,1,8.41,0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,-0.002352,...,-0.020684,9.58814,-1.770400,0.054545,9.63197,-1.631350,0.340997,0.003175,-0.020301,0.011275
4,1,8.42,0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,0.012269,...,-0.025975,9.69771,-1.656250,-0.060809,9.64699,-1.646470,0.340965,0.012698,-0.014303,-0.002823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376412,1,3772.50,0,2.02477,7.29553,5.74194,2.06573,6.57692,5.92695,1.516160,...,0.008888,9.89247,-0.404788,-0.027988,9.82743,-0.315490,0.290320,0.048745,-0.008034,0.018600
376413,1,3772.51,0,2.10836,7.86504,5.85674,2.08754,7.42244,5.87977,1.542230,...,0.020261,9.77339,-0.440118,-0.260527,9.82756,-0.300328,0.320541,0.042113,0.024647,0.013375
376414,1,3772.52,0,2.07163,8.39581,5.77742,2.13833,8.05640,5.90853,1.502390,...,0.014223,9.81482,-0.517578,-0.105264,9.81240,-0.360868,0.290545,-0.014889,0.026009,0.025054
376415,1,3772.53,0,2.19569,8.77634,6.00892,2.11251,8.53989,5.93770,1.332220,...,-0.019539,9.85194,-0.365619,-0.144416,9.84249,-0.391093,0.305618,0.047026,-0.035531,0.024640
376416,1,3772.54,0,2.14774,8.66047,5.73918,2.15810,8.59995,5.92242,1.209100,...,-0.019038,9.85084,-0.365298,-0.183018,9.82756,-0.300328,0.320541,0.042585,0.017541,-0.037893

In [ ]:
Protocol_Subject101.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Protocol/Subject101_limpio.csv', index=False)

Se procede a realizar el mismo precedimiento a los demás archivos.dat haciendo uso de un While

In [ ]:
x = 1
while x < 10:

  PAMAP2_Protocol_1 = '/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Protocol/subject10{}.dat'.format(x)

  import csv

  with open(PAMAP2_Protocol_1, 'r') as f:
      contenido = f.readlines()

  datos = []
  for linea in contenido:
      fila = linea.strip().split()
      datos.append(fila)

  with open('PAMAP2_Protocol_1.csv', 'w', newline='') as f:
      writer = csv.writer(f)
      writer.writerows(datos)

  Protocol_Subject101 = pd.read_csv('PAMAP2_Protocol_1.csv', header=None)

  import pandas as pd

  header = ['timestamp', 'activityID', 'heart rate', 'IMU_hand_temperature', 'IMU_hand_x_accel_16g', 'IMU_hand_y_accel_16g', 'IMU_hand_z_accel_16g', 'IMU_hand_x_accel_6g',
          'IMU_hand_y_accel_6g', 'IMU_hand_z_accel_6g', 'IMU_hand_x_gyro', 'IMU_hand_y_gyro', 'IMU_hand_z_gyro', 'IMU_hand_x_magn', 'IMU_hand_y_magn',
          'IMU_hand_z_magn', 'IMU_hand_1_orientation', 'IMU_hand_2_orientation', 'IMU_hand_3_orientation', 'IMU_hand_4_orientation',
          'IMU_chest_temperature', 'IMU_chest_x_accel_16g', 'IMU_chest_y_accel_16g', 'IMU_chest_z_accel_16g', 'IMU_chest_x_accel_6g',
          'IMU_chest_y_accel_6g', 'IMU_chest_z_accel_6g', 'IMU_chest_x_gyro', 'IMU_chest_y_gyro', 'IMU_chest_z_gyro', 'IMU_chest_x_magn', 'IMU_chest_y_magn',
          'IMU_chest_z_magn', 'IMU_chest_1_orientation', 'IMU_chest_2_orientation', 'IMU_chest_3_orientation', 'IMU_chest_4_orientation',
          'IMU_ankle_temperature', 'IMU_ankle_x_accel_16g', 'IMU_ankle_y_accel_16g', 'IMU_ankle_z_accel_16g', 'IMU_ankle_x_accel_6g',
          'IMU_ankle_y_accel_6g', 'IMU_ankle_z_accel_6g', 'IMU_ankle_x_gyro', 'IMU_ankle_y_gyro', 'IMU_ankle_z_gyro', 'IMU_ankle_x_magn', 'IMU_ankle_y_magn',
          'IMU_ankle_z_magn', 'IMU_ankle_1_orientation', 'IMU_ankle_2_orientation', 'IMU_ankle_3_orientation', 'IMU_ankle_4_orientation']
  Protocol_Subject101.columns = header

  columnas_a_conservar = ['timestamp','activityID', 'IMU_hand_x_accel_16g', 'IMU_hand_y_accel_16g', 'IMU_hand_z_accel_16g', 'IMU_hand_x_accel_6g',
            'IMU_hand_y_accel_6g', 'IMU_hand_z_accel_6g', 'IMU_hand_x_gyro', 'IMU_hand_y_gyro', 'IMU_hand_z_gyro',
            'IMU_chest_x_accel_16g', 'IMU_chest_y_accel_16g', 'IMU_chest_z_accel_16g', 'IMU_chest_x_accel_6g',
            'IMU_chest_y_accel_6g', 'IMU_chest_z_accel_6g', 'IMU_chest_x_gyro', 'IMU_chest_y_gyro', 'IMU_chest_z_gyro',
            'IMU_ankle_x_accel_16g', 'IMU_ankle_y_accel_16g', 'IMU_ankle_z_accel_16g', 'IMU_ankle_x_accel_6g',
            'IMU_ankle_y_accel_6g', 'IMU_ankle_z_accel_6g', 'IMU_ankle_x_gyro', 'IMU_ankle_y_gyro', 'IMU_ankle_z_gyro']

  Protocol_Subject101 = Protocol_Subject101[columnas_a_conservar]

  Protocol_Subject101.insert(0, 'Subject', x)

  Protocol_Subject101.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Protocol/Subject10{}_limpio.csv'.format(x), index=False)

  x = x + 1

En este momento ya tenemos los 9 archivos .csv limpios, por lo que se procede a unirlos.

In [ ]:
dataframes = {1: 'Subject101_limpio', 2: 'Subject102_limpio', 3: 'Subject103_limpio', 4: 'Subject104_limpio', 5: 'Subject105_limpio',
              6: 'Subject106_limpio', 7: 'Subject107_limpio', 8: 'Subject108_limpio', 9: 'Subject109_limpio'}
cont = 1
while cont < 10:
  y = '/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Protocol/Subject10{}_limpio.csv'.format(cont)
  dataframe = dataframes[cont]
  globals()[dataframe] = pd.read_csv(y)
  cont = cont + 1

In [ ]:
PAMAP2_FINAL = pd.concat([Subject101_limpio, Subject102_limpio, Subject103_limpio, Subject104_limpio, Subject105_limpio,
              Subject106_limpio, Subject107_limpio, Subject108_limpio, Subject109_limpio], ignore_index=True)
PAMAP2_FINAL

PAMAP2_FINAL.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Protocol/PAMAP2_PROTOCOL_FINAL.csv')

,Subject,timestamp,activityID,IMU_hand_x_accel_16g,IMU_hand_y_accel_16g,IMU_hand_z_accel_16g,IMU_hand_x_accel_6g,IMU_hand_y_accel_6g,IMU_hand_z_accel_6g,IMU_hand_x_gyro,...,IMU_chest_z_gyro,IMU_ankle_x_accel_16g,IMU_ankle_y_accel_16g,IMU_ankle_z_accel_16g,IMU_ankle_x_accel_6g,IMU_ankle_y_accel_6g,IMU_ankle_z_accel_6g,IMU_ankle_x_gyro,IMU_ankle_y_gyro,IMU_ankle_z_gyro
0,1,8.38,0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,-0.092217,...,-0.005663,9.65918,-1.655690,-0.099797,9.64689,-1.555760,0.310404,0.008300,0.009250,-0.017580
1,1,8.39,0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,-0.024413,...,-0.041522,9.69370,-1.579020,-0.215687,9.61670,-1.616300,0.280488,-0.006577,-0.004638,0.000368
2,1,8.40,0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,-0.057976,...,-0.002113,9.58944,-1.732760,0.092914,9.63173,-1.586050,0.280311,0.003014,0.000148,0.022495
3,1,8.41,0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,-0.002352,...,-0.020684,9.58814,-1.770400,0.054545,9.63197,-1.631350,0.340997,0.003175,-0.020301,0.011275
4,1,8.42,0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,0.012269,...,-0.025975,9.69771,-1.656250,-0.060809,9.64699,-1.646470,0.340965,0.012698,-0.014303,-0.002823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,9,100.19,0,-4.71493,10.22250,4.66893,-5.04654,9.94944,4.50736,1.784060,...,-0.191336,9.38737,-0.565040,-3.273700,9.09401,-0.228554,-2.687700,-0.037788,-0.062676,-0.127084
2872529,9,100.20,0,-4.95932,10.37130,4.12594,-4.96890,10.29620,4.43102,1.475210,...,-0.211320,9.45875,-1.020820,-3.308730,9.27291,-0.607010,-2.990140,-0.068904,-0.027006,-0.089808
2872530,9,100.21,0,-4.93997,9.83615,3.70468,-5.04613,10.35690,4.14405,1.290990,...,-0.237024,9.57580,-0.528578,-3.233400,9.43813,-0.697724,-2.990720,-0.070888,-0.038024,-0.064709
2872531,9,100.22,0,-4.64941,9.11129,3.51904,-5.06854,9.75268,3.87359,1.207940,...,-0.333854,9.49894,-0.489493,-3.311610,9.49875,-0.576563,-2.870350,0.018961,-0.025796,-0.064357
2872532,9,100.23,0,-4.09726,8.15642,3.29961,-4.73244,8.82870,3.54305,1.404170,...,-0.396232,9.42169,-0.526345,-3.389350,9.51292,-0.470945,-3.082660,-0.027472,0.011866,-0.042858

In [ ]:
PAMAP2_FINAL["activityID"].unique()

array([ 0,  1,  2,  3, 17, 16, 12, 13,  4,  7,  6,  5, 24])

In [ ]:
PAMAP2_FINAL_read = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Protocol/PAMAP2_PROTOCOL_FINAL.csv')

In [ ]:
PAMAP2_FINAL_read

,Unnamed: 0,Subject,timestamp,activityID,IMU_hand_x_accel_16g,IMU_hand_y_accel_16g,IMU_hand_z_accel_16g,IMU_hand_x_accel_6g,IMU_hand_y_accel_6g,IMU_hand_z_accel_6g,...,IMU_chest_z_gyro,IMU_ankle_x_accel_16g,IMU_ankle_y_accel_16g,IMU_ankle_z_accel_16g,IMU_ankle_x_accel_6g,IMU_ankle_y_accel_6g,IMU_ankle_z_accel_6g,IMU_ankle_x_gyro,IMU_ankle_y_gyro,IMU_ankle_z_gyro
0,0,1,8.38,0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,-0.005663,9.65918,-1.655690,-0.099797,9.64689,-1.555760,0.310404,0.008300,0.009250,-0.017580
1,1,1,8.39,0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.041522,9.69370,-1.579020,-0.215687,9.61670,-1.616300,0.280488,-0.006577,-0.004638,0.000368
2,2,1,8.40,0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,-0.002113,9.58944,-1.732760,0.092914,9.63173,-1.586050,0.280311,0.003014,0.000148,0.022495
3,3,1,8.41,0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,-0.020684,9.58814,-1.770400,0.054545,9.63197,-1.631350,0.340997,0.003175,-0.020301,0.011275
4,4,1,8.42,0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,-0.025975,9.69771,-1.656250,-0.060809,9.64699,-1.646470,0.340965,0.012698,-0.014303,-0.002823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,2872528,9,100.19,0,-4.71493,10.22250,4.66893,-5.04654,9.94944,4.50736,...,-0.191336,9.38737,-0.565040,-3.273700,9.09401,-0.228554,-2.687700,-0.037788,-0.062676,-0.127084
2872529,2872529,9,100.20,0,-4.95932,10.37130,4.12594,-4.96890,10.29620,4.43102,...,-0.211320,9.45875,-1.020820,-3.308730,9.27291,-0.607010,-2.990140,-0.068904,-0.027006,-0.089808
2872530,2872530,9,100.21,0,-4.93997,9.83615,3.70468,-5.04613,10.35690,4.14405,...,-0.237024,9.57580,-0.528578,-3.233400,9.43813,-0.697724,-2.990720,-0.070888,-0.038024,-0.064709
2872531,2872531,9,100.22,0,-4.64941,9.11129,3.51904,-5.06854,9.75268,3.87359,...,-0.333854,9.49894,-0.489493,-3.311610,9.49875,-0.576563,-2.870350,0.018961,-0.025796,-0.064357
2872532,2872532,9,100.23,0,-4.09726,8.15642,3.29961,-4.73244,8.82870,3.54305,...,-0.396232,9.42169,-0.526345,-3.389350,9.51292,-0.470945,-3.082660,-0.027472,0.011866,-0.042858

Precedemos a modificar el dataset para que cumpla con el standard acordado, por lo tando, vamos a cambiar el nombre de las columnas y reubicarlas, para el uso de los código, y usar columnas unicas para x,y y z. Debemos separar el dataset en mano, pecho y cadera, colocar los codigos y volver a unir el dataset pero esta vez de manera vertical.

In [ ]:
cols_comunes = ["Subject", "timestamp", "activityID"]

PAMAP2_FINAL_HAND = PAMAP2_FINAL_read.loc[:, cols_comunes + ["IMU_hand_x_accel_16g", "IMU_hand_y_accel_16g", "IMU_hand_z_accel_16g", "IMU_hand_x_accel_6g", "IMU_hand_y_accel_6g", "IMU_hand_z_accel_6g", "IMU_hand_x_gyro", "IMU_hand_y_gyro", "IMU_hand_z_gyro"]]

PAMAP2_FINAL_CHEST = PAMAP2_FINAL_read.loc[:, cols_comunes + ["IMU_chest_x_accel_16g", "IMU_chest_y_accel_16g", "IMU_chest_z_accel_16g", "IMU_chest_x_accel_6g", "IMU_chest_y_accel_6g", "IMU_chest_z_accel_6g", "IMU_chest_x_gyro", "IMU_chest_y_gyro", "IMU_chest_z_gyro"]]

PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_read.loc[:, cols_comunes + ["IMU_ankle_x_accel_16g", "IMU_ankle_y_accel_16g", "IMU_ankle_z_accel_16g", "IMU_ankle_x_accel_6g", "IMU_ankle_y_accel_6g", "IMU_ankle_z_accel_6g", "IMU_ankle_x_gyro", "IMU_ankle_y_gyro", "IMU_ankle_z_gyro"]]

In [ ]:

PAMAP2_FINAL_ANKLE.insert(12,'Code', 203)
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_x_accel_16g': 'X_Acc'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_y_accel_16g': 'Y_Acc'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_z_accel_16g': 'Z_Acc'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_x_accel_6g': 'X_Acc_6'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_y_accel_6g': 'Y_Acc_6'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_z_accel_6g': 'Z_Acc_6'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_x_gyro': 'X_Gyro'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_y_gyro': 'Y_Gyro'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_z_gyro': 'Z_Gyro'})
PAMAP2_FINAL_ANKLE
PAMAP2_FINAL_ANKLE.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/DATASETS_SEPARADOS/PAMAP2_FINAL_ANKLE_WITH_CODE.csv', index=False)

In [ ]:
PAMAP2_FINAL_CHEST.insert(12,'Code', 204)
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_x_accel_16g': 'X_Acc'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_y_accel_16g': 'Y_Acc'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_z_accel_16g': 'Z_Acc'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_x_accel_6g': 'X_Acc_6'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_y_accel_6g': 'Y_Acc_6'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_z_accel_6g': 'Z_Acc_6'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_x_gyro': 'X_Gyro'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_y_gyro': 'Y_Gyro'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_z_gyro': 'Z_Gyro'})
PAMAP2_FINAL_CHEST.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/DATASETS_SEPARADOS/PAMAP2_FINAL_CHEST_WITH_CODE.csv', index=False)

In [ ]:
PAMAP2_FINAL_HAND.insert(12,'Code', 201)
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_x_accel_16g': 'X_Acc'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_y_accel_16g': 'Y_Acc'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_z_accel_16g': 'Z_Acc'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_x_accel_6g': 'X_Acc_6'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_y_accel_6g': 'Y_Acc_6'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_z_accel_6g': 'Z_Acc_6'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_x_gyro': 'X_Gyro'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_y_gyro': 'Y_Gyro'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_z_gyro': 'Z_Gyro'})
PAMAP2_FINAL_HAND.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/DATASETS_SEPARADOS/PAMAP2_FINAL_HAND_WITH_CODE.csv', index=False)

In [ ]:
PAMAP2_FINAL_ORGANIZED = pd.concat([PAMAP2_FINAL_HAND, PAMAP2_FINAL_CHEST, PAMAP2_FINAL_ANKLE])
PAMAP2_FINAL_ORGANIZED

,Subject,timestamp,activityID,X_Acc,Y_Acc,Z_Acc,X_Acc_6,Y_Acc_6,Z_Acc_6,X_Gyro,Y_Gyro,Z_Gyro,Code
0,1,8.38,0,2.37223,8.600740,3.51048,2.43954,8.761650,3.35465,-0.092217,0.056812,-0.015845,201
1,1,8.39,0,2.18837,8.565600,3.66179,2.39494,8.550810,3.64207,-0.024413,0.047759,0.006474,201
2,1,8.40,0,2.37357,8.601070,3.54898,2.30514,8.536440,3.73280,-0.057976,0.032574,-0.006988,201
3,1,8.41,0,2.07473,8.528530,3.66021,2.33528,8.536220,3.73277,-0.002352,0.032810,-0.003747,201
4,1,8.42,0,2.22936,8.831220,3.70000,2.23055,8.597410,3.76295,0.012269,0.018305,-0.053325,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,9,100.19,0,9.38737,-0.565040,-3.27370,9.09401,-0.228554,-2.68770,-0.037788,-0.062676,-0.127084,203
2872529,9,100.20,0,9.45875,-1.020820,-3.30873,9.27291,-0.607010,-2.99014,-0.068904,-0.027006,-0.089808,203
2872530,9,100.21,0,9.57580,-0.528578,-3.23340,9.43813,-0.697724,-2.99072,-0.070888,-0.038024,-0.064709,203
2872531,9,100.22,0,9.49894,-0.489493,-3.31161,9.49875,-0.576563,-2.87035,0.018961,-0.025796,-0.064357,203
2872532,9,100.23,0,9.42169,-0.526345,-3.38935,9.51292,-0.470945,-3.08266,-0.027472,0.011866,-0.042858,203

In [ ]:
PAMAP2_FINAL_ORGANIZED.insert(13,'Dataset', 5)
PAMAP2_FINAL_ORGANIZED.insert(14,'Frequency', 100)
PAMAP2_FINAL_ORGANIZED.insert(15,'Trial', np.nan)
PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.rename(columns={'activityID': 'Activity'})
PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.rename(columns={'timestamp': 'TimeStamp'})
PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.rename(columns={'Subject': 'User'})

PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])
PAMAP2_FINAL_ORGANIZED

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,5,0,2.37223,8.600740,3.51048,-0.092217,0.056812,-0.015845,2.43954,8.761650,3.35465,201,8.38,100,1,NaN
1,5,0,2.18837,8.565600,3.66179,-0.024413,0.047759,0.006474,2.39494,8.550810,3.64207,201,8.39,100,1,NaN
2,5,0,2.37357,8.601070,3.54898,-0.057976,0.032574,-0.006988,2.30514,8.536440,3.73280,201,8.40,100,1,NaN
3,5,0,2.07473,8.528530,3.66021,-0.002352,0.032810,-0.003747,2.33528,8.536220,3.73277,201,8.41,100,1,NaN
4,5,0,2.22936,8.831220,3.70000,0.012269,0.018305,-0.053325,2.23055,8.597410,3.76295,201,8.42,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,5,0,9.38737,-0.565040,-3.27370,-0.037788,-0.062676,-0.127084,9.09401,-0.228554,-2.68770,203,100.19,100,9,NaN
2872529,5,0,9.45875,-1.020820,-3.30873,-0.068904,-0.027006,-0.089808,9.27291,-0.607010,-2.99014,203,100.20,100,9,NaN
2872530,5,0,9.57580,-0.528578,-3.23340,-0.070888,-0.038024,-0.064709,9.43813,-0.697724,-2.99072,203,100.21,100,9,NaN
2872531,5,0,9.49894,-0.489493,-3.31161,0.018961,-0.025796,-0.064357,9.49875,-0.576563,-2.87035,203,100.22,100,9,NaN
2872532,5,0,9.42169,-0.526345,-3.38935,-0.027472,0.011866,-0.042858,9.51292,-0.470945,-3.08266,203,100.23,100,9,NaN

In [ ]:
PAMAP2_FINAL_ORGANIZED.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5.csv')

In [ ]:
Dataset5 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5.csv')

In [ ]:
Dataset5

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,0,5,0,2.37223,8.600740,3.51048,-0.092217,0.056812,-0.015845,2.43954,8.761650,3.35465,201,8.38,100,1,NaN
1,1,5,0,2.18837,8.565600,3.66179,-0.024413,0.047759,0.006474,2.39494,8.550810,3.64207,201,8.39,100,1,NaN
2,2,5,0,2.37357,8.601070,3.54898,-0.057976,0.032574,-0.006988,2.30514,8.536440,3.73280,201,8.40,100,1,NaN
3,3,5,0,2.07473,8.528530,3.66021,-0.002352,0.032810,-0.003747,2.33528,8.536220,3.73277,201,8.41,100,1,NaN
4,4,5,0,2.22936,8.831220,3.70000,0.012269,0.018305,-0.053325,2.23055,8.597410,3.76295,201,8.42,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617594,2872528,5,0,9.38737,-0.565040,-3.27370,-0.037788,-0.062676,-0.127084,9.09401,-0.228554,-2.68770,203,100.19,100,9,NaN
8617595,2872529,5,0,9.45875,-1.020820,-3.30873,-0.068904,-0.027006,-0.089808,9.27291,-0.607010,-2.99014,203,100.20,100,9,NaN
8617596,2872530,5,0,9.57580,-0.528578,-3.23340,-0.070888,-0.038024,-0.064709,9.43813,-0.697724,-2.99072,203,100.21,100,9,NaN
8617597,2872531,5,0,9.49894,-0.489493,-3.31161,0.018961,-0.025796,-0.064357,9.49875,-0.576563,-2.87035,203,100.22,100,9,NaN
8617598,2872532,5,0,9.42169,-0.526345,-3.38935,-0.027472,0.011866,-0.042858,9.51292,-0.470945,-3.08266,203,100.23,100,9,NaN

Pasamos de rad a dps

In [ ]:
Dataset5['X_Gyro'] = np.degrees(Dataset5['X_Gyro'])
Dataset5['Y_Gyro'] = np.degrees(Dataset5['Y_Gyro'])
Dataset5['Z_Gyro'] = np.degrees(Dataset5['Z_Gyro'])
Dataset5 = Dataset5.drop(['X_Acc_6', 'Y_Acc_6', 'Z_Acc_6'], axis=1)

In [ ]:
Dataset5

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,5,0,2.37223,8.600740,3.51048,-5.283668,3.255059,-0.907823,201,8.38,100,1,NaN
1,1,5,0,2.18837,8.565600,3.66179,-1.398773,2.736360,0.370952,201,8.39,100,1,NaN
2,2,5,0,2.37357,8.601070,3.54898,-3.321786,1.866370,-0.400392,201,8.40,100,1,NaN
3,3,5,0,2.07473,8.528530,3.66021,-0.134737,1.879863,-0.214703,201,8.41,100,1,NaN
4,4,5,0,2.22936,8.831220,3.70000,0.702968,1.048799,-3.055286,201,8.42,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617594,2872528,5,0,9.38737,-0.565040,-3.27370,-2.165070,-3.591076,-7.281377,203,100.19,100,9,NaN
8617595,2872529,5,0,9.45875,-1.020820,-3.30873,-3.947885,-1.547341,-5.145602,203,100.20,100,9,NaN
8617596,2872530,5,0,9.57580,-0.528578,-3.23340,-4.061566,-2.178586,-3.707530,203,100.21,100,9,NaN
8617597,2872531,5,0,9.49894,-0.489493,-3.31161,1.086408,-1.478025,-3.687413,203,100.22,100,9,NaN
8617598,2872532,5,0,9.42169,-0.526345,-3.38935,-1.574041,0.679877,-2.455560,203,100.23,100,9,NaN

In [ ]:
ocurrencias = Dataset5['Unnamed: 0'].value_counts()

print("El valor 2872531 aparece:", ocurrencias[2872531], "veces")

El valor 2872531 aparece: 3 veces

In [ ]:
Dataset5.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5.csv', index=False)

In [ ]:
dataset5 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5.csv')

In [ ]:
dataset5

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,5,0,2.37223,8.600740,3.51048,-5.283668,3.255059,-0.907823,201,8.38,100,1,NaN
1,1,5,0,2.18837,8.565600,3.66179,-1.398773,2.736360,0.370952,201,8.39,100,1,NaN
2,2,5,0,2.37357,8.601070,3.54898,-3.321786,1.866370,-0.400392,201,8.40,100,1,NaN
3,3,5,0,2.07473,8.528530,3.66021,-0.134737,1.879863,-0.214703,201,8.41,100,1,NaN
4,4,5,0,2.22936,8.831220,3.70000,0.702968,1.048799,-3.055286,201,8.42,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617594,2872528,5,0,9.38737,-0.565040,-3.27370,-2.165070,-3.591076,-7.281377,203,100.19,100,9,NaN
8617595,2872529,5,0,9.45875,-1.020820,-3.30873,-3.947885,-1.547341,-5.145602,203,100.20,100,9,NaN
8617596,2872530,5,0,9.57580,-0.528578,-3.23340,-4.061566,-2.178586,-3.707530,203,100.21,100,9,NaN
8617597,2872531,5,0,9.49894,-0.489493,-3.31161,1.086408,-1.478025,-3.687413,203,100.22,100,9,NaN
8617598,2872532,5,0,9.42169,-0.526345,-3.38935,-1.574041,0.679877,-2.455560,203,100.23,100,9,NaN

##Preparación del Dataset 5 Optional

In [ ]:
x = 1
while x < 10:

  PAMAP2_Protocol_1 = '/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Optional/subject10{}.dat'.format(x)

  try:
    with open(PAMAP2_Protocol_1, 'r') as f:
      contenido = f.readlines()


    datos = []
    for linea in contenido:
        fila = linea.strip().split()
        datos.append(fila)

    with open('PAMAP2_Protocol_1.csv', 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(datos)

    Protocol_Subject101 = pd.read_csv('PAMAP2_Protocol_1.csv', header=None)

    import pandas as pd

    header = ['timestamp', 'activityID', 'heart rate', 'IMU_hand_temperature', 'IMU_hand_x_accel_16g', 'IMU_hand_y_accel_16g', 'IMU_hand_z_accel_16g', 'IMU_hand_x_accel_6g',
            'IMU_hand_y_accel_6g', 'IMU_hand_z_accel_6g', 'IMU_hand_x_gyro', 'IMU_hand_y_gyro', 'IMU_hand_z_gyro', 'IMU_hand_x_magn', 'IMU_hand_y_magn',
            'IMU_hand_z_magn', 'IMU_hand_1_orientation', 'IMU_hand_2_orientation', 'IMU_hand_3_orientation', 'IMU_hand_4_orientation',
            'IMU_chest_temperature', 'IMU_chest_x_accel_16g', 'IMU_chest_y_accel_16g', 'IMU_chest_z_accel_16g', 'IMU_chest_x_accel_6g',
            'IMU_chest_y_accel_6g', 'IMU_chest_z_accel_6g', 'IMU_chest_x_gyro', 'IMU_chest_y_gyro', 'IMU_chest_z_gyro', 'IMU_chest_x_magn', 'IMU_chest_y_magn',
            'IMU_chest_z_magn', 'IMU_chest_1_orientation', 'IMU_chest_2_orientation', 'IMU_chest_3_orientation', 'IMU_chest_4_orientation',
            'IMU_ankle_temperature', 'IMU_ankle_x_accel_16g', 'IMU_ankle_y_accel_16g', 'IMU_ankle_z_accel_16g', 'IMU_ankle_x_accel_6g',
            'IMU_ankle_y_accel_6g', 'IMU_ankle_z_accel_6g', 'IMU_ankle_x_gyro', 'IMU_ankle_y_gyro', 'IMU_ankle_z_gyro', 'IMU_ankle_x_magn', 'IMU_ankle_y_magn',
            'IMU_ankle_z_magn', 'IMU_ankle_1_orientation', 'IMU_ankle_2_orientation', 'IMU_ankle_3_orientation', 'IMU_ankle_4_orientation']
    Protocol_Subject101.columns = header

    columnas_a_conservar = ['timestamp','activityID', 'IMU_hand_x_accel_16g', 'IMU_hand_y_accel_16g', 'IMU_hand_z_accel_16g', 'IMU_hand_x_accel_6g',
              'IMU_hand_y_accel_6g', 'IMU_hand_z_accel_6g', 'IMU_hand_x_gyro', 'IMU_hand_y_gyro', 'IMU_hand_z_gyro',
              'IMU_chest_x_accel_16g', 'IMU_chest_y_accel_16g', 'IMU_chest_z_accel_16g', 'IMU_chest_x_accel_6g',
              'IMU_chest_y_accel_6g', 'IMU_chest_z_accel_6g', 'IMU_chest_x_gyro', 'IMU_chest_y_gyro', 'IMU_chest_z_gyro',
              'IMU_ankle_x_accel_16g', 'IMU_ankle_y_accel_16g', 'IMU_ankle_z_accel_16g', 'IMU_ankle_x_accel_6g',
              'IMU_ankle_y_accel_6g', 'IMU_ankle_z_accel_6g', 'IMU_ankle_x_gyro', 'IMU_ankle_y_gyro', 'IMU_ankle_z_gyro']

    Protocol_Subject101 = Protocol_Subject101[columnas_a_conservar]

    Protocol_Subject101.insert(0, 'Subject', x)

    Protocol_Subject101.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Optional/Subject10{}_limpio.csv'.format(x), index=False)

  except FileNotFoundError:
    print(f'Archino no existe subject{x}')

  x = x + 1

Archino no existe subject2
Archino no existe subject3
Archino no existe subject4
Archino no existe subject7

In [ ]:
dataframes = {1: 'Subject101_limpio', 5: 'Subject105_limpio',
              6: 'Subject106_limpio', 8: 'Subject108_limpio', 9: 'Subject109_limpio'}
cont = 1
while cont < 10:
  if cont in dataframes:
    y = '/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Optional/Subject10{}_limpio.csv'.format(cont)
    dataframe = dataframes[cont]
    try:
      globals()[dataframe] = pd.read_csv(y)
    except FileNotFoundError:
      print(f'Archino no existe subject{x}')
  else:
    print(f"No dataframe defined for Subject10{cont}. Skipping...")
  cont = cont + 1

No dataframe defined for Subject102. Skipping...
No dataframe defined for Subject103. Skipping...
No dataframe defined for Subject104. Skipping...
No dataframe defined for Subject107. Skipping...

In [ ]:
Subject101_limpio

,Subject,timestamp,activityID,IMU_hand_x_accel_16g,IMU_hand_y_accel_16g,IMU_hand_z_accel_16g,IMU_hand_x_accel_6g,IMU_hand_y_accel_6g,IMU_hand_z_accel_6g,IMU_hand_x_gyro,...,IMU_chest_z_gyro,IMU_ankle_x_accel_16g,IMU_ankle_y_accel_16g,IMU_ankle_z_accel_16g,IMU_ankle_x_accel_6g,IMU_ankle_y_accel_6g,IMU_ankle_z_accel_6g,IMU_ankle_x_gyro,IMU_ankle_y_gyro,IMU_ankle_z_gyro
0,1,10.03,0,1.99964,6.94837,5.08845,2.62244,7.73457,4.64028,-1.636280,...,-0.046505,9.06112,-3.60810,-2.33201,9.05153,-3.61551,-1.829010,-0.013780,0.009471,0.003633
1,1,10.04,0,1.80990,6.45729,5.16424,2.19725,6.93762,5.06528,-1.624550,...,-0.032001,9.06352,-3.57078,-2.25504,9.06644,-3.55505,-1.859550,-0.026320,0.070031,0.001804
2,1,10.05,0,1.82756,5.93151,5.78208,2.01408,6.28989,5.44441,-1.468110,...,-0.046452,9.06611,-3.49548,-2.17830,9.05161,-3.53987,-1.814120,-0.049060,-0.002170,0.012096
3,1,10.06,0,1.75760,5.78202,5.97397,1.83344,5.83858,5.92881,-1.242220,...,-0.038846,9.03340,-3.64873,-1.98473,9.02174,-3.58520,-1.768410,-0.031388,-0.008545,0.007356
4,1,10.07,0,1.50670,6.20407,6.27669,1.71564,5.82465,6.27627,-0.967176,...,-0.045611,9.10294,-3.60962,-2.17721,9.05184,-3.61542,-1.753330,0.024549,0.036445,-0.004679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319347,1,3203.50,0,2.18107,8.34630,4.58612,2.40197,8.43084,4.60878,0.040671,...,-0.008683,9.77148,-1.64571,-1.41075,9.67205,-1.67818,-0.854748,0.034809,0.010912,-0.002528
319348,1,3203.51,0,2.36012,8.45598,4.28053,2.43224,8.47590,4.57845,0.095105,...,-0.027993,9.69603,-1.75915,-1.41082,9.67198,-1.70845,-0.869785,-0.000541,-0.002416,0.000405
319349,1,3203.52,0,2.21003,8.41954,4.31689,2.43261,8.44577,4.65402,0.129914,...,0.010492,9.58666,-1.83533,-1.29570,9.64225,-1.70836,-0.793952,0.043692,0.022721,-0.007908
319350,1,3203.53,0,2.17197,8.38190,4.31645,2.46212,8.40022,4.62388,0.187450,...,0.001980,9.58356,-1.79640,-1.41174,9.65703,-1.67818,-0.854668,0.030572,0.010404,0.010848
319351,1,3203.54,0,2.13285,8.19249,4.31650,2.41527,8.32493,4.50329,0.194696,...,0.023473,9.73837,-1.87489,-1.21672,9.71713,-1.63279,-0.855133,-0.029198,0.008957,-0.018469

In [ ]:
PAMAP2_FINAL = pd.concat([Subject101_limpio, Subject105_limpio,
              Subject106_limpio, Subject108_limpio, Subject109_limpio], ignore_index=True)
PAMAP2_FINAL

PAMAP2_FINAL.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Optional/PAMAP2_OPTIONAL_FINAL.csv', index=False)

In [ ]:
PAMAP2_FINAL

,Subject,timestamp,activityID,IMU_hand_x_accel_16g,IMU_hand_y_accel_16g,IMU_hand_z_accel_16g,IMU_hand_x_accel_6g,IMU_hand_y_accel_6g,IMU_hand_z_accel_6g,IMU_hand_x_gyro,...,IMU_chest_z_gyro,IMU_ankle_x_accel_16g,IMU_ankle_y_accel_16g,IMU_ankle_z_accel_16g,IMU_ankle_x_accel_6g,IMU_ankle_y_accel_6g,IMU_ankle_z_accel_6g,IMU_ankle_x_gyro,IMU_ankle_y_gyro,IMU_ankle_z_gyro
0,1,10.03,0,1.99964,6.94837,5.08845,2.62244,7.73457,4.64028,-1.636280,...,-0.046505,9.06112,-3.608100,-2.33201,9.05153,-3.615510,-1.82901,-0.013780,0.009471,0.003633
1,1,10.04,0,1.80990,6.45729,5.16424,2.19725,6.93762,5.06528,-1.624550,...,-0.032001,9.06352,-3.570780,-2.25504,9.06644,-3.555050,-1.85955,-0.026320,0.070031,0.001804
2,1,10.05,0,1.82756,5.93151,5.78208,2.01408,6.28989,5.44441,-1.468110,...,-0.046452,9.06611,-3.495480,-2.17830,9.05161,-3.539870,-1.81412,-0.049060,-0.002170,0.012096
3,1,10.06,0,1.75760,5.78202,5.97397,1.83344,5.83858,5.92881,-1.242220,...,-0.038846,9.03340,-3.648730,-1.98473,9.02174,-3.585200,-1.76841,-0.031388,-0.008545,0.007356
4,1,10.07,0,1.50670,6.20407,6.27669,1.71564,5.82465,6.27627,-0.967176,...,-0.045611,9.10294,-3.609620,-2.17721,9.05184,-3.615420,-1.75333,0.024549,0.036445,-0.004679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977967,9,1940.78,0,-6.51915,6.87682,2.34395,-6.67159,6.87843,2.50735,0.007735,...,0.038095,9.30922,-0.563602,-3.39028,9.37794,-0.365044,-3.03688,-0.040479,0.028883,-0.016737
977968,9,1940.79,0,-6.47548,6.95375,2.49829,-6.71706,6.87873,2.47720,0.011587,...,-0.014263,9.27478,-0.412133,-3.31439,9.33258,-0.516377,-3.09669,-0.005168,0.040632,-0.015746
977969,9,1940.80,0,-6.58698,6.84148,2.57398,-6.79405,6.81875,2.34150,0.020748,...,-0.045272,9.27098,-0.296942,-3.46950,9.39297,-0.334790,-3.03706,0.022185,0.068296,0.001916
977970,9,1940.81,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.044441,9.53916,-0.376467,-3.23472,9.34807,-0.198639,-3.00699,-0.005940,-0.011902,0.006604
977971,9,1940.82,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.039345,9.39138,-0.642262,-3.11882,9.43867,-0.319470,-2.88600,-0.042861,-0.023277,0.033183

In [ ]:
cols_comunes = ["Subject", "timestamp", "activityID"]

PAMAP2_FINAL_HAND = PAMAP2_FINAL.loc[:, cols_comunes + ["IMU_hand_x_accel_16g", "IMU_hand_y_accel_16g", "IMU_hand_z_accel_16g", "IMU_hand_x_accel_6g", "IMU_hand_y_accel_6g", "IMU_hand_z_accel_6g", "IMU_hand_x_gyro", "IMU_hand_y_gyro", "IMU_hand_z_gyro"]]

PAMAP2_FINAL_CHEST = PAMAP2_FINAL.loc[:, cols_comunes + ["IMU_chest_x_accel_16g", "IMU_chest_y_accel_16g", "IMU_chest_z_accel_16g", "IMU_chest_x_accel_6g", "IMU_chest_y_accel_6g", "IMU_chest_z_accel_6g", "IMU_chest_x_gyro", "IMU_chest_y_gyro", "IMU_chest_z_gyro"]]

PAMAP2_FINAL_ANKLE = PAMAP2_FINAL.loc[:, cols_comunes + ["IMU_ankle_x_accel_16g", "IMU_ankle_y_accel_16g", "IMU_ankle_z_accel_16g", "IMU_ankle_x_accel_6g", "IMU_ankle_y_accel_6g", "IMU_ankle_z_accel_6g", "IMU_ankle_x_gyro", "IMU_ankle_y_gyro", "IMU_ankle_z_gyro"]]

In [ ]:
PAMAP2_FINAL_ANKLE.insert(12,'Code', 203)
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_x_accel_16g': 'X_Acc'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_y_accel_16g': 'Y_Acc'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_z_accel_16g': 'Z_Acc'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_x_accel_6g': 'X_Acc_6'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_y_accel_6g': 'Y_Acc_6'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_z_accel_6g': 'Z_Acc_6'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_x_gyro': 'X_Gyro'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_y_gyro': 'Y_Gyro'})
PAMAP2_FINAL_ANKLE = PAMAP2_FINAL_ANKLE.rename(columns={'IMU_ankle_z_gyro': 'Z_Gyro'})
PAMAP2_FINAL_ANKLE

,Subject,timestamp,activityID,X_Acc,Y_Acc,Z_Acc,X_Acc_6,Y_Acc_6,Z_Acc_6,X_Gyro,Y_Gyro,Z_Gyro,Code
0,1,10.03,0,9.06112,-3.608100,-2.33201,9.05153,-3.615510,-1.82901,-0.013780,0.009471,0.003633,203
1,1,10.04,0,9.06352,-3.570780,-2.25504,9.06644,-3.555050,-1.85955,-0.026320,0.070031,0.001804,203
2,1,10.05,0,9.06611,-3.495480,-2.17830,9.05161,-3.539870,-1.81412,-0.049060,-0.002170,0.012096,203
3,1,10.06,0,9.03340,-3.648730,-1.98473,9.02174,-3.585200,-1.76841,-0.031388,-0.008545,0.007356,203
4,1,10.07,0,9.10294,-3.609620,-2.17721,9.05184,-3.615420,-1.75333,0.024549,0.036445,-0.004679,203
...,...,...,...,...,...,...,...,...,...,...,...,...,...
977967,9,1940.78,0,9.30922,-0.563602,-3.39028,9.37794,-0.365044,-3.03688,-0.040479,0.028883,-0.016737,203
977968,9,1940.79,0,9.27478,-0.412133,-3.31439,9.33258,-0.516377,-3.09669,-0.005168,0.040632,-0.015746,203
977969,9,1940.80,0,9.27098,-0.296942,-3.46950,9.39297,-0.334790,-3.03706,0.022185,0.068296,0.001916,203
977970,9,1940.81,0,9.53916,-0.376467,-3.23472,9.34807,-0.198639,-3.00699,-0.005940,-0.011902,0.006604,203
977971,9,1940.82,0,9.39138,-0.642262,-3.11882,9.43867,-0.319470,-2.88600,-0.042861,-0.023277,0.033183,203

In [ ]:
PAMAP2_FINAL_CHEST.insert(12,'Code', 204)
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_x_accel_16g': 'X_Acc'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_y_accel_16g': 'Y_Acc'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_z_accel_16g': 'Z_Acc'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_x_accel_6g': 'X_Acc_6'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_y_accel_6g': 'Y_Acc_6'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_z_accel_6g': 'Z_Acc_6'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_x_gyro': 'X_Gyro'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_y_gyro': 'Y_Gyro'})
PAMAP2_FINAL_CHEST = PAMAP2_FINAL_CHEST.rename(columns={'IMU_chest_z_gyro': 'Z_Gyro'})
#PAMAP2_FINAL_CHEST.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/DATASETS_SEPARADOS/PAMAP2_FINAL_CHEST_WITH_CODE.csv', index=False)

In [ ]:
PAMAP2_FINAL_HAND.insert(12,'Code', 201)
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_x_accel_16g': 'X_Acc'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_y_accel_16g': 'Y_Acc'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_z_accel_16g': 'Z_Acc'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_x_accel_6g': 'X_Acc_6'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_y_accel_6g': 'Y_Acc_6'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_z_accel_6g': 'Z_Acc_6'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_x_gyro': 'X_Gyro'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_y_gyro': 'Y_Gyro'})
PAMAP2_FINAL_HAND = PAMAP2_FINAL_HAND.rename(columns={'IMU_hand_z_gyro': 'Z_Gyro'})

In [ ]:
PAMAP2_FINAL_HAND

,Subject,timestamp,activityID,X_Acc,Y_Acc,Z_Acc,X_Acc_6,Y_Acc_6,Z_Acc_6,X_Gyro,Y_Gyro,Z_Gyro,Code
0,1,10.03,0,1.99964,6.94837,5.08845,2.62244,7.73457,4.64028,-1.636280,1.250160,0.480475,201
1,1,10.04,0,1.80990,6.45729,5.16424,2.19725,6.93762,5.06528,-1.624550,1.275710,0.459727,201
2,1,10.05,0,1.82756,5.93151,5.78208,2.01408,6.28989,5.44441,-1.468110,1.224660,0.449260,201
3,1,10.06,0,1.75760,5.78202,5.97397,1.83344,5.83858,5.92881,-1.242220,1.185760,0.410845,201
4,1,10.07,0,1.50670,6.20407,6.27669,1.71564,5.82465,6.27627,-0.967176,1.143680,0.407230,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...
977967,9,1940.78,0,-6.51915,6.87682,2.34395,-6.67159,6.87843,2.50735,0.007735,0.022994,-0.002261,201
977968,9,1940.79,0,-6.47548,6.95375,2.49829,-6.71706,6.87873,2.47720,0.011587,0.053199,0.028846,201
977969,9,1940.80,0,-6.58698,6.84148,2.57398,-6.79405,6.81875,2.34150,0.020748,0.031785,0.004877,201
977970,9,1940.81,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201
977971,9,1940.82,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201

In [ ]:
PAMAP2_FINAL_ORGANIZED = pd.concat([PAMAP2_FINAL_HAND, PAMAP2_FINAL_CHEST, PAMAP2_FINAL_ANKLE])

In [ ]:
PAMAP2_FINAL_ORGANIZED

,Subject,timestamp,activityID,X_Acc,Y_Acc,Z_Acc,X_Acc_6,Y_Acc_6,Z_Acc_6,X_Gyro,Y_Gyro,Z_Gyro,Code
0,1,10.03,0,1.99964,6.948370,5.08845,2.62244,7.734570,4.64028,-1.636280,1.250160,0.480475,201
1,1,10.04,0,1.80990,6.457290,5.16424,2.19725,6.937620,5.06528,-1.624550,1.275710,0.459727,201
2,1,10.05,0,1.82756,5.931510,5.78208,2.01408,6.289890,5.44441,-1.468110,1.224660,0.449260,201
3,1,10.06,0,1.75760,5.782020,5.97397,1.83344,5.838580,5.92881,-1.242220,1.185760,0.410845,201
4,1,10.07,0,1.50670,6.204070,6.27669,1.71564,5.824650,6.27627,-0.967176,1.143680,0.407230,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...
977967,9,1940.78,0,9.30922,-0.563602,-3.39028,9.37794,-0.365044,-3.03688,-0.040479,0.028883,-0.016737,203
977968,9,1940.79,0,9.27478,-0.412133,-3.31439,9.33258,-0.516377,-3.09669,-0.005168,0.040632,-0.015746,203
977969,9,1940.80,0,9.27098,-0.296942,-3.46950,9.39297,-0.334790,-3.03706,0.022185,0.068296,0.001916,203
977970,9,1940.81,0,9.53916,-0.376467,-3.23472,9.34807,-0.198639,-3.00699,-0.005940,-0.011902,0.006604,203
977971,9,1940.82,0,9.39138,-0.642262,-3.11882,9.43867,-0.319470,-2.88600,-0.042861,-0.023277,0.033183,203

In [ ]:
PAMAP2_FINAL_ORGANIZED.insert(13,'Dataset', 5)
PAMAP2_FINAL_ORGANIZED.insert(14,'Frequency', 100)
PAMAP2_FINAL_ORGANIZED.insert(15,'Trial', np.nan)
PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.rename(columns={'activityID': 'Activity'})
PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.rename(columns={'timestamp': 'TimeStamp'})
PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.rename(columns={'Subject': 'User'})

PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])
PAMAP2_FINAL_ORGANIZED

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,5,0,1.99964,6.948370,5.08845,-1.636280,1.250160,0.480475,2.62244,7.734570,4.64028,201,10.03,100,1,NaN
1,5,0,1.80990,6.457290,5.16424,-1.624550,1.275710,0.459727,2.19725,6.937620,5.06528,201,10.04,100,1,NaN
2,5,0,1.82756,5.931510,5.78208,-1.468110,1.224660,0.449260,2.01408,6.289890,5.44441,201,10.05,100,1,NaN
3,5,0,1.75760,5.782020,5.97397,-1.242220,1.185760,0.410845,1.83344,5.838580,5.92881,201,10.06,100,1,NaN
4,5,0,1.50670,6.204070,6.27669,-0.967176,1.143680,0.407230,1.71564,5.824650,6.27627,201,10.07,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977967,5,0,9.30922,-0.563602,-3.39028,-0.040479,0.028883,-0.016737,9.37794,-0.365044,-3.03688,203,1940.78,100,9,NaN
977968,5,0,9.27478,-0.412133,-3.31439,-0.005168,0.040632,-0.015746,9.33258,-0.516377,-3.09669,203,1940.79,100,9,NaN
977969,5,0,9.27098,-0.296942,-3.46950,0.022185,0.068296,0.001916,9.39297,-0.334790,-3.03706,203,1940.80,100,9,NaN
977970,5,0,9.53916,-0.376467,-3.23472,-0.005940,-0.011902,0.006604,9.34807,-0.198639,-3.00699,203,1940.81,100,9,NaN
977971,5,0,9.39138,-0.642262,-3.11882,-0.042861,-0.023277,0.033183,9.43867,-0.319470,-2.88600,203,1940.82,100,9,NaN

In [ ]:
PAMAP2_FINAL_ORGANIZED['X_Gyro'] = np.degrees(PAMAP2_FINAL_ORGANIZED['X_Gyro'])
PAMAP2_FINAL_ORGANIZED['Y_Gyro'] = np.degrees(PAMAP2_FINAL_ORGANIZED['Y_Gyro'])
PAMAP2_FINAL_ORGANIZED['Z_Gyro'] = np.degrees(PAMAP2_FINAL_ORGANIZED['Z_Gyro'])
PAMAP2_FINAL_ORGANIZED = PAMAP2_FINAL_ORGANIZED.drop(['X_Acc_6', 'Y_Acc_6', 'Z_Acc_6'], axis=1)

In [ ]:
PAMAP2_FINAL_ORGANIZED

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,5,0,1.99964,6.948370,5.08845,-93.751938,71.628892,27.529190,201,10.03,100,1,NaN
1,5,0,1.80990,6.457290,5.16424,-93.079859,73.092799,26.340417,201,10.04,100,1,NaN
2,5,0,1.82756,5.931510,5.78208,-84.116507,70.167849,25.740702,201,10.05,100,1,NaN
3,5,0,1.75760,5.782020,5.97397,-71.173963,67.939044,23.539685,201,10.06,100,1,NaN
4,5,0,1.50670,6.204070,6.27669,-55.415103,65.528037,23.332560,201,10.07,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
977967,5,0,9.30922,-0.563602,-3.39028,-2.319247,1.654868,-0.958954,203,1940.78,100,9,NaN
977968,5,0,9.27478,-0.412133,-3.31439,-0.296083,2.328031,-0.902179,203,1940.79,100,9,NaN
977969,5,0,9.27098,-0.296942,-3.46950,1.271118,3.913061,0.109759,203,1940.80,100,9,NaN
977970,5,0,9.53916,-0.376467,-3.23472,-0.340338,-0.681952,0.378364,203,1940.81,100,9,NaN
977971,5,0,9.39138,-0.642262,-3.11882,-2.455766,-1.333691,1.901246,203,1940.82,100,9,NaN

In [ ]:
PAMAP2_FINAL_ORGANIZED.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5_OPTIONAL.csv')

##Union de protocol y optional

In [ ]:
protocol = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5.csv')

In [ ]:
protocol

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,5,0,2.37223,8.600740,3.51048,-5.283668,3.255059,-0.907823,201,8.38,100,1,NaN
1,1,5,0,2.18837,8.565600,3.66179,-1.398773,2.736360,0.370952,201,8.39,100,1,NaN
2,2,5,0,2.37357,8.601070,3.54898,-3.321786,1.866370,-0.400392,201,8.40,100,1,NaN
3,3,5,0,2.07473,8.528530,3.66021,-0.134737,1.879863,-0.214703,201,8.41,100,1,NaN
4,4,5,0,2.22936,8.831220,3.70000,0.702968,1.048799,-3.055286,201,8.42,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617594,2872528,5,0,9.38737,-0.565040,-3.27370,-2.165070,-3.591076,-7.281377,203,100.19,100,9,NaN
8617595,2872529,5,0,9.45875,-1.020820,-3.30873,-3.947885,-1.547341,-5.145602,203,100.20,100,9,NaN
8617596,2872530,5,0,9.57580,-0.528578,-3.23340,-4.061566,-2.178586,-3.707530,203,100.21,100,9,NaN
8617597,2872531,5,0,9.49894,-0.489493,-3.31161,1.086408,-1.478025,-3.687413,203,100.22,100,9,NaN
8617598,2872532,5,0,9.42169,-0.526345,-3.38935,-1.574041,0.679877,-2.455560,203,100.23,100,9,NaN

In [ ]:
optional = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5_OPTIONAL.csv')

In [ ]:
optional

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,5,0,1.99964,6.948370,5.08845,-93.751938,71.628892,27.529190,201,10.03,100,1,NaN
1,1,5,0,1.80990,6.457290,5.16424,-93.079859,73.092799,26.340417,201,10.04,100,1,NaN
2,2,5,0,1.82756,5.931510,5.78208,-84.116507,70.167849,25.740702,201,10.05,100,1,NaN
3,3,5,0,1.75760,5.782020,5.97397,-71.173963,67.939044,23.539685,201,10.06,100,1,NaN
4,4,5,0,1.50670,6.204070,6.27669,-55.415103,65.528037,23.332560,201,10.07,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933911,977967,5,0,9.30922,-0.563602,-3.39028,-2.319247,1.654868,-0.958954,203,1940.78,100,9,NaN
2933912,977968,5,0,9.27478,-0.412133,-3.31439,-0.296083,2.328031,-0.902179,203,1940.79,100,9,NaN
2933913,977969,5,0,9.27098,-0.296942,-3.46950,1.271118,3.913061,0.109759,203,1940.80,100,9,NaN
2933914,977970,5,0,9.53916,-0.376467,-3.23472,-0.340338,-0.681952,0.378364,203,1940.81,100,9,NaN
2933915,977971,5,0,9.39138,-0.642262,-3.11882,-2.455766,-1.333691,1.901246,203,1940.82,100,9,NaN

In [ ]:
unique_activities = optional["Activity"].unique()
unique_activities

array([ 0, 11,  9, 19, 18, 10, 20])

In [ ]:
dataset5 = pd.concat([protocol, optional])

In [ ]:
dataset5

,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,5,0,2.37223,8.600740,3.51048,-5.283668,3.255059,-0.907823,201,8.38,100,1,NaN
1,1,5,0,2.18837,8.565600,3.66179,-1.398773,2.736360,0.370952,201,8.39,100,1,NaN
2,2,5,0,2.37357,8.601070,3.54898,-3.321786,1.866370,-0.400392,201,8.40,100,1,NaN
3,3,5,0,2.07473,8.528530,3.66021,-0.134737,1.879863,-0.214703,201,8.41,100,1,NaN
4,4,5,0,2.22936,8.831220,3.70000,0.702968,1.048799,-3.055286,201,8.42,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933911,977967,5,0,9.30922,-0.563602,-3.39028,-2.319247,1.654868,-0.958954,203,1940.78,100,9,NaN
2933912,977968,5,0,9.27478,-0.412133,-3.31439,-0.296083,2.328031,-0.902179,203,1940.79,100,9,NaN
2933913,977969,5,0,9.27098,-0.296942,-3.46950,1.271118,3.913061,0.109759,203,1940.80,100,9,NaN
2933914,977970,5,0,9.53916,-0.376467,-3.23472,-0.340338,-0.681952,0.378364,203,1940.81,100,9,NaN
2933915,977971,5,0,9.39138,-0.642262,-3.11882,-2.455766,-1.333691,1.901246,203,1940.82,100,9,NaN

In [ ]:
dataset5.to_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5_FINAL.csv')

####Describe

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset_5.csv')

In [ ]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
count,1.155152e+07,1.155152e+07,11551515.0,1.155152e+07,1.151931e+07,1.151931e+07,1.151931e+07,1.151931e+07,1.151931e+07,1.151931e+07,1.155152e+07,1.155152e+07,11551515.0,1.155152e+07,0.0
mean,3.587013e+06,1.195671e+06,5.0,6.868323e+00,1.855237e+00,3.981884e+00,-2.147771e-01,1.641827e-01,1.875553e-01,-3.694172e-01,2.026667e+02,1.646636e+03,100.0,4.670896e+00,NaN
std,2.515788e+06,8.385961e+05,0.0,6.882659e+00,7.342227e+00,6.633443e+00,4.760973e+00,5.528555e+01,3.883666e+01,7.163581e+01,1.247219e+00,1.077869e+03,0.0,2.616087e+00,NaN
min,0.000000e+00,0.000000e+00,5.0,0.000000e+00,-1.550680e+02,-1.576150e+02,-1.595850e+02,-1.666018e+03,-1.272694e+03,-9.568223e+02,2.010000e+02,5.640000e+00,100.0,1.000000e+00,NaN
25%,1.443939e+06,4.813130e+05,5.0,0.000000e+00,-1.389060e+00,-1.021280e-01,-2.999670e+00,-6.916517e+00,-5.484702e+00,-7.287278e+00,2.010000e+02,7.402900e+02,100.0,2.000000e+00,NaN
50%,2.887878e+06,9.626260e+05,5.0,4.000000e+00,7.473310e-01,3.796150e+00,-7.655880e-01,7.600572e-02,-3.001714e-04,-3.893844e-01,2.030000e+02,1.495380e+03,100.0,5.000000e+00,NaN
75%,5.729720e+06,1.909906e+06,5.0,1.200000e+01,8.961945e+00,8.951100e+00,2.265510e+00,6.011129e+00,6.371061e+00,4.450977e+00,2.040000e+02,2.474060e+03,100.0,7.000000e+00,NaN
max,8.617598e+06,2.872532e+06,5.0,2.400000e+01,1.576880e+02,1.576110e+02,1.605160e+02,1.513514e+03,1.322266e+03,1.109017e+03,2.040000e+02,4.475630e+03,100.0,9.000000e+00,NaN

##Revisión de las actividades

In [ ]:
x = '/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Protocol/subject101.dat'

In [ ]:
import os
import pandas as pd

ruta = '/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Optional/'
archivos_txt = [f for f in os.listdir(ruta) if f.endswith('.dat')]

columna1_valores_unicos = []

for archivo in archivos_txt:
    file_path = os.path.join(ruta, archivo)
    df = pd.read_csv(file_path, sep=' ', header=None)
    columna1_valores = df.iloc[:, 1].unique()
    columna1_valores_unicos.extend(columna1_valores)

print(columna1_valores_unicos)

[0, 11, 9, 19, 18, 0, 10, 19, 0, 10, 19, 18, 0, 10, 19, 18, 20, 0, 10, 19, 18, 20]

In [ ]:
f = [0, 1, 2, 3, 17, 16, 12, 13, 4, 7, 6, 5, 24, 0, 1, 2, 3, 17, 16, 12, 13, 4, 7, 6, 5, 24, 0, 1, 2, 3, 17, 16, 13, 12, 4, 0, 1, 2, 3, 17, 16, 12, 13, 4, 7, 6, 5, 0, 1, 2, 3, 17, 16, 12, 13, 4, 7, 6, 5, 24, 0, 1, 2, 3, 17, 16, 12, 13, 4, 7, 6, 5, 24, 0, 1, 2, 3, 17, 16, 12, 13, 4, 7, 6, 5, 0, 1, 2, 3, 17, 16, 12, 13, 4, 6, 7, 5, 24, 0, 24]
f.unique()

AttributeError: ignored

## Actividades

In [ ]:
dataset5 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5_FINAL.csv')
dataset5

,Unnamed: 0.1,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,0,0,5,0,2.37223,8.600740,3.51048,-5.283668,3.255059,-0.907823,201,8.38,100,1,NaN
1,1,1,5,0,2.18837,8.565600,3.66179,-1.398773,2.736360,0.370952,201,8.39,100,1,NaN
2,2,2,5,0,2.37357,8.601070,3.54898,-3.321786,1.866370,-0.400392,201,8.40,100,1,NaN
3,3,3,5,0,2.07473,8.528530,3.66021,-0.134737,1.879863,-0.214703,201,8.41,100,1,NaN
4,4,4,5,0,2.22936,8.831220,3.70000,0.702968,1.048799,-3.055286,201,8.42,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11551510,2933911,977967,5,0,9.30922,-0.563602,-3.39028,-2.319247,1.654868,-0.958954,203,1940.78,100,9,NaN
11551511,2933912,977968,5,0,9.27478,-0.412133,-3.31439,-0.296083,2.328031,-0.902179,203,1940.79,100,9,NaN
11551512,2933913,977969,5,0,9.27098,-0.296942,-3.46950,1.271118,3.913061,0.109759,203,1940.80,100,9,NaN
11551513,2933914,977970,5,0,9.53916,-0.376467,-3.23472,-0.340338,-0.681952,0.378364,203,1940.81,100,9,NaN
11551514,2933915,977971,5,0,9.39138,-0.642262,-3.11882,-2.455766,-1.333691,1.901246,203,1940.82,100,9,NaN

In [ ]:
dataset5["Activity"].unique()

array([ 0,  1,  2,  3, 17, 16, 12, 13,  4,  7,  6,  5, 24, 11,  9, 19, 18,
       10, 20])

In [ ]:
dataset5["Code"].unique()

201
204
203

In [ ]:
dataset5 = dataset5[dataset5['Activity'] != 0]

In [ ]:
dataset5

,Unnamed: 0.1,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
2928,2928,2928,5,1,2.21530,8.279150,5.58753,-0.272157,2.153107,-0.638561,201,37.66,100,1,NaN
2929,2929,2929,5,1,2.29196,7.672880,5.74467,-9.838258,1.459828,-0.546499,201,37.67,100,1,NaN
2930,2930,2930,5,1,2.29090,7.142400,5.82342,-13.650204,0.642492,0.047597,201,37.68,100,1,NaN
2931,2931,2931,5,1,2.21800,7.143650,5.89930,-11.053043,1.091679,0.766285,201,37.69,100,1,NaN
2932,2932,2932,5,1,2.30106,7.258570,6.09259,-4.008493,-1.050088,0.262511,201,37.70,100,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11551046,2933447,977503,5,20,9.26409,-0.561116,-3.66088,-0.787920,0.672469,-0.648193,203,1936.14,100,9,NaN
11551047,2933448,977504,5,20,9.30900,-0.183274,-3.46982,-0.549617,-0.806427,-3.008412,203,1936.15,100,9,NaN
11551048,2933449,977505,5,20,9.30959,-0.069368,-3.47052,-0.620244,-1.458882,-3.285518,203,1936.16,100,9,NaN
11551049,2933450,977506,5,20,9.23414,-0.182800,-3.47059,-1.111630,-0.168581,-1.920692,203,1936.17,100,9,NaN
11551050,2933451,977507,5,20,9.31399,-0.070653,-3.31611,-0.281027,1.259138,-0.686495,203,1936.18,100,9,NaN

In [ ]:
mapping = {
    1:18,
    2:16,
    3:17,
    4:6,
    5:9,
    6:24,
    7:23,
    9:26,
    10:16,
    11:12,
    12:13,
    13:14,
    16:22,
    17:21,
    18:27,
    19:28,
    20:29,
    24:25
}

ruta_salida = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset5.csv'

data = dataset5.copy()

data['Activity'] = data['Activity'].map(mapping)
data = data.reset_index(drop=True)

data.to_csv(ruta_salida, index=False)

## Resampling

In [ ]:
dataset5Final = resample_dataframe(data)

In [ ]:
dataset5Final

,Unnamed: 0.1,Unnamed: 0,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,2928,2928,5,18,2.21530,8.279150,5.58753,-0.272157,2.153107,-0.638561,201,37.66,50,1,NaN
4,2932,2932,5,18,2.30106,7.258570,6.09259,-4.008493,-1.050088,0.262511,201,37.70,50,1,NaN
7,2935,2935,5,18,2.32815,7.634310,5.70686,11.477949,-0.530891,3.928617,201,37.73,50,1,NaN
8,2936,2936,5,18,2.25096,7.785980,5.62821,11.693954,-3.910804,2.864806,201,37.74,50,1,NaN
9,2937,2937,5,18,2.14107,7.522620,5.78141,9.814251,-3.174816,1.236225,201,37.75,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8174848,2933441,977497,5,29,9.22943,-0.029319,-3.66454,1.545405,0.026668,3.098017,203,1936.08,50,9,NaN
8174849,2933442,977498,5,29,9.45859,0.005942,-3.50805,-0.468242,-1.899882,3.390592,203,1936.09,50,9,NaN
8174850,2933443,977499,5,29,9.34552,-0.145221,-3.50827,0.843640,-0.635284,4.082914,203,1936.10,50,9,NaN
8174857,2933450,977506,5,29,9.23414,-0.182800,-3.47059,-1.111630,-0.168581,-1.920692,203,1936.17,50,9,NaN
8174858,2933451,977507,5,29,9.31399,-0.070653,-3.31611,-0.281027,1.259138,-0.686495,203,1936.18,50,9,NaN

In [ ]:
dataset5Final = dataset5Final.drop(columns=['Unnamed: 0.1','Unnamed: 0'])

In [ ]:
dataset5Final

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,5,18,2.21530,8.279150,5.58753,-0.272157,2.153107,-0.638561,201,37.66,50,1,NaN
4,5,18,2.30106,7.258570,6.09259,-4.008493,-1.050088,0.262511,201,37.70,50,1,NaN
7,5,18,2.32815,7.634310,5.70686,11.477949,-0.530891,3.928617,201,37.73,50,1,NaN
8,5,18,2.25096,7.785980,5.62821,11.693954,-3.910804,2.864806,201,37.74,50,1,NaN
9,5,18,2.14107,7.522620,5.78141,9.814251,-3.174816,1.236225,201,37.75,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8174848,5,29,9.22943,-0.029319,-3.66454,1.545405,0.026668,3.098017,203,1936.08,50,9,NaN
8174849,5,29,9.45859,0.005942,-3.50805,-0.468242,-1.899882,3.390592,203,1936.09,50,9,NaN
8174850,5,29,9.34552,-0.145221,-3.50827,0.843640,-0.635284,4.082914,203,1936.10,50,9,NaN
8174857,5,29,9.23414,-0.182800,-3.47059,-1.111630,-0.168581,-1.920692,203,1936.17,50,9,NaN
8174858,5,29,9.31399,-0.070653,-3.31611,-0.281027,1.259138,-0.686495,203,1936.18,50,9,NaN

In [ ]:
dataset5Final.to_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset5.csv', index=False)

In [ ]:
dataset5 = dataset5Final.copy()

## Análisis Gráfico Dataset 5

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/5_PAMAP2/PAMAP2_Dataset/Dataset5_Final/Dataset5.csv')

###Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(dataset5)

### Valores Máximo y Mínimos Acelerometro

In [ ]:
grafico_acelerometro_max_min(dataset5)

### Valores Válidos Giroscopio

In [ ]:
grafico_giroscopio_valido(dataset5)

###Valores Máximo y Mínimos Giroscopio

In [ ]:
grafico_giroscopio_max_min(dataset5)

###Actividades Válidas

In [ ]:
grafico_activity(dataset5)

# Dataset Número 6. DialiAC.

## Preparación del Dataset Número 6

El dataset se presenta mediante 19 archivos txt los cuales representan a cada sujeto, dento de estos archivos se encuentran los datos raw de los 4 sensores así como su etiquetado en orden, esto es importante puesto que al momento de unir todos los archivos hay que extraer el valor del sujeto y ordenar por sujeto,arctividad y código, para que el orden se mantenga. Sin embargo esto de debe preguntar porque para el timestamp probablemente sea mejor dejar las filas como estan para adicionar este factor con la ayuda de la frecuencia.

In [ ]:

import os
import pandas as pd

folder_path = "/content/drive/MyDrive/TESIS_DATASET/6. Daliac/Archivos_Raw"

# Obtener la lista de archivos ordenados
file_list = sorted([file for file in os.listdir(folder_path) if file.endswith('.txt')])

# Crear una lista para almacenar los DataFrames
dfs = []

# Iterar sobre los archivos y agregar la columna 'User'
for i, file_name in enumerate(file_list):
    file_path = os.path.join(folder_path, file_name)
    df = pd.read_csv(file_path, delimiter=',')
    header = ['X_Acc_W', 'Y_Acc_W', 'Z_Acc_W', 'X_Gyro_W', 'Y_Gyro_W', 'Z_Gyro_W',
    'X_Acc_C', 'Y_Acc_C', 'Z_Acc_C', 'X_Gyro_C', 'Y_Gyro_C', 'Z_Gyro_C',
    'X_Acc_H', 'Y_Acc_H', 'Z_Acc_H', 'X_Gyro_H', 'Y_Gyro_H', 'Z_Gyro_H',
    'X_Acc_A', 'Y_Acc_A', 'Z_Acc_A', 'X_Gyro_A', 'Y_Gyro_A', 'Z_Gyro_A',
    'Aticity']
    df.columns = header
    df['User'] = i + 1  # Asignar el valor del nombre como la columna 'User'
    dfs.append(df)

# Concatenamos los archivos resultantes
concatenated_df = pd.concat(dfs, axis=0)

In [ ]:
concatenated_df

,X_Acc_W,Y_Acc_W,Z_Acc_W,X_Gyro_W,Y_Gyro_W,Z_Gyro_W,X_Acc_C,Y_Acc_C,Z_Acc_C,X_Gyro_C,...,Y_Gyro_H,Z_Gyro_H,X_Acc_A,Y_Acc_A,Z_Acc_A,X_Gyro_A,Y_Gyro_A,Z_Gyro_A,Aticity,User
0,0.057310,0.16003,-0.009739,238.560,51.564,174.5900,-0.15410,-0.86636,0.069517,46.727,...,-18.0210,37.482,-0.942720,-0.321320,-0.498810,-82.6060,36.087,-1.5711,1,1
1,0.022143,0.18408,-0.038329,243.690,59.620,166.1700,-0.15410,-0.89867,0.053434,57.346,...,-20.5840,37.116,-0.922710,-0.217220,-0.467560,-75.2830,37.552,-5.9651,1,1
2,-0.001302,0.20412,-0.030160,246.620,65.112,156.2900,-0.16981,-0.90675,0.049414,65.768,...,-23.5140,35.285,-0.890700,-0.136260,-0.451930,-69.4240,37.552,-8.8945,1,1
3,-0.032562,0.20813,-0.026076,250.640,70.605,145.3000,-0.16981,-0.90675,0.081579,69.063,...,-24.2460,33.088,-0.898700,-0.109270,-0.487090,-63.5660,39.017,-10.3590,1,1
4,-0.067730,0.20813,-0.034244,253.570,75.731,134.3200,-0.14625,-0.89867,0.133850,69.796,...,-23.1470,32.722,-0.906710,-0.089996,-0.530070,-57.7070,37.552,-11.8240,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248849,-0.380330,-0.61754,-0.115930,-114.420,191.810,25.5640,-0.25227,-0.53115,0.105700,-31.998,...,20.4260,43.341,-0.046301,1.294100,-0.190160,9.6677,-21.034,73.1270,13,19
248850,-0.364700,-0.55742,-0.144520,-106.370,182.650,18.6070,-0.29939,-0.66847,0.061476,-37.491,...,8.3429,41.144,-0.198370,1.082000,-0.100300,-25.4840,-21.034,84.8440,13,19
248851,-0.372510,-0.46924,-0.136350,-100.870,176.060,11.2840,-0.28369,-0.76136,0.037352,-33.097,...,-15.0920,38.214,-0.250400,0.735060,-0.026064,-62.1010,-29.822,108.2800,13,19
248852,-0.431130,-0.38106,-0.071003,-95.749,172.030,3.5944,-0.28761,-1.00370,0.025290,-23.577,...,-32.6680,37.116,-0.130340,0.145180,0.212260,-92.8590,-41.540,140.5000,13,19
248853,-0.485830,-0.26483,0.018851,-93.918,169.840,-4.8274,-0.27583,-1.25810,0.005188,-18.817,...,-30.1050,35.651,0.285860,0.854580,0.532640,-104.5800,-41.540,178.5800,13,19

In [ ]:
concatenated_df.to_csv("/content/drive/MyDrive/TESIS_DATASET/6. Daliac/Archivos_txts_unidos/Archivos_Unidos.csv")

In [ ]:
Dataset_6_df = pd.read_csv("/content/drive/MyDrive/TESIS_DATASET/6. Daliac/Archivos_txts_unidos/Archivos_Unidos.csv")

In [ ]:
# Separamos el dataset por las ubicaciones
cols_comunes = ["User", "Aticity"]


Dataset_6_Wrist = Dataset_6_df.loc[:, cols_comunes + ["X_Acc_W",	"Y_Acc_W",	"Z_Acc_W",	"X_Gyro_W",	"Y_Gyro_W",	"Z_Gyro_W"]]

Dataset_6_Chest = Dataset_6_df.loc[:, cols_comunes + ["X_Acc_C",	"Y_Acc_C",	"Z_Acc_C",	"X_Gyro_C",	"Y_Gyro_C",	"Z_Gyro_C"]]

Dataset_6_Hip = Dataset_6_df.loc[:, cols_comunes + ["X_Acc_H",	"Y_Acc_H",	"Z_Acc_H",	"X_Gyro_H",	"Y_Gyro_H",	"Z_Gyro_H"]]

Dataset_6_Ankle = Dataset_6_df.loc[:, cols_comunes + ["X_Acc_A",	"Y_Acc_A",	"Z_Acc_A",	"X_Gyro_A",	"Y_Gyro_A",	"Z_Gyro_A"]]

In [ ]:
Dataset_6_Wrist.insert(8,'Code', 211)
Dataset_6_Wrist = Dataset_6_Wrist.rename(columns={'X_Acc_W': 'X_Acc'})
Dataset_6_Wrist = Dataset_6_Wrist.rename(columns={'Y_Acc_W': 'Y_Acc'})
Dataset_6_Wrist = Dataset_6_Wrist.rename(columns={'Z_Acc_W': 'Z_Acc'})
Dataset_6_Wrist = Dataset_6_Wrist.rename(columns={'X_Gyro_W': 'X_Gyro'})
Dataset_6_Wrist = Dataset_6_Wrist.rename(columns={'Y_Gyro_W': 'Y_Gyro'})
Dataset_6_Wrist = Dataset_6_Wrist.rename(columns={'Z_Gyro_W': 'Z_Gyro'})

Dataset_6_Wrist.insert(9,'Dataset', 6)
Dataset_6_Wrist.insert(10,'Frequency',  204.8)
Dataset_6_Wrist.insert(11,'Trial', np.nan)
Dataset_6_Wrist.insert(12,'X_Acc_6', np.nan)
Dataset_6_Wrist.insert(13,'Y_Acc_6', np.nan)
Dataset_6_Wrist.insert(14,'Z_Acc_6', np.nan)
Dataset_6_Wrist.insert(15,'TimeStamp', np.nan)
Dataset_6_Wrist = Dataset_6_Wrist.rename(columns={'Aticity': 'Activity'})


Dataset_6_Wrist = Dataset_6_Wrist.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])

In [ ]:
Dataset_6_Chest.insert(8,'Code', 204)
Dataset_6_Chest = Dataset_6_Chest.rename(columns={'X_Acc_C': 'X_Acc'})
Dataset_6_Chest = Dataset_6_Chest.rename(columns={'Y_Acc_C': 'Y_Acc'})
Dataset_6_Chest = Dataset_6_Chest.rename(columns={'Z_Acc_C': 'Z_Acc'})
Dataset_6_Chest = Dataset_6_Chest.rename(columns={'X_Gyro_C': 'X_Gyro'})
Dataset_6_Chest = Dataset_6_Chest.rename(columns={'Y_Gyro_C': 'Y_Gyro'})
Dataset_6_Chest = Dataset_6_Chest.rename(columns={'Z_Gyro_C': 'Z_Gyro'})

Dataset_6_Chest.insert(9,'Dataset', 6)
Dataset_6_Chest.insert(10,'Frequency',  204.8)
Dataset_6_Chest.insert(11,'Trial', np.nan)
Dataset_6_Chest.insert(12,'X_Acc_6', np.nan)
Dataset_6_Chest.insert(13,'Y_Acc_6', np.nan)
Dataset_6_Chest.insert(14,'Z_Acc_6', np.nan)
Dataset_6_Chest.insert(15,'TimeStamp', np.nan)
Dataset_6_Chest = Dataset_6_Chest.rename(columns={'Aticity': 'Activity'})


Dataset_6_Chest = Dataset_6_Chest.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])

In [ ]:
Dataset_6_Hip.insert(8,'Code', 202)
Dataset_6_Hip = Dataset_6_Hip.rename(columns={'X_Acc_H': 'X_Acc'})
Dataset_6_Hip = Dataset_6_Hip.rename(columns={'Y_Acc_H': 'Y_Acc'})
Dataset_6_Hip = Dataset_6_Hip.rename(columns={'Z_Acc_H': 'Z_Acc'})
Dataset_6_Hip = Dataset_6_Hip.rename(columns={'X_Gyro_H': 'X_Gyro'})
Dataset_6_Hip = Dataset_6_Hip.rename(columns={'Y_Gyro_H': 'Y_Gyro'})
Dataset_6_Hip = Dataset_6_Hip.rename(columns={'Z_Gyro_H': 'Z_Gyro'})

Dataset_6_Hip.insert(9,'Dataset', 6)
Dataset_6_Hip.insert(10,'Frequency',  204.8)
Dataset_6_Hip.insert(11,'Trial', np.nan)
Dataset_6_Hip.insert(12,'X_Acc_6', np.nan)
Dataset_6_Hip.insert(13,'Y_Acc_6', np.nan)
Dataset_6_Hip.insert(14,'Z_Acc_6', np.nan)
Dataset_6_Hip.insert(15,'TimeStamp', np.nan)
Dataset_6_Hip = Dataset_6_Hip.rename(columns={'Aticity': 'Activity'})


Dataset_6_Hip = Dataset_6_Hip.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])

In [ ]:
Dataset_6_Ankle.insert(8,'Code', 223)
Dataset_6_Ankle = Dataset_6_Ankle.rename(columns={'X_Acc_A': 'X_Acc'})
Dataset_6_Ankle = Dataset_6_Ankle.rename(columns={'Y_Acc_A': 'Y_Acc'})
Dataset_6_Ankle = Dataset_6_Ankle.rename(columns={'Z_Acc_A': 'Z_Acc'})
Dataset_6_Ankle = Dataset_6_Ankle.rename(columns={'X_Gyro_A': 'X_Gyro'})
Dataset_6_Ankle = Dataset_6_Ankle.rename(columns={'Y_Gyro_A': 'Y_Gyro'})
Dataset_6_Ankle = Dataset_6_Ankle.rename(columns={'Z_Gyro_A': 'Z_Gyro'})

Dataset_6_Ankle.insert(9,'Dataset', 6)
Dataset_6_Ankle.insert(10,'Frequency',  204.8)
Dataset_6_Ankle.insert(11,'Trial', np.nan)
Dataset_6_Ankle.insert(12,'X_Acc_6', np.nan)
Dataset_6_Ankle.insert(13,'Y_Acc_6', np.nan)
Dataset_6_Ankle.insert(14,'Z_Acc_6', np.nan)
Dataset_6_Ankle.insert(15,'TimeStamp', np.nan)
Dataset_6_Ankle = Dataset_6_Ankle.rename(columns={'Aticity': 'Activity'})


Dataset_6_Ankle = Dataset_6_Ankle.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])

In [ ]:
Dataset_6_Ankle

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,6,1,-0.942720,-0.321320,-0.498810,-82.6060,36.087,-1.5711,NaN,NaN,NaN,223,NaN,204.8,1,NaN
1,6,1,-0.922710,-0.217220,-0.467560,-75.2830,37.552,-5.9651,NaN,NaN,NaN,223,NaN,204.8,1,NaN
2,6,1,-0.890700,-0.136260,-0.451930,-69.4240,37.552,-8.8945,NaN,NaN,NaN,223,NaN,204.8,1,NaN
3,6,1,-0.898700,-0.109270,-0.487090,-63.5660,39.017,-10.3590,NaN,NaN,NaN,223,NaN,204.8,1,NaN
4,6,1,-0.906710,-0.089996,-0.530070,-57.7070,37.552,-11.8240,NaN,NaN,NaN,223,NaN,204.8,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686818,6,13,-0.046301,1.294100,-0.190160,9.6677,-21.034,73.1270,NaN,NaN,NaN,223,NaN,204.8,19,NaN
4686819,6,13,-0.198370,1.082000,-0.100300,-25.4840,-21.034,84.8440,NaN,NaN,NaN,223,NaN,204.8,19,NaN
4686820,6,13,-0.250400,0.735060,-0.026064,-62.1010,-29.822,108.2800,NaN,NaN,NaN,223,NaN,204.8,19,NaN
4686821,6,13,-0.130340,0.145180,0.212260,-92.8590,-41.540,140.5000,NaN,NaN,NaN,223,NaN,204.8,19,NaN
4686822,6,13,0.285860,0.854580,0.532640,-104.5800,-41.540,178.5800,NaN,NaN,NaN,223,NaN,204.8,19,NaN

In [ ]:
Dataset6_1 = pd.concat([Dataset_6_Wrist, Dataset_6_Chest, Dataset_6_Hip, Dataset_6_Ankle])

In [ ]:
Dataset6_1.to_csv("/content/drive/MyDrive/TESIS_DATASET/6. Daliac/Dataset_6_Final/Dataset_6.csv")

In [ ]:
Dataset6_1

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,6,1,0.057310,0.16003,-0.009739,238.5600,51.564,174.590,NaN,NaN,NaN,211,NaN,204.8,1,NaN
1,6,1,0.022143,0.18408,-0.038329,243.6900,59.620,166.170,NaN,NaN,NaN,211,NaN,204.8,1,NaN
2,6,1,-0.001302,0.20412,-0.030160,246.6200,65.112,156.290,NaN,NaN,NaN,211,NaN,204.8,1,NaN
3,6,1,-0.032562,0.20813,-0.026076,250.6400,70.605,145.300,NaN,NaN,NaN,211,NaN,204.8,1,NaN
4,6,1,-0.067730,0.20813,-0.034244,253.5700,75.731,134.320,NaN,NaN,NaN,211,NaN,204.8,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686818,6,13,-0.046301,1.29410,-0.190160,9.6677,-21.034,73.127,NaN,NaN,NaN,223,NaN,204.8,19,NaN
4686819,6,13,-0.198370,1.08200,-0.100300,-25.4840,-21.034,84.844,NaN,NaN,NaN,223,NaN,204.8,19,NaN
4686820,6,13,-0.250400,0.73506,-0.026064,-62.1010,-29.822,108.280,NaN,NaN,NaN,223,NaN,204.8,19,NaN
4686821,6,13,-0.130340,0.14518,0.212260,-92.8590,-41.540,140.500,NaN,NaN,NaN,223,NaN,204.8,19,NaN
4686822,6,13,0.285860,0.85458,0.532640,-104.5800,-41.540,178.580,NaN,NaN,NaN,223,NaN,204.8,19,NaN

Los indices se dejaron intactos, para que se reconozcan las mismas filas originales. Ahora procedemos a arreglar de mejor manera el dataset

In [ ]:
cantidad_filas_indice = len(Dataset6_1[Dataset6_1.index == 1])
cantidad_filas_indice

4

In [ ]:
Dataset6_1.insert(9,'Dataset', 6)
Dataset6_1.insert(10,'Frequency',  204.8)
Dataset6_1.insert(11,'Trial', np.nan)
Dataset6_1.insert(12,'X_Acc_6', np.nan)
Dataset6_1.insert(13,'Y_Acc_6', np.nan)
Dataset6_1.insert(14,'Z_Acc_6', np.nan)
Dataset6_1.insert(15,'TimeStamp', np.nan)
Dataset6_1 = Dataset6_1.rename(columns={'Aticity': 'Activity'})


Dataset6_1 = Dataset6_1.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])

Realizamos la conversión inicial de unidades

In [ ]:
Dataset6_1['X_Acc'] = Dataset6_1['X_Acc'] * 9.81
Dataset6_1['Y_Acc'] = Dataset6_1['Y_Acc'] * 9.81
Dataset6_1['Z_Acc'] = Dataset6_1['Z_Acc'] * 9.81

In [ ]:
# Eliminamos las columnas que ya no necesitamos
Dataset6 = Dataset6_1.drop(columns=['X_Acc_6', 'Y_Acc_6', 'Z_Acc_6'])
Dataset6

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,6,1,0.562211,1.569894,-0.095539,238.5600,51.564,174.590,211,NaN,204.8,1,NaN
1,6,1,0.217223,1.805825,-0.376007,243.6900,59.620,166.170,211,NaN,204.8,1,NaN
2,6,1,-0.012777,2.002417,-0.295870,246.6200,65.112,156.290,211,NaN,204.8,1,NaN
3,6,1,-0.319433,2.041755,-0.255806,250.6400,70.605,145.300,211,NaN,204.8,1,NaN
4,6,1,-0.664431,2.041755,-0.335934,253.5700,75.731,134.320,211,NaN,204.8,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686818,6,13,-0.454213,12.695121,-1.865470,9.6677,-21.034,73.127,223,NaN,204.8,19,NaN
4686819,6,13,-1.946010,10.614420,-0.983943,-25.4840,-21.034,84.844,223,NaN,204.8,19,NaN
4686820,6,13,-2.456424,7.210939,-0.255688,-62.1010,-29.822,108.280,223,NaN,204.8,19,NaN
4686821,6,13,-1.278635,1.424216,2.082271,-92.8590,-41.540,140.500,223,NaN,204.8,19,NaN
4686822,6,13,2.804287,8.383430,5.225198,-104.5800,-41.540,178.580,223,NaN,204.8,19,NaN

In [ ]:
Dataset6.to_csv("/content/drive/MyDrive/TESIS_DATASET/6. Daliac/Dataset_6_Final/Dataset_6.csv", index = False)

In [ ]:
import pandas as pd
import json

resultado1 = prueba.describe()

# Convertir el resultado en un diccionario
resultado_diccionario1 = resultado1.to_dict()


# Convertir el diccionario en una cadena JSON
json_string1 = json.dumps(resultado_diccionario1)

# Guardar la cadena JSON en un archivo .json
ruta_json1 = "/content/drive/MyDrive/TESIS_DATASET/6. Daliac/Dataset_6_Final/Dataset_6_Describe.json"

with open(ruta_json1, 'w') as archivo:
    archivo.write(json_string1)

## Actividades

In [ ]:
dataset6 = pd.read_csv("/content/drive/MyDrive/TESIS_DATASET/6. Daliac/Dataset_6_Final/Dataset_6.csv")
dataset6

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,6,1,0.562211,1.569894,-0.095539,238.5600,51.564,174.590,211,NaN,204.8,1,NaN
1,6,1,0.217223,1.805825,-0.376007,243.6900,59.620,166.170,211,NaN,204.8,1,NaN
2,6,1,-0.012777,2.002417,-0.295870,246.6200,65.112,156.290,211,NaN,204.8,1,NaN
3,6,1,-0.319433,2.041755,-0.255806,250.6400,70.605,145.300,211,NaN,204.8,1,NaN
4,6,1,-0.664431,2.041755,-0.335934,253.5700,75.731,134.320,211,NaN,204.8,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18747287,6,13,-0.454213,12.695121,-1.865470,9.6677,-21.034,73.127,223,NaN,204.8,19,NaN
18747288,6,13,-1.946010,10.614420,-0.983943,-25.4840,-21.034,84.844,223,NaN,204.8,19,NaN
18747289,6,13,-2.456424,7.210939,-0.255688,-62.1010,-29.822,108.280,223,NaN,204.8,19,NaN
18747290,6,13,-1.278635,1.424216,2.082271,-92.8590,-41.540,140.500,223,NaN,204.8,19,NaN
18747291,6,13,2.804287,8.383430,5.225198,-104.5800,-41.540,178.580,223,NaN,204.8,19,NaN

In [ ]:
dataset6["Activity"].unique()

1
2
3
4
5
6
7
8
9
10
11
12
13

In [ ]:
data = dataset6.copy()

activity_mapping = {
    1: 16,
    2: 18,
    3: 17,
    4: 30,
    5: 22,
    6: 31,
    7: 6,
    8: 13,
    9: 14,
    10: 32,
    11: 33,
    12: 34,
    13: 25
}

data["Activity"] = data["Activity"].map(activity_mapping)

Valores en la columna 'Activity' reemplazados y archivo guardado.

In [ ]:
data

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,6,16,0.562211,1.569894,-0.095539,238.5600,51.564,174.590,211,NaN,204.8,1,NaN
1,6,16,0.217223,1.805825,-0.376007,243.6900,59.620,166.170,211,NaN,204.8,1,NaN
2,6,16,-0.012777,2.002417,-0.295870,246.6200,65.112,156.290,211,NaN,204.8,1,NaN
3,6,16,-0.319433,2.041755,-0.255806,250.6400,70.605,145.300,211,NaN,204.8,1,NaN
4,6,16,-0.664431,2.041755,-0.335934,253.5700,75.731,134.320,211,NaN,204.8,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18747287,6,25,-0.454213,12.695121,-1.865470,9.6677,-21.034,73.127,223,NaN,204.8,19,NaN
18747288,6,25,-1.946010,10.614420,-0.983943,-25.4840,-21.034,84.844,223,NaN,204.8,19,NaN
18747289,6,25,-2.456424,7.210939,-0.255688,-62.1010,-29.822,108.280,223,NaN,204.8,19,NaN
18747290,6,25,-1.278635,1.424216,2.082271,-92.8590,-41.540,140.500,223,NaN,204.8,19,NaN
18747291,6,25,2.804287,8.383430,5.225198,-104.5800,-41.540,178.580,223,NaN,204.8,19,NaN

In [ ]:
data = data.reset_index(drop=True)

## Resampling

In [ ]:
dataset6Final = resample_dataframe(data)

In [ ]:
dataset6Final

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
1,6,16,0.217223,1.805825,-0.376007,243.690,59.620,166.1700,211,NaN,50,1,NaN
4,6,16,-0.664431,2.041755,-0.335934,253.570,75.731,134.3200,211,NaN,50,1,NaN
6,6,16,-1.316110,2.041755,0.625652,252.480,84.519,110.1500,211,NaN,50,1,NaN
9,6,16,-2.466038,1.923839,1.106470,272.980,89.279,77.9260,211,NaN,50,1,NaN
11,6,16,-2.926029,2.081093,0.665726,290.920,90.378,57.0550,211,NaN,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18747268,6,25,-2.181548,-2.395700,-3.015300,74.113,-129.420,1.3582,223,NaN,50,19,NaN
18747270,6,25,1.744218,-1.828388,-4.356817,119.520,-103.060,29.1870,223,NaN,50,19,NaN
18747272,6,25,14.267664,1.159542,-5.046656,147.350,-32.752,48.2270,223,NaN,50,19,NaN
18747286,6,25,-0.022370,13.375935,-2.785353,44.820,-25.428,64.3390,223,NaN,50,19,NaN
18747289,6,25,-2.456424,7.210939,-0.255688,-62.101,-29.822,108.2800,223,NaN,50,19,NaN

In [ ]:
dataset6Final.to_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset6.csv', index=False)

## Análisis Gráfico Dataset 6

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset6.csv')
df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,6,30,-9.543560,-1.033974,-0.318580,-1.8476,0.287240,0.49911,202,NaN,40,2,NaN
1,6,6,1.030639,-5.131317,6.913794,19.2650,-122.440000,11.80300,204,NaN,40,10,NaN
2,6,33,-5.532644,-3.030505,7.517109,-18.1210,27.764000,1.39740,211,NaN,40,4,NaN
3,6,18,4.817102,-0.199457,8.238242,1.2854,-0.065115,-1.16570,211,NaN,40,2,NaN
4,6,34,-5.302697,5.895025,7.276666,5.3132,6.525900,-8.12290,211,NaN,40,18,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3661575,6,6,-9.287323,0.856933,-0.447326,-13.7670,-19.570000,4.28750,223,NaN,40,3,NaN
3661576,6,30,-9.874746,-0.696598,-0.165799,10.6020,-1.177400,-2.79640,202,NaN,40,12,NaN
3661577,6,6,-9.955188,-0.315539,2.388931,-15.2320,-9.317100,10.14600,223,NaN,40,4,NaN
3661578,6,6,-9.254165,-3.058169,-0.738722,-19.4240,7.976700,-7.92270,202,NaN,40,1,NaN
3661579,6,32,-9.601439,-9.506184,-3.705237,-56.2420,-45.934000,-175.87000,223,NaN,40,7,NaN

###Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(df)

### Valores Máximo y Mínimos Acelerometro

In [ ]:
grafico_acelerometro_max_min(df)

### Valores Válidos Giroscopio

In [ ]:
grafico_giroscopio_valido(df)

###Valores Máximo y Mínimos Giroscopio

In [ ]:
grafico_giroscopio_max_min(df)

###Actividades Válidas

In [ ]:
grafico_activity(df)

## Describe

In [ ]:
dataset6 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset6.csv')
dataset6

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,6,30,-9.543560,-1.033974,-0.318580,-1.8476,0.287240,0.49911,202,NaN,40,2,NaN
1,6,6,1.030639,-5.131317,6.913794,19.2650,-122.440000,11.80300,204,NaN,40,10,NaN
2,6,33,-5.532644,-3.030505,7.517109,-18.1210,27.764000,1.39740,211,NaN,40,4,NaN
3,6,18,4.817102,-0.199457,8.238242,1.2854,-0.065115,-1.16570,211,NaN,40,2,NaN
4,6,34,-5.302697,5.895025,7.276666,5.3132,6.525900,-8.12290,211,NaN,40,18,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3661575,6,6,-9.287323,0.856933,-0.447326,-13.7670,-19.570000,4.28750,223,NaN,40,3,NaN
3661576,6,30,-9.874746,-0.696598,-0.165799,10.6020,-1.177400,-2.79640,202,NaN,40,12,NaN
3661577,6,6,-9.955188,-0.315539,2.388931,-15.2320,-9.317100,10.14600,223,NaN,40,4,NaN
3661578,6,6,-9.254165,-3.058169,-0.738722,-19.4240,7.976700,-7.92270,202,NaN,40,1,NaN
3661579,6,32,-9.601439,-9.506184,-3.705237,-56.2420,-45.934000,-175.87000,223,NaN,40,7,NaN

In [ ]:
data.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
count,18747292.0,1.874729e+07,1.874729e+07,1.874729e+07,1.874729e+07,1.874729e+07,1.874729e+07,1.874729e+07,1.874729e+07,0.0,1.874729e+07,1.874729e+07,0.0
mean,6.0,2.207723e+01,-6.329035e+00,-9.249309e-01,1.021218e+00,-1.167531e+00,2.463482e+00,-5.180119e-01,2.100000e+02,NaN,2.048000e+02,1.001351e+01,NaN
std,0.0,1.075806e+01,7.203387e+00,8.228395e+00,5.104333e+00,6.455776e+01,6.753639e+01,9.243916e+01,8.215839e+00,NaN,7.787549e-12,5.460078e+00,NaN
min,6.0,6.000000e+00,-8.289548e+01,-8.262767e+01,-7.890575e+01,-8.017600e+02,-1.368500e+03,-1.877800e+03,2.020000e+02,NaN,2.048000e+02,1.000000e+00,NaN
25%,6.0,1.300000e+01,-9.874746e+00,-5.844504e+00,-1.368986e+00,-1.376700e+01,-1.289500e+01,-1.178500e+01,2.035000e+02,NaN,2.048000e+02,5.000000e+00,NaN
50%,6.0,2.500000e+01,-6.490983e+00,-3.217484e-01,1.047414e+00,-5.849400e-01,3.010500e-01,-6.722900e-02,2.075000e+02,NaN,2.048000e+02,1.000000e+01,NaN
75%,6.0,3.200000e+01,-9.710919e-01,2.395602e+00,3.385431e+00,1.120900e+01,1.558200e+01,1.216900e+01,2.140000e+02,NaN,2.048000e+02,1.500000e+01,NaN
max,6.0,3.400000e+01,8.502033e+01,7.808564e+01,8.380389e+01,1.267800e+03,1.045200e+03,9.065200e+02,2.230000e+02,NaN,2.048000e+02,1.900000e+01,NaN

In [ ]:
dataset6Final.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
count,4576975.0,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,0.0,4576975.0,4.576975e+06,0.0
mean,6.0,2.207955e+01,-6.329251e+00,-9.173356e-01,1.019786e+00,-1.155228e+00,2.486941e+00,-4.785032e-01,2.100025e+02,NaN,50.0,1.001186e+01,NaN
std,0.0,1.075903e+01,7.217002e+00,8.234118e+00,5.100830e+00,6.453012e+01,6.747449e+01,9.242980e+01,8.215882e+00,NaN,0.0,5.460712e+00,NaN
min,6.0,6.000000e+00,-8.285428e+01,-8.262767e+01,-7.618348e+01,-8.017600e+02,-1.274800e+03,-1.183600e+03,2.020000e+02,NaN,50.0,1.000000e+00,NaN
25%,6.0,1.300000e+01,-9.874746e+00,-5.844504e+00,-1.368986e+00,-1.376700e+01,-1.289500e+01,-1.178500e+01,2.040000e+02,NaN,50.0,5.000000e+00,NaN
50%,6.0,2.500000e+01,-6.490983e+00,-3.217484e-01,1.047414e+00,-5.849400e-01,3.010500e-01,-6.722900e-02,2.110000e+02,NaN,50.0,1.000000e+01,NaN
75%,6.0,3.200000e+01,-9.710919e-01,2.395602e+00,3.385431e+00,1.120900e+01,1.558200e+01,1.216900e+01,2.230000e+02,NaN,50.0,1.500000e+01,NaN
max,6.0,3.400000e+01,8.502033e+01,7.800716e+01,8.364300e+01,8.987200e+02,8.592300e+02,8.098500e+02,2.230000e+02,NaN,50.0,1.900000e+01,NaN

#Dataset Número 8.HARBox_Dataset_Daily_Activities_Recognition

## Preparación del Dataset Número 8

Comenzamos revisando un unico archivo

In [ ]:
HARBox_Dataset = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox'

In [ ]:
HARBox_Dataset_1 = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1'

In [ ]:
HARBox_Dataset_1_wave = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1/Wave_train.txt'

In [ ]:
import csv

with open(HARBox_Dataset_1_wave, 'r') as archivo_txt:

    contenido = archivo_txt.readlines()

    contenido = [linea.strip().split(' ') for linea in contenido]

    with open('HARBox_Dataset_1_wave.csv', 'w', newline='') as archivo_csv:

        writer = csv.writer(archivo_csv)
        writer.writerows(contenido)

In [ ]:
wave_train = pd.read_csv('HARBox_Dataset_1_wave.csv', header=None)
wave_train

,0,1,2,3,4,5,6,7,8,9
0,1.609662e+12,-2.470816,7.307104,5.937620,-0.046845,-0.093689,-0.172473,8.3125,-49.4375,-13.1875
1,1.609662e+12,-2.461239,7.259220,5.755661,-0.078784,-0.177797,-0.169279,9.0625,-49.4375,-13.5625
2,1.609662e+12,-2.336741,7.268796,5.793968,-0.141599,-0.234223,-0.161827,8.8750,-49.3125,-13.5625
3,1.609662e+12,-2.126051,7.096414,5.985504,-0.220383,-0.303425,-0.142663,8.7500,-49.3125,-13.5625
4,1.609662e+12,-2.202666,7.192182,6.215348,-0.289585,-0.361981,-0.117112,8.7500,-49.2500,-13.6250
...,...,...,...,...,...,...,...,...,...,...
4695,1.609662e+12,0.593762,7.402872,6.397307,0.030875,0.209736,0.040457,-7.8125,-36.2500,-39.3125
4696,1.609662e+12,0.785298,7.259220,6.502652,-0.002129,0.166086,0.051103,-7.8125,-36.2500,-39.3125
4697,1.609662e+12,0.938527,7.211336,6.531382,-0.015970,0.151180,0.024487,-7.8125,-36.2500,-39.3125
4698,1.609662e+12,0.794875,7.278373,6.579266,-0.036198,0.134146,-0.035133,-7.8125,-36.2500,-39.3125
4699,1.609662e+12,0.794875,7.278373,6.579266,-0.045780,0.093689,-0.069202,-7.8125,-36.2500,-39.3125

En la literatura encontrada no sé especifican las columnas, sin embargo esta si menciona que son los datos de una IMU de 9 ejes, proporcionando esta información a una IA, esta determinó las columnas, en base a esto se asignaron:

In [ ]:
header = ['timestamp', 'x_accel', 'y_accel', 'z_accel', 'x_gyro', 'y_gyro', 'z_gyro', 'x_magn', 'y_magn',
          'z_magn']
wave_train.columns = header

In [ ]:
wave_train

,timestamp,x_accel,y_accel,z_accel,x_gyro,y_gyro,z_gyro,x_magn,y_magn,z_magn
0,1.609662e+12,-2.470816,7.307104,5.937620,-0.046845,-0.093689,-0.172473,8.3125,-49.4375,-13.1875
1,1.609662e+12,-2.461239,7.259220,5.755661,-0.078784,-0.177797,-0.169279,9.0625,-49.4375,-13.5625
2,1.609662e+12,-2.336741,7.268796,5.793968,-0.141599,-0.234223,-0.161827,8.8750,-49.3125,-13.5625
3,1.609662e+12,-2.126051,7.096414,5.985504,-0.220383,-0.303425,-0.142663,8.7500,-49.3125,-13.5625
4,1.609662e+12,-2.202666,7.192182,6.215348,-0.289585,-0.361981,-0.117112,8.7500,-49.2500,-13.6250
...,...,...,...,...,...,...,...,...,...,...
4695,1.609662e+12,0.593762,7.402872,6.397307,0.030875,0.209736,0.040457,-7.8125,-36.2500,-39.3125
4696,1.609662e+12,0.785298,7.259220,6.502652,-0.002129,0.166086,0.051103,-7.8125,-36.2500,-39.3125
4697,1.609662e+12,0.938527,7.211336,6.531382,-0.015970,0.151180,0.024487,-7.8125,-36.2500,-39.3125
4698,1.609662e+12,0.794875,7.278373,6.579266,-0.036198,0.134146,-0.035133,-7.8125,-36.2500,-39.3125
4699,1.609662e+12,0.794875,7.278373,6.579266,-0.045780,0.093689,-0.069202,-7.8125,-36.2500,-39.3125

los valores tanto de timpstamp como del magnetometro los eliminamos

In [ ]:
wave_train.drop(columns=['timestamp','x_magn',	'y_magn' ,	'z_magn'], inplace=True)
wave_train

       x_accel   y_accel   z_accel    x_gyro    y_gyro    z_gyro
0    -2.470816  7.307104  5.937620 -0.046845 -0.093689 -0.172473
1    -2.461239  7.259220  5.755661 -0.078784 -0.177797 -0.169279
2    -2.336741  7.268796  5.793968 -0.141599 -0.234223 -0.161827
3    -2.126051  7.096414  5.985504 -0.220383 -0.303425 -0.142663
4    -2.202666  7.192182  6.215348 -0.289585 -0.361981 -0.117112
...        ...       ...       ...       ...       ...       ...
4695  0.593762  7.402872  6.397307  0.030875  0.209736  0.040457
4696  0.785298  7.259220  6.502652 -0.002129  0.166086  0.051103
4697  0.938527  7.211336  6.531382 -0.015970  0.151180  0.024487
4698  0.794875  7.278373  6.579266 -0.036198  0.134146 -0.035133
4699  0.794875  7.278373  6.579266 -0.045780  0.093689 -0.069202

[4700 rows x 6 columns]

Para el proceso de unión debemos agregar 2 columnas, una para la actividad y otra para el sujeto. Por el momento a la actividad wave se le asiganara el valor 1.

In [ ]:
wave_train.insert(0, 'Subject', 1)
wave_train.insert(1, 'Activity', 1)
wave_train

,Subject,Activity,x_accel,y_accel,z_accel,x_gyro,y_gyro,z_gyro
0,1,1,-2.470816,7.307104,5.937620,-0.046845,-0.093689,-0.172473
1,1,1,-2.461239,7.259220,5.755661,-0.078784,-0.177797,-0.169279
2,1,1,-2.336741,7.268796,5.793968,-0.141599,-0.234223,-0.161827
3,1,1,-2.126051,7.096414,5.985504,-0.220383,-0.303425,-0.142663
4,1,1,-2.202666,7.192182,6.215348,-0.289585,-0.361981,-0.117112
...,...,...,...,...,...,...,...,...
4695,1,1,0.593762,7.402872,6.397307,0.030875,0.209736,0.040457
4696,1,1,0.785298,7.259220,6.502652,-0.002129,0.166086,0.051103
4697,1,1,0.938527,7.211336,6.531382,-0.015970,0.151180,0.024487
4698,1,1,0.794875,7.278373,6.579266,-0.036198,0.134146,-0.035133
4699,1,1,0.794875,7.278373,6.579266,-0.045780,0.093689,-0.069202

Pprocedemos a crear el primer while para unir las 5 actividades en el sujeto 1, no eliminamos el timestamp en este caso

In [ ]:
import csv

files = {
    "wave": "Wave_train.txt",
    "walk": "Walk_train.txt",
    "typing": "typing_train.txt",
    "hop": "Hop_train.txt",
    "call": "Call_train.txt"
}

for activity, filename in files.items():
    path = "/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1/{}".format(filename)
    with open(path, 'r') as archivo_txt:
        contenido = archivo_txt.readlines()
        contenido = [linea.strip().split(' ') for linea in contenido]
        with open('HARBox_Dataset_1_{}.csv'.format(activity), 'w', newline='') as archivo_csv:
            writer = csv.writer(archivo_csv)
            writer.writerows(contenido)
    df = pd.read_csv('HARBox_Dataset_1_{}.csv'.format(activity), header=None)
    header = ['timestamp', 'x_accel', 'y_accel', 'z_accel', 'x_gyro', 'y_gyro', 'z_gyro', 'x_magn', 'y_magn', 'z_magn']
    df.columns = header
    df.drop(columns=['x_magn', 'y_magn', 'z_magn'], inplace=True)
    df.insert(0, 'Subject', 1)
    df.insert(1, 'Activity', activity.capitalize())
    globals()["{}_train".format(activity)] = df

    df.to_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1/{}_train_limpio.csv'.format(filename), index=False)

In [ ]:
Wave = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1/Wave_train.txt_train_limpio.csv')
Walk = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1/Walk_train.txt_train_limpio.csv')
Hop = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1/Hop_train.txt_train_limpio.csv')
Call = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1/Call_train.txt_train_limpio.csv')
typing = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/1/typing_train.txt_train_limpio.csv')

In [ ]:
Subject = pd.concat([Wave, Walk, Hop, Call, typing], ignore_index=True)

Subject.to_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/Subject_1.csv', index=False)

Aplicamos el código a todos los archivos

In [ ]:
contador = 1

while contador < 121:

  files = {
      "wave": "Wave_train.txt",
      "walk": "Walk_train.txt",
      "typing": "typing_train.txt",
      "hop": "Hop_train.txt",
      "call": "Call_train.txt"
  }

  for activity, filename in files.items():
      path = "/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/{}".format(contador, filename)
      with open(path, 'r') as archivo_txt:
          contenido = archivo_txt.readlines()
          contenido = [linea.strip().split(' ') for linea in contenido]
          with open('HARBox_Dataset_1_{}.csv'.format(activity), 'w', newline='') as archivo_csv:
              writer = csv.writer(archivo_csv)
              writer.writerows(contenido)
      df = pd.read_csv('HARBox_Dataset_1_{}.csv'.format(activity), header=None)
      header = ['timestamp', 'x_accel', 'y_accel', 'z_accel', 'x_gyro', 'y_gyro', 'z_gyro', 'x_magn', 'y_magn', 'z_magn']
      df.columns = header
      df.drop(columns=['x_magn', 'y_magn', 'z_magn'], inplace=True)
      df.insert(0, 'Subject', contador)
      df.insert(1, 'Activity', activity.capitalize())
      globals()["{}_train".format(activity)] = df

      df.to_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/{}_train_limpio.csv'.format(contador, filename), index=False)

  Wave = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/Wave_train.txt_train_limpio.csv'.format(contador))
  Walk = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/Walk_train.txt_train_limpio.csv'.format(contador))
  Hop = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/Hop_train.txt_train_limpio.csv'.format(contador))
  Call = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/Call_train.txt_train_limpio.csv'.format(contador))
  typing = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/typing_train.txt_train_limpio.csv'.format(contador))

  Subject = pd.concat([Call, Hop, typing, Walk, Wave], ignore_index=True)

  Subject.to_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/Files_Cleaned/{}.csv'.format(contador), index=False)
  y = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/Files_Cleaned/{}.csv'.format(contador)
  globals()[contador] = pd.read_csv(y)
  contador = contador + 1

Realizamos una modificación debido a que algunos de los archivos no contaban con las mismas actividades por lo que debemos hacer excepciones

In [ ]:
import os.path
contador = 1

while contador < 121:

  files = {
      "wave": "Wave_train.txt",
      "walk": "Walk_train.txt",
      "typing": "typing_train.txt",
      "hop": "Hop_train.txt",
      "call": "Call_train.txt"
  }

  for activity, filename in files.items():
    path = "/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/{}".format(contador, filename)
    if os.path.isfile(path):
        with open(path, 'r') as archivo_txt:
            contenido = archivo_txt.readlines()
            contenido = [linea.strip().split(' ') for linea in contenido]
            with open('HARBox_Dataset_1_{}.csv'.format(activity), 'w', newline='') as archivo_csv:
                writer = csv.writer(archivo_csv)
                writer.writerows(contenido)
        df = pd.read_csv('HARBox_Dataset_1_{}.csv'.format(activity), header=None)
        header = ['timestamp', 'x_accel', 'y_accel', 'z_accel', 'x_gyro', 'y_gyro', 'z_gyro', 'x_magn', 'y_magn', 'z_magn']
        df.columns = header
        df.drop(columns=['x_magn', 'y_magn', 'z_magn'], inplace=True)
        df.insert(0, 'Subject', contador)
        df.insert(1, 'Activity', activity.capitalize())
        globals()["{}_train".format(activity)] = df

        df.to_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/{}_train_limpio.csv'.format(contador, filename), index=False)
    else:
        print("El archivo {} no se encuentra".format(filename))

  try:
    Wave = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/Wave_train.txt_train_limpio.csv'.format(contador))
  except FileNotFoundError:
    Wave = None
  try:
    Walk = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/Walk_train.txt_train_limpio.csv'.format(contador))
  except FileNotFoundError:
    Walk = None
  try:
    Hop = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/Hop_train.txt_train_limpio.csv'.format(contador))
  except FileNotFoundError:
    Hop = None
  try:
    Call = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/Call_train.txt_train_limpio.csv'.format(contador))
  except FileNotFoundError:
    Call = None
  try:
    typing = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/{}/typing_train.txt_train_limpio.csv'.format(contador))
  except FileNotFoundError:
    typing = None

  Subject = pd.concat([df for df in [Call, Hop, typing, Walk, Wave] if df is not None], ignore_index=True)

  Subject.to_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/Files_Cleaned/{}.csv'.format(contador), index=False)
  y = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/Files_Cleaned/{}.csv'.format(contador)
  globals()[contador] = pd.read_csv(y)
  contador = contador + 1

El archivo Wave_train.txt no se encuentra
El archivo Wave_train.txt no se encuentra
El archivo Wave_train.txt no se encuentra
El archivo Call_train.txt no se encuentra
El archivo Call_train.txt no se encuentra
El archivo Hop_train.txt no se encuentra
El archivo Call_train.txt no se encuentra
El archivo typing_train.txt no se encuentra
El archivo typing_train.txt no se encuentra

In [ ]:
globals()[120]

,Subject,Activity,timestamp,x_accel,y_accel,z_accel,x_gyro,y_gyro,z_gyro
0,120,Call,1.609500e+12,1.641311,6.562708,6.715075,0.355192,0.019146,0.281452
1,120,Call,1.609500e+12,1.524896,6.788385,5.874815,0.322711,-0.019181,0.182631
2,120,Call,1.609500e+12,1.198719,6.705900,5.744906,0.126728,0.117670,0.131772
3,120,Call,1.609500e+12,0.916012,6.570666,6.165989,0.015341,0.203680,0.128735
4,120,Call,1.609500e+12,1.062346,6.645471,6.491868,0.073478,0.094352,0.110322
...,...,...,...,...,...,...,...,...,...
23495,120,Wave,1.609500e+12,5.705287,0.987714,9.883063,-2.836090,4.489231,7.211107
23496,120,Wave,1.609500e+12,7.338850,1.202904,10.804380,-3.072006,5.281750,6.938015
23497,120,Wave,1.609500e+12,7.287845,1.019499,11.859612,-2.859164,5.192686,6.585581
23498,120,Wave,1.609500e+12,9.263415,2.443427,13.746184,-2.340591,4.771242,5.822104
23499,120,Wave,1.609500e+12,9.962502,3.196202,14.536328,-1.470370,4.280088,4.811210

Ya tenemos los 120 archivos, ahora procedemos a unirlos para obtener nuestro dataset final

In [ ]:
#Union de los csv

# Ruta de la carpeta con los archivos CSV
folder_path = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/large_scale_HARBox/Files_Cleaned/'

# Obtener la lista de todos los archivos CSV en la carpeta
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

# Leer cada archivo CSV en un DataFrame y concatenarlos verticalmente
dfs = []
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    dfs.append(df)

concatenated_df = pd.concat(dfs, axis=0, ignore_index=True)

# Ruta para guardar el archivo CSV concatenado
output_folder = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/Dataset8/'
output_file = os.path.join(output_folder, 'dataset_8_1.csv')

# Guardar el archivo CSV concatenado en la ruta especificada
concatenated_df.to_csv(output_file, index=False)

In [ ]:
concatenated_df

,Subject,Activity,timestamp,x_accel,y_accel,z_accel,x_gyro,y_gyro,z_gyro
0,1,Call,1.609661e+12,-1.359907,9.701305,1.991976,0.597269,0.633467,0.007453
1,1,Call,1.609661e+12,-1.244985,9.720459,1.647211,0.684570,0.678183,0.057491
2,1,Call,1.609661e+12,-1.024718,9.682152,1.283292,0.754837,0.755902,0.106465
3,1,Call,1.609661e+12,-0.890643,9.710882,0.746991,0.784648,0.765484,0.113918
4,1,Call,1.609661e+12,-0.727837,9.720459,0.172383,0.716510,0.755902,0.106465
...,...,...,...,...,...,...,...,...,...
3411495,120,Wave,1.609500e+12,5.705287,0.987714,9.883063,-2.836090,4.489231,7.211107
3411496,120,Wave,1.609500e+12,7.338850,1.202904,10.804380,-3.072006,5.281750,6.938015
3411497,120,Wave,1.609500e+12,7.287845,1.019499,11.859612,-2.859164,5.192686,6.585581
3411498,120,Wave,1.609500e+12,9.263415,2.443427,13.746184,-2.340591,4.771242,5.822104
3411499,120,Wave,1.609500e+12,9.962502,3.196202,14.536328,-1.470370,4.280088,4.811210

In [ ]:
concatenated_df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/Dataset8/dataset_8_1.csv')

In [ ]:
concatenated_df

,Subject,Activity,timestamp,x_accel,y_accel,z_accel,x_gyro,y_gyro,z_gyro
0,1,Call,1.609661e+12,-1.359907,9.701305,1.991976,0.597269,0.633467,0.007453
1,1,Call,1.609661e+12,-1.244985,9.720459,1.647211,0.684570,0.678183,0.057491
2,1,Call,1.609661e+12,-1.024718,9.682152,1.283292,0.754837,0.755902,0.106465
3,1,Call,1.609661e+12,-0.890643,9.710882,0.746991,0.784648,0.765484,0.113918
4,1,Call,1.609661e+12,-0.727837,9.720459,0.172383,0.716510,0.755902,0.106465
...,...,...,...,...,...,...,...,...,...
3411495,120,Wave,1.609500e+12,5.705287,0.987714,9.883063,-2.836090,4.489231,7.211107
3411496,120,Wave,1.609500e+12,7.338850,1.202904,10.804380,-3.072006,5.281750,6.938015
3411497,120,Wave,1.609500e+12,7.287845,1.019499,11.859612,-2.859164,5.192686,6.585581
3411498,120,Wave,1.609500e+12,9.263415,2.443427,13.746184,-2.340591,4.771242,5.822104
3411499,120,Wave,1.609500e+12,9.962502,3.196202,14.536328,-1.470370,4.280088,4.811210

Realizamos las modificaciones necesarias

In [ ]:
concatenated_df.insert(9,'Dataset', 8)
concatenated_df.insert(10,'X_Acc_6', np.nan)
concatenated_df.insert(11,'Y_Acc_6', np.nan)
concatenated_df.insert(12,'Z_Acc_6', np.nan)
concatenated_df.insert(13,'Code', 201)
concatenated_df.insert(14,'Frequency', 50)
concatenated_df.insert(15,'Trial', np.nan)
concatenated_df = concatenated_df.rename(columns={'x_accel': 'X_Acc'})
concatenated_df = concatenated_df.rename(columns={'y_accel': 'Y_Acc'})
concatenated_df = concatenated_df.rename(columns={'z_accel': 'Z_Acc'})
concatenated_df = concatenated_df.rename(columns={'x_gyro': 'X_Gyro'})
concatenated_df = concatenated_df.rename(columns={'y_gyro': 'Y_Gyro'})
concatenated_df = concatenated_df.rename(columns={'z_gyro': 'Z_Gyro'})
concatenated_df = concatenated_df.rename(columns={'timestamp': 'TimeStamp'})
concatenated_df = concatenated_df.rename(columns={'Subject': 'User'})

concatenated_df = concatenated_df.reindex(columns=['Dataset','Activity','X_Acc','Y_Acc','Z_Acc','X_Gyro','Y_Gyro','Z_Gyro','X_Acc_6','Y_Acc_6','Z_Acc_6','Code','TimeStamp','Frequency','User','Trial'])
concatenated_df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,8,Call,-1.359907,9.701305,1.991976,0.597269,0.633467,0.007453,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
1,8,Call,-1.244985,9.720459,1.647211,0.684570,0.678183,0.057491,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
2,8,Call,-1.024718,9.682152,1.283292,0.754837,0.755902,0.106465,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
3,8,Call,-0.890643,9.710882,0.746991,0.784648,0.765484,0.113918,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
4,8,Call,-0.727837,9.720459,0.172383,0.716510,0.755902,0.106465,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411495,8,Wave,5.705287,0.987714,9.883063,-2.836090,4.489231,7.211107,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411496,8,Wave,7.338850,1.202904,10.804380,-3.072006,5.281750,6.938015,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411497,8,Wave,7.287845,1.019499,11.859612,-2.859164,5.192686,6.585581,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411498,8,Wave,9.263415,2.443427,13.746184,-2.340591,4.771242,5.822104,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411499,8,Wave,9.962502,3.196202,14.536328,-1.470370,4.280088,4.811210,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN

In [ ]:
concatenated_df.to_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/Dataset8_Final/Dataset8.csv', index = False)

In [ ]:
Dataset8 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/Dataset8_Final/Dataset8.csv')

In [ ]:
Dataset8

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,8,Call,-1.359907,9.701305,1.991976,0.597269,0.633467,0.007453,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
1,8,Call,-1.244985,9.720459,1.647211,0.684570,0.678183,0.057491,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
2,8,Call,-1.024718,9.682152,1.283292,0.754837,0.755902,0.106465,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
3,8,Call,-0.890643,9.710882,0.746991,0.784648,0.765484,0.113918,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
4,8,Call,-0.727837,9.720459,0.172383,0.716510,0.755902,0.106465,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411495,8,Wave,5.705287,0.987714,9.883063,-2.836090,4.489231,7.211107,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411496,8,Wave,7.338850,1.202904,10.804380,-3.072006,5.281750,6.938015,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411497,8,Wave,7.287845,1.019499,11.859612,-2.859164,5.192686,6.585581,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411498,8,Wave,9.263415,2.443427,13.746184,-2.340591,4.771242,5.822104,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411499,8,Wave,9.962502,3.196202,14.536328,-1.470370,4.280088,4.811210,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN

In [ ]:
# Convertimos de radianes a grados
Dataset8['X_Gyro'] = np.degrees(Dataset8['X_Gyro'])
Dataset8['Y_Gyro'] = np.degrees(Dataset8['Y_Gyro'])
Dataset8['Z_Gyro'] = np.degrees(Dataset8['Z_Gyro'])
Dataset8

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,X_Acc_6,Y_Acc_6,Z_Acc_6,Code,TimeStamp,Frequency,User,Trial
0,8,Call,-1.359907,9.701305,1.991976,34.221000,36.295000,0.427000,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
1,8,Call,-1.244985,9.720459,1.647211,39.223000,38.857001,3.294000,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
2,8,Call,-1.024718,9.682152,1.283292,43.249000,43.310001,6.100000,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
3,8,Call,-0.890643,9.710882,0.746991,44.956998,43.859001,6.527000,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
4,8,Call,-0.727837,9.720459,0.172383,41.052999,43.310001,6.100000,NaN,NaN,NaN,201,1.609661e+12,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411495,8,Wave,5.705287,0.987714,9.883063,-162.496006,257.213996,413.166011,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411496,8,Wave,7.338850,1.202904,10.804380,-176.013005,302.621995,397.519004,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411497,8,Wave,7.287845,1.019499,11.859612,-163.818003,297.518997,377.325987,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411498,8,Wave,9.263415,2.443427,13.746184,-134.105997,273.372010,333.581986,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN
3411499,8,Wave,9.962502,3.196202,14.536328,-84.245998,245.231003,275.662009,NaN,NaN,NaN,201,1.609500e+12,50,120,NaN

In [ ]:
from datetime import datetime

Dataset8['TimeStamp'] = Dataset8['TimeStamp'].astype('float64')

# Convertir el timestamp a segundos
Dataset8['TimeStamp'] = Dataset8['TimeStamp'] / 1000

Dataset8['TimeStamp'] = Dataset8['TimeStamp'].apply(lambda x: datetime.utcfromtimestamp(x).strftime('%Y-%m-%d.%H-%M-%S'))

In [ ]:
Dataset8 = Dataset8.drop(['X_Acc_6', 'Y_Acc_6', 'Z_Acc_6'], axis=1)

In [ ]:
Dataset8

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,8,Call,-1.359907,9.701305,1.991976,34.221000,36.295000,0.427000,201,2021-01-03.08-09-55,50,1,NaN
1,8,Call,-1.244985,9.720459,1.647211,39.223000,38.857001,3.294000,201,2021-01-03.08-09-55,50,1,NaN
2,8,Call,-1.024718,9.682152,1.283292,43.249000,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
3,8,Call,-0.890643,9.710882,0.746991,44.956998,43.859001,6.527000,201,2021-01-03.08-09-55,50,1,NaN
4,8,Call,-0.727837,9.720459,0.172383,41.052999,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411495,8,Wave,5.705287,0.987714,9.883063,-162.496006,257.213996,413.166011,201,2021-01-01.11-23-02,50,120,NaN
3411496,8,Wave,7.338850,1.202904,10.804380,-176.013005,302.621995,397.519004,201,2021-01-01.11-23-02,50,120,NaN
3411497,8,Wave,7.287845,1.019499,11.859612,-163.818003,297.518997,377.325987,201,2021-01-01.11-23-02,50,120,NaN
3411498,8,Wave,9.263415,2.443427,13.746184,-134.105997,273.372010,333.581986,201,2021-01-01.11-23-02,50,120,NaN
3411499,8,Wave,9.962502,3.196202,14.536328,-84.245998,245.231003,275.662009,201,2021-01-01.11-23-02,50,120,NaN

In [ ]:
Dataset8.to_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/Dataset8_Final/Dataset8.csv', index = False)

In [ ]:
Dataset8.describe()

,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,3411500.0,3.411500e+06,3.411500e+06,3.411500e+06,3.411500e+06,3.411500e+06,3.411500e+06,3411500.0,3411500.0,3.411500e+06,0.0
mean,8.0,4.737109e-01,2.603639e+00,4.160561e+00,9.991712e-01,1.648598e-01,1.138516e-01,201.0,50.0,6.358962e+01,NaN
std,0.0,6.906840e+00,6.358324e+00,6.666013e+00,7.928295e+01,6.761931e+01,1.083148e+02,0.0,0.0,3.373671e+01,NaN
min,8.0,-7.850138e+01,-7.823334e+01,-7.827900e+01,-1.437759e+03,-1.271542e+03,-1.170590e+03,201.0,50.0,1.000000e+00,NaN
25%,8.0,-2.278679e+00,3.348389e-01,-7.330916e-01,-1.356052e+01,-1.421204e+01,-1.525720e+01,201.0,50.0,3.600000e+01,NaN
50%,8.0,6.200000e-02,3.833112e+00,4.239000e+00,0.000000e+00,0.000000e+00,0.000000e+00,201.0,50.0,6.700000e+01,NaN
75%,8.0,3.576000e+00,6.494000e+00,8.730686e+00,1.520286e+01,1.511657e+01,1.515300e+01,201.0,50.0,9.100000e+01,NaN
max,8.0,7.830984e+01,7.776397e+01,7.900761e+01,1.741688e+03,1.365667e+03,1.352837e+03,201.0,50.0,1.200000e+02,NaN

In [ ]:
import pandas as pd
import json

resultado1 = prueba.describe()

# Convertir el resultado en un diccionario
resultado_diccionario1 = resultado1.to_dict()


# Convertir el diccionario en una cadena JSON
json_string1 = json.dumps(resultado_diccionario1)

# Guardar la cadena JSON en un archivo .json
ruta_json1 = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/Dataset8_Final/Dataset8_describe.json'

with open(ruta_json1, 'w') as archivo:
    archivo.write(json_string1)

## Actividades

In [ ]:
dataset8 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/Dataset8_Final/Dataset8.csv')
dataset8

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,8,Call,-1.359907,9.701305,1.991976,34.221000,36.295000,0.427000,201,2021-01-03.08-09-55,50,1,NaN
1,8,Call,-1.244985,9.720459,1.647211,39.223000,38.857001,3.294000,201,2021-01-03.08-09-55,50,1,NaN
2,8,Call,-1.024718,9.682152,1.283292,43.249000,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
3,8,Call,-0.890643,9.710882,0.746991,44.956998,43.859001,6.527000,201,2021-01-03.08-09-55,50,1,NaN
4,8,Call,-0.727837,9.720459,0.172383,41.052999,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411495,8,Wave,5.705287,0.987714,9.883063,-162.496006,257.213996,413.166011,201,2021-01-01.11-23-02,50,120,NaN
3411496,8,Wave,7.338850,1.202904,10.804380,-176.013005,302.621995,397.519004,201,2021-01-01.11-23-02,50,120,NaN
3411497,8,Wave,7.287845,1.019499,11.859612,-163.818003,297.518997,377.325987,201,2021-01-01.11-23-02,50,120,NaN
3411498,8,Wave,9.263415,2.443427,13.746184,-134.105997,273.372010,333.581986,201,2021-01-01.11-23-02,50,120,NaN
3411499,8,Wave,9.962502,3.196202,14.536328,-84.245998,245.231003,275.662009,201,2021-01-01.11-23-02,50,120,NaN

In [ ]:
dataset8["Activity"].unique()

Call
Hop
Typing
Walk
Wave

In [ ]:
remapping = {
    'Call': 3,
    'Hop': 35,
    'Typing': 37,
    'Walk': 6,
    'Wave': 36
}

df = dataset8.copy()

df['Activity'] = df['Activity'].map(remapping)

Remapeo y guardado completados.

In [ ]:
df

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,8,3,-1.359907,9.701305,1.991976,34.221000,36.295000,0.427000,201,2021-01-03.08-09-55,50,1,NaN
1,8,3,-1.244985,9.720459,1.647211,39.223000,38.857001,3.294000,201,2021-01-03.08-09-55,50,1,NaN
2,8,3,-1.024718,9.682152,1.283292,43.249000,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
3,8,3,-0.890643,9.710882,0.746991,44.956998,43.859001,6.527000,201,2021-01-03.08-09-55,50,1,NaN
4,8,3,-0.727837,9.720459,0.172383,41.052999,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411495,8,36,5.705287,0.987714,9.883063,-162.496006,257.213996,413.166011,201,2021-01-01.11-23-02,50,120,NaN
3411496,8,36,7.338850,1.202904,10.804380,-176.013005,302.621995,397.519004,201,2021-01-01.11-23-02,50,120,NaN
3411497,8,36,7.287845,1.019499,11.859612,-163.818003,297.518997,377.325987,201,2021-01-01.11-23-02,50,120,NaN
3411498,8,36,9.263415,2.443427,13.746184,-134.105997,273.372010,333.581986,201,2021-01-01.11-23-02,50,120,NaN
3411499,8,36,9.962502,3.196202,14.536328,-84.245998,245.231003,275.662009,201,2021-01-01.11-23-02,50,120,NaN

## Resampling

In [ ]:
dataset8 = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset8.csv')
dataset8

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,8,3,-1.359907,9.701305,1.991976,34.221000,36.295000,0.427000,201,2021-01-03.08-09-55,50,1,NaN
1,8,3,-1.244985,9.720459,1.647211,39.223000,38.857001,3.294000,201,2021-01-03.08-09-55,50,1,NaN
2,8,3,-1.024718,9.682152,1.283292,43.249000,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
3,8,3,-0.890643,9.710882,0.746991,44.956998,43.859001,6.527000,201,2021-01-03.08-09-55,50,1,NaN
4,8,3,-0.727837,9.720459,0.172383,41.052999,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411495,8,36,5.705287,0.987714,9.883063,-162.496006,257.213996,413.166011,201,2021-01-01.11-23-02,50,120,NaN
3411496,8,36,7.338850,1.202904,10.804380,-176.013005,302.621995,397.519004,201,2021-01-01.11-23-02,50,120,NaN
3411497,8,36,7.287845,1.019499,11.859612,-163.818003,297.518997,377.325987,201,2021-01-01.11-23-02,50,120,NaN
3411498,8,36,9.263415,2.443427,13.746184,-134.105997,273.372010,333.581986,201,2021-01-01.11-23-02,50,120,NaN
3411499,8,36,9.962502,3.196202,14.536328,-84.245998,245.231003,275.662009,201,2021-01-01.11-23-02,50,120,NaN

In [ ]:
dataset8Final = resample_dataframe(df)

In [ ]:
dataset8Final

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
0,8,3,-1.359907,9.701305,1.991976,34.221000,36.295000,0.427000,201,2021-01-03.08-09-55,50,1,NaN
1,8,3,-1.244985,9.720459,1.647211,39.223000,38.857001,3.294000,201,2021-01-03.08-09-55,50,1,NaN
2,8,3,-1.024718,9.682152,1.283292,43.249000,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
3,8,3,-0.890643,9.710882,0.746991,44.956998,43.859001,6.527000,201,2021-01-03.08-09-55,50,1,NaN
4,8,3,-0.727837,9.720459,0.172383,41.052999,43.310001,6.100000,201,2021-01-03.08-09-55,50,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3411495,8,36,5.705287,0.987714,9.883063,-162.496006,257.213996,413.166011,201,2021-01-01.11-23-02,50,120,NaN
3411496,8,36,7.338850,1.202904,10.804380,-176.013005,302.621995,397.519004,201,2021-01-01.11-23-02,50,120,NaN
3411497,8,36,7.287845,1.019499,11.859612,-163.818003,297.518997,377.325987,201,2021-01-01.11-23-02,50,120,NaN
3411498,8,36,9.263415,2.443427,13.746184,-134.105997,273.372010,333.581986,201,2021-01-01.11-23-02,50,120,NaN
3411499,8,36,9.962502,3.196202,14.536328,-84.245998,245.231003,275.662009,201,2021-01-01.11-23-02,50,120,NaN

In [ ]:
dataset8Final.to_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset8.csv', index=False)

## Análisis Gráfico Dataset 8

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset8.csv')

###Valores Válidos Acelerometro

In [ ]:
grafico_acelerometro_valido(df)

### Valores Máximo y Mínimos Acelerometro

In [ ]:
grafico_acelerometro_max_min(df)

### Valores Válidos Giroscopio

In [ ]:
grafico_giroscopio_valido(df)

###Valores Máximo y Mínimos Giroscopio

In [ ]:
grafico_giroscopio_max_min(df)

###Actividades Válidas

In [ ]:
grafico_activity(df)

## Describe

In [ ]:
ruta_entrada = '/content/drive/MyDrive/TESIS_DATASET/8_HARBox_Dataset_Daily_Activities_Recognition/Dataset8_Final/Dataset8.csv'
ruta_salida = '/content/drive/MyDrive/TESIS_DATASET/Datasets definitivos_CSV/dataset8.csv'
dataset8_antes = pd.read_csv(ruta_entrada)
dataset8_despues = pd.read_csv(ruta_salida)

### Describe Antes

In [ ]:
dataset8_antes.describe()

,Dataset,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,Frequency,User,Trial
count,3411500.0,3.411500e+06,3.411500e+06,3.411500e+06,3.411500e+06,3.411500e+06,3.411500e+06,3411500.0,3411500.0,3.411500e+06,0.0
mean,8.0,4.737109e-01,2.603639e+00,4.160561e+00,9.991712e-01,1.648598e-01,1.138516e-01,201.0,50.0,6.358962e+01,NaN
std,0.0,6.906840e+00,6.358324e+00,6.666013e+00,7.928295e+01,6.761931e+01,1.083148e+02,0.0,0.0,3.373671e+01,NaN
min,8.0,-7.850138e+01,-7.823334e+01,-7.827900e+01,-1.437759e+03,-1.271542e+03,-1.170590e+03,201.0,50.0,1.000000e+00,NaN
25%,8.0,-2.278679e+00,3.348389e-01,-7.330916e-01,-1.356052e+01,-1.421204e+01,-1.525720e+01,201.0,50.0,3.600000e+01,NaN
50%,8.0,6.200000e-02,3.833112e+00,4.239000e+00,0.000000e+00,0.000000e+00,0.000000e+00,201.0,50.0,6.700000e+01,NaN
75%,8.0,3.576000e+00,6.494000e+00,8.730686e+00,1.520286e+01,1.511657e+01,1.515300e+01,201.0,50.0,9.100000e+01,NaN
max,8.0,7.830984e+01,7.776397e+01,7.900761e+01,1.741688e+03,1.365667e+03,1.352837e+03,201.0,50.0,1.200000e+02,NaN

### Describe Despues

In [ ]:
dataset8_despues.describe()

,Dataset,Activity,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Code,TimeStamp,Frequency,User,Trial
count,4576975.0,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,4.576975e+06,0.0,4576975.0,4.576975e+06,0.0
mean,6.0,2.207933e+01,-6.324408e+00,-9.227476e-01,1.024178e+00,-1.137367e+00,2.430360e+00,-5.070447e-01,2.099934e+02,NaN,50.0,1.001315e+01,NaN
std,0.0,1.075932e+01,7.203348e+00,8.225409e+00,5.117687e+00,6.454143e+01,6.758602e+01,9.249007e+01,8.211192e+00,NaN,0.0,5.460822e+00,NaN
min,6.0,6.000000e+00,-8.285428e+01,-8.258745e+01,-7.606870e+01,-7.212000e+02,-1.274800e+03,-1.438400e+03,2.020000e+02,NaN,50.0,1.000000e+00,NaN
25%,6.0,1.300000e+01,-9.874746e+00,-5.844504e+00,-1.368986e+00,-1.376700e+01,-1.289500e+01,-1.178500e+01,2.020000e+02,NaN,50.0,5.000000e+00,NaN
50%,6.0,2.500000e+01,-6.483821e+00,-3.217484e-01,1.047414e+00,-5.849400e-01,3.010500e-01,-6.722900e-02,2.040000e+02,NaN,50.0,1.000000e+01,NaN
75%,6.0,3.200000e+01,-9.645683e-01,2.395602e+00,3.385431e+00,1.120900e+01,1.558200e+01,1.216900e+01,2.110000e+02,NaN,50.0,1.500000e+01,NaN
max,6.0,3.400000e+01,8.502033e+01,7.574399e+01,8.149854e+01,7.372800e+02,7.363000e+02,7.937400e+02,2.230000e+02,NaN,50.0,1.900000e+01,NaN